/* notes.js: trang sổ tay VIẾT TAY cho các bài nền cốt lõi (chỗ người học dễ bí nhất). Dùng thuật ngữ y như trong bài học.
   Các bài còn lại vẫn dùng bản tự gom từ câu "rút ra" của bài (còn thô). Nạp sau notebook.js. */
(() => {
  const N = {
    k5: `<b>Máy không đoán ý.</b> Nó làm đúng từng lệnh, từ trên xuống, mỗi lần một lệnh.<br>• Lệnh phải <b>rõ, nhỏ, làm được ngay</b>. "Dọn phòng" là lệnh quá to; "nhặt cái áo lên" mới là lệnh máy làm được.<br>• Thiếu một lệnh hoặc sai thứ tự thì kết quả sai, dù ý bạn đúng.<br><b>Mẹo:</b> tự đóng vai máy. Làm từng lệnh một trên giấy và ghi lại điều gì đã thay đổi sau mỗi lệnh.`,
    k6: `<b>Nếu... thì...</b>: máy kiểm tra một điều kiện rồi chọn việc để làm.<br>• Điều kiện <b>đúng</b> → làm việc ở vế "thì".<br>• Điều kiện <b>sai</b> → làm việc ở vế "nếu không". (Sau này gọi là <code>if</code> và <code>else</code>.)<br><b>Ca biên:</b> khi giá trị đúng bằng ngưỡng. "Lớn hơn 5" khác "lớn hơn hoặc bằng 5": với đúng 5, câu đầu sai, câu sau đúng. Một chữ trong luật đổi thì kết quả đổi.`,
    k7: `<b>Lặp lại</b>: làm một việc nhiều lần, nhưng <b>phải biết dừng</b>.<br>• Mỗi vòng phải làm điều kiện dừng <b>tiến lại gần</b> hơn (ví dụ: bớt đi một quả táo, đếm thêm một lần). Nếu không thì lặp mãi không dừng.<br>• Số lần lặp không phải lúc nào cũng bằng "số cuối": đếm từ 1 đến 5 là lặp 5 lần, nhưng đếm 0, 1, 2 là lặp 3 lần.<br><b>Mẹo:</b> hỏi "việc nào làm cho vòng lặp sắp dừng?". Không trả lời được thì vòng lặp có nguy cơ vô hạn.`,
    p1: `<b>Biến là cái hộp có tên.</b><pre>x = 5      # đặt 5 vào hộp tên x\ny = x + 2  # lấy số đang ở hộp x, cộng 2, đặt vào hộp y\nx = 9      # gán lại: số cũ trong hộp x bị thay</pre>• <code>=</code> là <b>phép gán</b>, đọc là "đặt vào", không phải "bằng nhau" như trong toán.<br>• Vế phải được tính xong trước, rồi mới đặt vào hộp bên trái.<br>• Gán lại thì giá trị cũ <b>mất</b>.<br><b>Mẹo:</b> sau mỗi dòng, viết ra giá trị của mọi hộp. Dòng 3 ở trên: x = 9, y vẫn là 7 (y không tự đổi theo x).`,
    p2: `<b>if / else</b>: chọn một trong hai đường.<pre>if n > 5:\n    print("A")\nelse:\n    print("B")</pre>• Điều kiện đúng → chạy khối <code>if</code>; sai → chạy khối <code>else</code>. Chỉ một khối chạy.<br>• <b>Thụt dòng</b> (4 dấu cách) cho biết dòng nào nằm trong khối. Dấu <code>:</code> cuối dòng <code>if</code> và <code>else</code> là bắt buộc.<br>• So sánh: <code>&gt;</code> lớn hơn, <code>&gt;=</code> lớn hơn hoặc bằng, <code>==</code> bằng nhau (hai dấu bằng; một dấu bằng là phép gán).<br><b>Ca biên:</b> luôn thử đúng bằng ngưỡng.`,
    p3: `<b>Vòng lặp for</b>: chạy lại một khối lệnh nhiều lần.<pre>for i in range(3):\n    print(i)      # in 0, 1, 2</pre>• <code>range(3)</code> cho ra <b>0, 1, 2</b> (không có 3): <code>range(n)</code> là n số, từ 0 đến n - 1.<br>• Các dòng <b>thụt vào</b> dưới <code>for</code> là việc làm lại mỗi vòng. Dòng không thụt chạy một lần sau khi vòng lặp kết thúc.<br>• Mỗi vòng, <code>i</code> là hộp mang giá trị tiếp theo.<br><b>Mẹo:</b> kẻ bảng: vòng 1: i = 0, vòng 2: i = 1... rồi ghi giá trị các biến ở cuối mỗi vòng.`,
    p4: `<b>Hàm</b> là một đoạn lệnh có tên, nhận đầu vào và trả đầu ra.<pre>def gap_doi(x):\n    return x * 2\n\nprint(gap_doi(4))   # 8</pre>• <code>def</code> định nghĩa hàm; <code>x</code> là chỗ nhận đầu vào.<br>• <b><code>return</code> đưa kết quả ra ngoài</b> cho nơi gọi hàm, và kết thúc hàm ngay. Dòng nào nằm sau <code>return</code> sẽ không chạy.<br>• <code>print</code> chỉ hiện chữ lên màn hình, <b>không</b> đưa giá trị cho nơi gọi hàm. Muốn dùng kết quả tiếp thì phải <code>return</code>.<br>• Gọi hàm: <code>gap_doi(4)</code> chạy hàm với x = 4 và trả về 8.`,
    l1: `<b>Mảng (list)</b> là một dãy hộp xếp hàng, mỗi hộp có <b>chỉ số</b> bắt đầu từ 0.<pre>a = [7, 8, 9, 4]\n# chỉ số:  0  1  2  3</pre>• Hộp đầu có chỉ số <b>0</b>. Số 9 ở chỉ số 2; chỉ số 3 chứa số 4.<br>• Có n hộp thì các chỉ số là <b>0 đến n - 1</b>. Hộp cuối có chỉ số <b>n - 1</b> (ở ví dụ: 4 hộp, chỉ số cuối là 3).<br>• Chỉ số = số hộp đứng trước nó.<br><b>Mẹo kiểm tra:</b> viết các chỉ số ra giấy. Nếu bạn viết chỉ số bằng số hộp thì đã vượt quá cuối.`,
    a2: `<b>Đọc một hộp: <code>a[i]</code></b> lấy giá trị ở hộp có chỉ số i.<pre>a = [7, 8, 1]\nprint(a[1])   # 8\nprint(a[2])   # 1 (hộp cuối)</pre>• Đếm từ 0: <code>a[0]</code> là hộp đầu.<br>• Hộp cuối là <code>a[len(a) - 1]</code>.<br>• Chỉ số không có hộp (nhỏ hơn 0 hoặc từ <code>len(a)</code> trở lên) thì Python báo <b>IndexError</b>. Đó là cách máy nói "không có hộp đó".`,
    a3: `<b>Ghi đè một hộp: <code>a[i] = x</code></b> đặt x vào hộp i, thay giá trị cũ.<pre>a = [7, 8, 1]\na[0] = 9      # a thành [9, 8, 1]\na[0] = a[1] + 5   # lấy 8 + 5 = 13, a thành [13, 8, 1]</pre>• <b>Chỉ hộp i đổi</b>; các hộp khác giữ nguyên.<br>• Giá trị cũ của hộp i mất, nên muốn giữ thì phải lưu sang chỗ khác trước khi ghi đè.<br>• Vế phải tính xong rồi mới đặt vào hộp bên trái.`,
    sm: `<b>Cộng dồn</b>: tính tổng bằng một biến nhớ.<pre>total = 0\nfor x in a:\n    total = total + x</pre>• Bắt đầu từ <b>0</b> vì 0 là số "không có gì": cộng 0 vào đâu cũng không đổi.<br>• Mỗi vòng: lấy tổng cũ, cộng số mới, đặt lại vào <code>total</code>. Với [2, 5, 3]: 0 → 2 → 7 → 10.<br>• Mảng rỗng: vòng lặp không chạy lần nào, tổng là 0. Hợp lý.<br><b>Mẹo:</b> kẻ bảng hai cột "x" và "total sau vòng này".`,
    cn: `<b>Đếm số lần xuất hiện</b>: dùng một bộ đếm.<pre>c = 0\nfor x in a:\n    if x == 2:\n        c = c + 1</pre>• <code>c = 0</code> vì lúc đầu <b>chưa gặp lần nào</b>.<br>• Mỗi lần gặp đúng giá trị cần đếm thì <code>c</code> tăng 1; không gặp thì để nguyên.<br>• Chú ý <code>==</code> (so sánh) chứ không phải <code>=</code> (gán).<br>• Cuối vòng lặp, <code>c</code> là số lần gặp. Ở ví dụ: có bao nhiêu hộp chứa 2.`,
    l2: `<b>Tìm một số: mở từng hộp</b>, bắt đầu từ hộp chỉ số 0.<br>• Mở hộp i; <b>gặp</b> số cần tìm thì dừng và trả về <b>chỉ số i</b> (không phải chính số đó).<br>• Chỉ khi <b>đã mở hết mọi hộp</b> mà không gặp mới kết luận "không có" (thường trả -1).<br>• Có nhiều số giống nhau thì dừng ở lần gặp <b>đầu tiên</b>.<br><b>Lỗi hay gặp:</b> kết luận "không có" ngay sau hộp đầu tiên không khớp. Câu "không có" chỉ được nói sau khi hết vòng lặp.`,
    l3: `<b>Tìm số lớn nhất: tờ giấy nhớ.</b> Ghi số lớn nhất <b>đã thấy cho đến giờ</b> lên tờ giấy.<br>• Bắt đầu: ghi số ở hộp đầu tiên.<br>• Mỗi hộp tiếp theo: nếu số mới <b>lớn hơn</b> số trên giấy thì xóa đi, ghi số mới; nếu không thì giữ nguyên.<br>• Hết hộp: số trên giấy là số lớn nhất.<br><b>Vì sao bắt đầu từ hộp đầu, không phải 0?</b> Nếu mọi số đều âm thì 0 sẽ lớn hơn tất cả và cho kết quả sai.`
  };
  for (const id in N) if (LES[id] && !LES[id].note) LES[id].note = N[id];
})();
