/* notes-more.js: trang sổ tay VIẾT TAY đợt 2 cho 18 bài trước đây chỉ có bản tự gom (bx0, b2-b6, d1, d2, tp, stk, que, bs, bub, t1, t2, g1, dp2, ap5).
   Mỗi trang theo khuôn: ý chính, ví dụ chạy tay từng bước, lỗi hay gặp, mẹo tự kiểm tra. Dùng đúng ví dụ và thuật ngữ trong bài học.
   Mọi đoạn code trong <pre> được tools/verify-notes.js chạy bằng Python thật để đối chiếu kết quả ghi bên cạnh. Nạp sau notes.js. */
(() => {
  const N = {
    bx0: `<b>Biết các mảnh chưa đủ, còn phải biết mỗi chỗ cần mảnh gì.</b><br>Viết \"một cộng một bằng hai\" cần đúng 5 mảnh theo đúng thứ tự: <code>số</code> <code>phép tính</code> <code>số</code> <code>dấu bằng</code> <code>kết quả</code>.<pre>1 + 1 = 2     đúng: số, phép tính, số, bằng, kết quả\n1 + = 2       thiếu một số ở chỗ thứ ba\n1 1 + = 2     hai số đứng cạnh nhau, chưa có phép tính ở giữa</pre>• Ba dòng dùng <b>cùng các mảnh</b>, nhưng chỉ dòng đầu đúng. Lỗi nằm ở <b>thứ tự và vai trò</b>, không phải ở việc thiếu mảnh.<br>• Khi có mảnh thừa, đó là bẫy: hỏi \"chỗ nào còn trống, chỗ đó cần loại mảnh gì?\" rồi mới chọn.<br><b>Vì sao học bài này?</b> Code cũng vậy. Bạn hiểu \"cộng dồn vào tổng\" nhưng vẫn có thể viết sai thứ tự các mảnh. Từ đây trở đi, mỗi lần viết một dòng, hãy hỏi: mỗi chỗ trong dòng này giữ vai trò gì?<br><b>Mẹo:</b> đọc to dòng vừa viết bằng lời thường. Đọc không ra nghĩa thì thứ tự đang sai.`,

    b2: `<b>if / else và độ thụt dòng.</b><pre>if n &gt; 3:\n    print(\"A\")\nelse:\n    print(\"B\")</pre>• Dòng <code>if</code> (và <code>else</code>) <b>luôn kết thúc bằng dấu hai chấm</b> <code>:</code>. Thiếu thì Python báo <code>SyntaxError</code>.<br>• Các dòng <b>thụt vào 4 dấu cách</b> là khối việc thuộc về dòng ở ngay trên. Python dùng độ thụt để biết dòng nào nằm trong khối nào. Đây là <b>quy định</b>, không phải để cho đẹp.<br>• Chỉ <b>một</b> trong hai khối chạy: điều kiện đúng thì khối <code>if</code>, sai thì khối <code>else</code>.<br><b>Lỗi hay gặp:</b> quên dấu <code>:</code>; quên thụt dòng (Python báo lỗi); thụt không đều giữa các dòng của cùng một khối.<br><b>Mẹo:</b> nhìn thẳng cột. Hai dòng cùng khối thì thẳng hàng với nhau; dòng thuộc về <code>if</code> thì lùi vào so với <code>if</code>.`,

    b3: `<b>Vòng lặp: viết đúng dòng và đặt đúng chỗ.</b><pre>total = 0\nfor i in range(3):\n    total = total + i\nprint(total)</pre>• <code>for i in range(3):</code> nghĩa là: lặp lại, mỗi lần gọi số hiện tại là <code>i</code>, qua các số <b>0, 1, 2</b> (3 lần, không có 3).<br>• Dòng nằm <b>thụt vào</b> dưới <code>for</code> chạy ở <b>mỗi vòng</b>; dòng thẳng hàng với <code>for</code> chạy một lần khi vòng đã xong.<br>• Chạy tay: total = 0; i = 0 → 0; i = 1 → 1; i = 2 → 3. In ra 3.<br><b>Vì sao <code>total = 0</code> nằm TRÊN vòng for?</b> Việc chuẩn bị chỉ làm <b>một lần</b>, trước khi lặp. Nếu nằm trong vòng, mỗi vòng lại đặt về 0 và mất tổng đã cộng.<br><b>Mẹo:</b> với mỗi dòng, hỏi \"dòng này chạy một lần hay mỗi vòng?\" Câu trả lời nằm ở độ thụt.`,

    b4: `<b>Hàm: tạo hàm, trả kết quả, rồi gọi hàm.</b><pre>def gap_doi(x):\n    return x * 2\n\nprint(gap_doi(4))</pre>• <code>def gap_doi(x):</code> <b>tạo</b> hàm tên <code>gap_doi</code>, nhận vào <code>x</code>. Tạo xong thì hàm chưa chạy.<br>• <code>return x * 2</code> là việc hàm <b>trả ra</b> cho nơi gọi nó. Dòng này thụt vào vì thuộc về hàm.<br>• <code>print(gap_doi(4))</code> thẳng hàng với <code>def</code> vì nó nằm <b>ngoài hàm</b>: đây là lúc <b>gọi</b> hàm, với <code>x = 4</code>. In ra 8.<br><b>Thứ tự:</b> tạo hàm trước, gọi hàm sau. Gọi một hàm chưa được tạo thì Python báo <code>NameError</code>.<br><b>Lỗi hay gặp:</b> tưởng thụt dòng là quên; thật ra thụt = bên trong hàm, không thụt = bên ngoài. Nhầm <code>print</code> với <code>return</code>: <code>return</code> trả kết quả cho code đang gọi, còn <code>print</code> chỉ hiện lên màn hình.`,

    b5: `<b>Bốn mẩu viết liên quan đến list, đều dùng ví dụ hàng hộp <code>a</code>.</b><pre>a[0]          # lấy hộp số 0\na[1] = 9      # bỏ số 9 vào hộp số 1\nlen(a)        # đếm có bao nhiêu hộp\nfor x in a:   # lặp qua từng số x trong a</pre>• Dấu <b>ngoặc vuông</b> <code>[ ]</code> chứa <b>chỉ số</b>. Có <code>=</code> ở sau thì là <b>đặt vào</b> hộp đó, không có thì là <b>lấy ra</b>.<br>• <code>len(a)</code> cho <b>số hộp</b>, nên chỉ số cuối cùng là <code>len(a) - 1</code> (nhớ bài thứ tự, máy đếm từ 0).<br>• <code>for x in a:</code> cho <b>chính số trong hộp</b>; <code>for i in range(len(a)):</code> cho <b>số thứ tự của hộp</b> (chỉ số). Cần giá trị thì dùng <code>x</code>; cần biết hộp thứ mấy thì dùng <code>i</code> (rồi <code>a[i]</code> để lấy giá trị).<br><b>Lỗi hay gặp:</b> viết <code>a(0)</code> thay vì <code>a[0]</code>; dùng <code>a[len(a)]</code> (vượt hộp cuối, <code>IndexError</code>).<br><b>Mẹo:</b> trước khi viết, hỏi \"mình cần giá trị hay cần chỉ số?\"`,

    b6: `<b>Từ tờ giấy nhớ đến từng dòng code.</b> Bài \"tìm số lớn nhất\" có tờ giấy nhớ; trong code, tờ giấy đó là <b>một biến</b> (ở đây tên <code>best</code>).<pre>def find_max(nums):\n    best = nums[0]\n    for x in nums:\n        if x &gt; best:\n            best = x\n    return best</pre>Đối chiếu từng dòng với tờ giấy nhớ:<br>• <code>best = nums[0]</code>: ghi số ở hộp đầu lên giấy. Phải đứng <b>trước</b> vòng for, vì việc chuẩn bị làm một lần.<br>• <code>for x in nums:</code>: lần lượt xem từng hộp.<br>• <code>if x &gt; best:</code> rồi <code>best = x</code>: nếu số mới lớn hơn số trên giấy thì xóa, ghi số mới.<br>• <code>return best</code>: thẳng hàng với <code>for</code>, nên chỉ chạy <b>sau khi</b> vòng đã xong.<br><b>Độ thụt quyết định dòng chạy khi nào.</b> Nếu <code>best = x</code> thẳng hàng với <code>if</code> (quên thụt), nó chạy ở <b>mọi</b> vòng và ghi đè hết, kết quả là số cuối cùng chứ không phải số lớn nhất. Python <b>không báo lỗi</b> trường hợp này; chỉ test mới bắt được.<br><b>Mẹo:</b> khi viết dở, hỏi \"dòng tiếp theo làm gì với MỘT hộp?\" Việc đó nằm bên trong vòng lặp.`,

    d1: `<b>Dictionary: tra theo khóa, không tra theo vị trí.</b><pre>d = {\"a\": 3, \"b\": 5}\nprint(d[\"b\"])     # 5   (tra khóa \"b\")\nd[\"c\"] = 7         # thêm khóa mới \"c\" với giá trị 7\nprint(d[\"c\"])     # 7</pre>• Mỗi mục có hai phần: <b>khóa</b> (cái để tra, ví dụ <code>\"b\"</code>) và <b>giá trị</b> (cái tra ra, ví dụ <code>5</code>). Giống tra từ điển: tra chữ, ra nghĩa.<br>• <code>d[khóa]</code> <b>đọc</b> giá trị; <code>d[khóa] = giá trị</code> <b>ghi</b> (khóa đã có thì thay giá trị, chưa có thì thêm mới).<br>• Tra một khóa <b>chưa có</b> thì Python báo <code>KeyError</code>: không trả 0, không trả <code>None</code>. Đây là lỗi thật chứ không phải \"không có thì thôi\".<br><b>Khác list:</b> list tra bằng <b>số thứ tự</b> (<code>a[0]</code>); dict tra bằng <b>khóa</b> do bạn chọn.<br><b>Mẹo:</b> trước khi tra, hỏi \"khóa này chắc chắn đã có chưa?\" Chưa chắc thì phải kiểm tra trước (bài sau có cách tra an toàn).`,

    d2: `<b>Đếm tần suất: chữ là khóa, số lần là giá trị.</b><pre>s = \"abca\"\nd = {}\nfor ch in s:\n    d[ch] = d.get(ch, 0) + 1\nprint(d[\"a\"])    # 2</pre>• <code>d.get(ch, 0)</code> nghĩa là: tra khóa <code>ch</code>; <b>nếu chưa có thì trả 0</b> (không báo lỗi). Đây là chỗ khác <code>d[ch]</code>.<br>• Mỗi lần gặp một chữ: lấy số lần cũ (hoặc 0 nếu lần đầu), <b>cộng 1</b>, ghi lại.<br>• Chạy tay với <code>\"abca\"</code>: a → {a:1}; b → {a:1, b:1}; c → {a:1, b:1, c:1}; a → {a:2, b:1, c:1}. Nên <code>d[\"a\"]</code> là 2.<br><b>Lỗi hay gặp:</b> viết <code>d[ch] = d[ch] + 1</code> hoặc <code>d[ch] += 1</code> khi khóa chưa có: gặp chữ đầu tiên là <code>KeyError</code>. Quên <b>+ 1</b> (chỉ ghi lại số cũ) nên không đếm được gì.<br><b>Mẹo:</b> tự hỏi \"lần đầu gặp chữ này thì d.get(ch, 0) ra mấy?\" Ra 0, cộng 1 thành 1.`,

    tp: `<b>Hai con trỏ: một đứng đầu, một đứng cuối, cùng tiến vào giữa.</b><pre>a = [1, 2, 3, 4]\ni = 0\nj = len(a) - 1             # 3\na[i], a[j] = a[j], a[i]   # đổi chỗ hai hộp\ni = i + 1\nj = j - 1\nprint(a)                  # [4, 2, 3, 1]</pre>• \"Con trỏ\" ở đây chỉ là hai biến lưu <b>chỉ số</b>: <code>i</code> ở đầu (0), <code>j</code> ở cuối (<code>len(a) - 1</code>, không phải <code>len(a)</code>).<br>• <code>a[i], a[j] = a[j], a[i]</code> đổi chỗ hai hộp trong một dòng.<br>• Sau khi xử lý xong một cặp: <b><code>i</code> tăng 1, <code>j</code> giảm 1</b>, hai đầu tiến dần vào giữa.<br>• Làm tiếp với cặp mới: hộp 1 và hộp 2 đổi chỗ, ra <code>[4, 3, 2, 1]</code>. Khi <code>i</code> gặp hoặc vượt <code>j</code> thì dừng (đã đi hết).<br><b>Lỗi hay gặp:</b> đặt <code>j = len(a)</code> (vượt hộp cuối); cho <code>i</code> và <code>j</code> cùng tăng nên không bao giờ gặp nhau; đổi chỗ bằng hai dòng gán liền nhau làm mất một giá trị.<br><b>Mẹo:</b> vẽ hàng hộp, đặt hai ngón tay ở hai đầu, nhích từng bước.`,

    stk: `<b>Stack (chồng): vào sau, ra trước.</b> Giống chồng đĩa: đĩa đặt lên sau cùng nằm trên cùng, nên được lấy ra đầu tiên.<pre>push(3)    # chồng: 3\npush(5)    # chồng: 3, 5\npush(8)    # chồng: 3, 5, 8   (8 ở trên cùng)\npop()      # trả về 8, chồng: 3, 5\npop()      # trả về 5, chồng: 3</pre>• <code>push(x)</code>: đặt <code>x</code> lên <b>trên cùng</b>.<br>• <code>pop()</code>: lấy ra và trả về phần tử <b>trên cùng</b>. Chỉ làm việc ở một đầu.<br>• Quy tắc gọi tắt là <b>LIFO</b> (last in, first out): vào sau cùng, ra đầu tiên.<br><b>Lỗi hay gặp:</b> tưởng <code>pop()</code> lấy phần tử đầu tiên bỏ vào (đó là việc của queue); pop khi chồng đang rỗng (là lỗi).<br><b>Dùng ở đâu:</b> nút \"hoàn tác\" (undo), kiểm tra ngoặc đóng mở khớp nhau.<br><b>Mẹo:</b> hỏi \"cái nào mình đặt vào SAU CÙNG?\" Đó là cái ra trước.`,

    que: `<b>Queue (hàng đợi): vào trước, ra trước.</b> Giống xếp hàng mua vé: ai đến trước thì được phục vụ trước.<pre>enqueue(3)    # hàng: 3\nenqueue(5)    # hàng: 3, 5\nenqueue(8)    # hàng: 3, 5, 8   (3 đứng đầu hàng)\ndequeue()     # trả về 3, hàng: 5, 8\ndequeue()     # trả về 5, hàng: 8</pre>• <code>enqueue(x)</code>: cho <code>x</code> đứng vào <b>cuối</b> hàng.<br>• <code>dequeue()</code>: lấy ra và trả về phần tử <b>đầu</b> hàng.<br>• Quy tắc gọi tắt là <b>FIFO</b> (first in, first out).<br><b>So với stack:</b> cùng dữ liệu 3, 5, 8 thì stack lấy ra 8 trước, queue lấy ra 3 trước. Khác nhau ở <b>đầu nào được lấy</b>.<br><b>Lỗi hay gặp:</b> lẫn <code>dequeue</code> với <code>pop</code> của stack; quên rằng phần tử mới luôn vào cuối.<br><b>Dùng ở đâu:</b> hàng chờ công việc (job queue), giới hạn tốc độ gọi API.<br><b>Mẹo:</b> hỏi \"ai đến sớm nhất mà chưa được phục vụ?\" Đó là người ra trước.`,

    bs: `<b>Chia đôi: mỗi lần nhìn một hộp giữa, bỏ ngay một nửa.</b><br><b>Điều kiện bắt buộc: mảng phải đã sắp xếp.</b> Chia đôi dựa vào việc \"nhỏ hơn thì ở bên trái, lớn hơn thì ở bên phải\".<pre>a = [1, 3, 5, 7, 9, 11, 13]   # chỉ số 0 đến 6, tìm 11\nlo = 0, hi = 6\nmid = (0 + 6) // 2 = 3        # a[3] = 7;  11 &gt; 7  → bỏ nửa trái, lo = 4\nmid = (4 + 6) // 2 = 5        # a[5] = 11; trúng, trả về chỉ số 5</pre>• Hộp giữa của chỉ số <code>lo</code> đến <code>hi</code> là <code>(lo + hi) // 2</code> (<code>//</code> là chia lấy phần nguyên).<br>• So sánh số cần tìm với hộp giữa: nhỏ hơn thì chỉ có thể ở <b>nửa trái</b>, lớn hơn thì chỉ có thể ở <b>nửa phải</b>, bằng thì xong.<br>• Mỗi lần <b>số hộp còn lại giảm một nửa</b>. Đó là lý do nó nhanh: một triệu hộp chỉ cần khoảng 20 lần xem (vì 2<sup>20</sup> ≈ một triệu).<br><b>Lỗi hay gặp:</b> dùng trên mảng chưa sắp xếp (kết quả sai mà không báo lỗi); bỏ nhầm nửa; quên rằng hộp giữa đã xét rồi nên nửa mới phải loại nó ra.<br><b>Mẹo:</b> trước khi bỏ một nửa, hỏi \"số cần tìm chắc chắn KHÔNG nằm ở nửa này vì sao?\"`,

    bub: `<b>Nổi bọt: so sánh hai hộp cạnh nhau, trái lớn hơn phải thì đổi chỗ.</b><pre>a = [3, 1, 2]\n# so hộp 0 và hộp 1: 3 &gt; 1 → đổi   → [1, 3, 2]\n# so hộp 1 và hộp 2: 3 &gt; 2 → đổi   → [1, 2, 3]</pre>• Một <b>lượt</b> là đi từ đầu đến cuối mảng, mỗi bước so một cặp cạnh nhau.<br>• Số lớn nhất bị đổi chỗ liên tục nên được <b>đẩy dần về cuối</b> mảng. Sau một lượt, số lớn nhất đã ở đúng chỗ.<br>• Nhưng <b>một lượt chưa chắc sắp xếp xong</b> cả mảng. Ví dụ <code>[3, 2, 1]</code>: sau một lượt là <code>[2, 1, 3]</code>. Số 3 đã đúng chỗ, còn 2 và 1 vẫn lộn. Cần lặp thêm lượt nữa.<br><b>Lỗi hay gặp:</b> đổi chỗ khi hai số bằng nhau (không cần); so hộp cuối với hộp không tồn tại (<code>IndexError</code>); tưởng một lượt là xong.<br><b>Mẹo:</b> chạy tay một lượt trên giấy, ghi lại mảng sau mỗi lần so. Sau một lượt, nhìn xem số lớn nhất đã ở cuối chưa.`,

    t1: `<b>Cây: mỗi nút có tối đa hai nút con.</b><pre>      1          nút 1 là gốc\n     / \\\n    2   3        nút 2 và 3 là con của 1\n   /\n  4              nút 4 là con trái của 2</pre><pre>r = Cay(1)\nr.left = Cay(2)\nr.right = Cay(3)\nr.left.left = Cay(4)\nprint(r.left.v)   # 2</pre>• Mỗi nút có ba phần: giá trị <code>v</code>, con trái <code>left</code>, con phải <code>right</code>.<br>• Đọc <code>r.left.v</code> từ trái sang phải: từ <code>r</code>, đi sang con trái, rồi lấy giá trị. <code>r.right.v</code> là 3; <code>r.left.left.v</code> là 4. Cây này có 4 nút.<br>• Nút <b>không có con</b> thì chỗ đó là <code>None</code>. Nút như vậy gọi là <b>lá</b>. Nút 3 là lá nên <code>r.right.left</code> là <code>None</code>.<br><b>Khác linked list:</b> mỗi nút của linked list chỉ có <b>một</b> mũi tên đi ra (sang nút kế); mỗi nút của cây có <b>hai</b> (trái, phải), nên chia nhánh được.<br><b>Lỗi hay gặp:</b> đi tiếp từ <code>None</code>, ví dụ <code>r.right.left.v</code> là lỗi vì <code>None</code> không có <code>v</code>.<br><b>Mẹo:</b> vẽ cây ra giấy rồi đi theo từng chữ <code>left</code>/<code>right</code> bằng ngón tay.`,

    t2: `<b>Duyệt cây bằng đệ quy: bài nhỏ hơn giống hệt bài lớn.</b> Cây con trái và cây con phải cũng là cây.<pre>def dem(nut):\n    if nut is None:        # ca cơ sở: cây rỗng\n        return 0\n    return 1 + dem(nut.left) + dem(nut.right)</pre>• <b>Ca cơ sở</b>: <code>None</code> (cây rỗng) có <b>0</b> nút. Không có ca cơ sở thì đệ quy không bao giờ dừng.<br>• <b>Bước đệ quy</b>: số nút của cây = <b>1</b> (chính nó) + số nút cây con trái + số nút cây con phải.<br>• Trên cây 1, 2, 3, 4 của bài trước: nút 4 là lá: 1 + 0 + 0 = 1; nút 2: 1 + 1 + 0 = 2; nút 3: 1; gốc: 1 + 2 + 1 = <b>4</b>.<br>• <b>Thứ tự in</b> khi dòng <code>print(nut.v)</code> đứng <b>trước</b> hai lời gọi con: nút mình, rồi cả cây con trái, rồi cây con phải. Với cây trên in ra <b>1, 2, 4, 3</b>.<br><b>Lỗi hay gặp:</b> quên ca cơ sở nên gặp <code>None</code> rồi đòi <code>nut.left</code> (lỗi); nhầm thứ tự in khi dòng <code>print</code> đặt ở chỗ khác.<br><b>Mẹo:</b> chạy tay từ <b>lá</b> trở lên: lá trước, rồi cha của nó.`,

    g1: `<b>Đồ thị: các nút và các đường nối giữa chúng.</b> Cách ghi trong bài: mỗi nút ghi danh sách những nút nó nối tới.<pre>ban = {\"An\": [\"Binh\", \"Chi\"],\n       \"Binh\": [\"An\", \"Dung\"],\n       \"Chi\": [\"An\"],\n       \"Dung\": [\"Binh\"]}\nprint(ban[\"Chi\"])         # ['An']\nprint(len(ban[\"An\"]))     # 2</pre>• <code>ban[\"Chi\"]</code> là danh sách bạn của Chi. <code>len(ban[\"An\"])</code> là <b>số bạn</b> của An.<br>• Quan hệ bạn bè là <b>hai chiều</b> (đồ thị vô hướng): An là bạn của Binh thì Binh cũng là bạn của An, nên mỗi đường nối được <b>ghi hai lần</b>, một ở mỗi phía.<br>• Đếm đường nối: mỗi đường chỉ đếm <b>một lần</b>. Ở đây có An-Binh, An-Chi, Binh-Dung: <b>3 đường</b>. Cộng độ dài các danh sách (2 + 2 + 1 + 1 = 6) rồi chia 2 cũng ra 3.<br><b>Khác cây:</b> một nút có thể nối với <b>nhiều</b> nút, và đường nối có thể tạo thành <b>vòng</b> quay lại chỗ cũ; cây thì không có vòng.<br><b>Lỗi hay gặp:</b> đếm đường nối hai lần (ra 6); quên ghi cả hai phía khiến dữ liệu lệch.<br><b>Mẹo:</b> vẽ chấm cho nút và gạch cho đường nối, rồi đối chiếu với dict.`,

    dp2: `<b>Quy hoạch động: giải bài nhỏ trước, ghi vào bảng, bài lớn lấy từ bảng.</b><br>Leo cầu thang, mỗi lần bước 1 hoặc 2 bậc. Gọi <b>cách(k)</b> là số cách lên bậc k.<br>• cách(1) = 1; cách(2) = 2 (1+1 hoặc 2).<br>• Muốn đứng ở bậc k, bước <b>cuối cùng</b> đến từ bậc k-1 (bước 1) hoặc bậc k-2 (bước 2). Hai nhóm cách này không trùng nhau, nên <b>cách(k) = cách(k-1) + cách(k-2)</b>.<br>• Bảng: cách(3) = 2 + 1 = 3; cách(4) = 3 + 2 = 5; cách(5) = 5 + 3 = 8.<pre>dp = [1, 2]\nfor i in range(2, 5):\n    dp.append(dp[i - 1] + dp[i - 2])\nprint(dp)          # [1, 2, 3, 5, 8]\nprint(dp[4])       # 8</pre><b>Chỗ hay nhầm:</b> trong bài, <code>dp[0]</code> là <b>bậc 1</b>, <code>dp[1]</code> là bậc 2, nên <code>dp[4]</code> là <b>bậc 5</b> (chỉ số lệch một so với số bậc). Hỏi bậc k thì đọc <code>dp[k - 1]</code>.<br><b>Vì sao không tính lại từ đầu?</b> Mỗi ô chỉ cần hai ô liền trước đã có sẵn. Ghi lại kết quả để dùng, khỏi tính lại.<br><b>Mẹo:</b> trước khi code, tự viết hai câu: \"<code>dp[i]</code> nghĩa là gì\" và \"<code>dp[i]</code> tính từ những ô nào\".`,

    ap5: `<b>Thư mục là một cây; dung lượng thư mục = dung lượng chính nó + dung lượng các thư mục con.</b><pre>def total(n):\n    s = n[\"size\"]\n    for c in n[\"children\"]:\n        s += total(c)\n    return s</pre>• Mỗi nút là tệp hoặc thư mục, ghi <code>size</code> và danh sách <code>children</code>. Thư mục có thể có <code>size</code> 0 vì dung lượng nằm ở các tệp con.<br>• <b>Ca cơ sở</b>: nút <b>không có con</b>. Vòng <code>for</code> không chạy lần nào, hàm trả về <code>size</code> của chính nó. Không cần viết <code>if</code> riêng.<br>• <b>Bước đệ quy</b>: cộng <code>total(c)</code> của từng con vào <code>s</code>.<br>• Với thư mục chứa hai tệp 7 và 3 (bản thân nó 0): 0 + 7 + 3 = <b>10</b>. Cả cây: 5 + 10 = <b>15</b>.<br>• Đây chính là ý tưởng của lệnh <code>du</code> và trình quản lý tệp khi hiện dung lượng thư mục: duyệt cây, cộng từ lá lên.<br><b>Lỗi hay gặp:</b> quên cộng <code>size</code> của chính nút; nhầm <code>total(c)</code> với <code>c[\"size\"]</code> nên bỏ sót các tầng sâu hơn.<br><b>Mẹo:</b> các thứ ngoài đời hình cây (sơ đồ công ty, mục lục, bình luận trả lời bình luận) đều tính được bằng cùng khuôn: lấy giá trị của nút + kết quả của các con.`
  };
  for (const id in N) if (LES[id] && !LES[id].note) LES[id].note = N[id];
})();
