/* Kiểm tra hiểu thật cho 12 bài code w1 đến w12 (trước đây chỉ chấm bằng test ẩn: code chạy qua test chưa chắc là hiểu).
   Đề sinh ngẫu nhiên: dự đoán đầu ra của hàm với dữ liệu mới, đi ngược từ kết quả, đem cùng ý sang hàm khác,
   tự phán đúng/sai kèm lý do, và bẫy đọc đề (ca biên, ca lỗi). Mọi câu có code gắn _py để tools/verify-adv.js chạy Python thật.
   Nạp sau probe-last.js. Mọi tên nằm trong IIFE để không đụng tên toàn cục. */
(() => {
  const J = x => JSON.stringify(x).replace(/,/g, ", ").replace(/:/g, ": "), pyL = a => "[" + a.join(", ") + "]", pyBL = a => "[" + a.map(b => b ? "True" : "False").join(", ") + "]";
  const num = (src, body, a, w, lead) => { const c = src + body; return aPy(fT(`${fPre(c)}${lead || "In ra mấy?"}`, a, w), c, [String(a)]) };
  const opt = (src, body, right, wrongs, out, err, w, lead) => { const c = src + body; return aPy(fC(`${fPre(c)}${lead || "Chạy đoạn code trên thì điều gì xảy ra?"}`, [right, ...wrongs], w), c, out, err) };
  const arr = (n, lo, hi) => Array.from({ length: n }, () => fR(lo, hi));
  const sum = a => a.reduce((x, y) => x + y, 0);

  /* ===== w1: find_max ===== */
  const FM = `def find_max(nums):\n    best = nums[0]\n    for x in nums:\n        if x > best:\n            best = x\n    return best\n`;
  PRB.w1 = {
    same: () => { const a = arr(fR(4, 6), -4, 9), m = Math.max(...a); return num(FM, `print(find_max(${J(a)}))`, m, `Lớn nhất của ${J(a)} là ${m}: best bị ghi đè mỗi khi gặp số lớn hơn.`) },
    flip: () => { const a = pDistinct(5, 9), m = Math.max(...a); return num(FM, `nums = ${J(a)}\nprint(nums.index(find_max(nums)))`, a.indexOf(m), `find_max trả ${m}. Số ${m} nằm ở chỉ số ${a.indexOf(m)} (đếm từ 0).`, "In ra mấy? (chú ý: đây là CHỈ SỐ của kết quả, không phải kết quả)") },
    new: () => { const a = arr(fR(5, 7), 1, 9), t = fR(3, 6), c = a.filter(x => x > t).length; return num(`def count_more(nums, t):\n    c = 0\n    for x in nums:\n        if x > t:\n            c += 1\n    return c\n`, `print(count_more(${J(a)}, ${t}))`, c, `Cùng cách đi hết dãy với một biến nhớ, nhưng biến nhớ lần này là bộ đếm: có ${c} số lớn hơn ${t}.`) },
    verdict: KV("Hà nói: 'find_max đặt best = 0 ở đầu thì đúng với mọi danh sách'. Hà nói đúng hay sai?", "Hà nói: 'find_max nên đặt best = nums[0] để đúng cả với danh sách toàn số âm'. Hà nói đúng hay sai?", "Với danh sách toàn số âm thì 0 lớn hơn mọi số trong đó, kết quả sẽ sai", "Python bắt buộc best bằng 0", "Số âm không so sánh được với nhau", "Sai: [-3, -1, -7] sẽ trả 0, mà 0 không có trong danh sách."),
    read: () => { const v = fR(1, 9); return opt(LES.w1.ref, `print(find_max([]))`, "Báo lỗi ValueError vì danh sách rỗng", ["In ra 0", "In ra None"], [], "ValueError", "Hàm có dòng kiểm tra ở đầu: danh sách rỗng bị chặn trước khi tìm số lớn nhất. Đọc kỹ các dòng bảo vệ trước khi dự đoán.") }
  };
  bank("w1", "read", [() => opt(LES.w1.ref, `print(find_max("abc"))`, "Báo lỗi TypeError vì không phải list", ["In ra c", "In ra 0"], [], "TypeError", "Dòng đầu kiểm tra isinstance(nums, list): một chuỗi không phải list nên bị chặn bằng TypeError, dù chuỗi cũng 'duyệt được'.")]);

  /* ===== w2: linear_search ===== */
  const LS = `def linear_search(nums, target):\n    for i in range(len(nums)):\n        if nums[i] == target:\n            return i\n    return -1\n`;
  PRB.w2 = {
    same: () => { const a = arr(fR(5, 7), 1, 5), t = fR(1, 6), r = a.indexOf(t); return num(LS, `print(linear_search(${J(a)}, ${t}))`, r, r < 0 ? `Không có ${t} trong dãy nên trả -1.` : `${t} gặp đầu tiên ở chỉ số ${r}; hàm trả về ngay, không xét tiếp.`) },
    flip: () => { const a = pDistinct(6, 12), r = fR(1, 5), t = a[r]; return aPy(fT(`${fPre(LS)}nums = ${J(a)}. Muốn linear_search(nums, ?) trả về ${r}, dấu ? phải là số mấy?`, t, `Hàm trả CHỈ SỐ ${r}, nên số cần tìm là nums[${r}] = ${t}.`), LS + `print(linear_search(${J(a)}, ${t}))`, [String(r)]) },
    new: () => { const a = arr(fR(5, 7), 1, 9).map((x, i) => i == 3 ? -x : x), r = a.findIndex(x => x < 0); return num(`def first_negative(nums):\n    for i in range(len(nums)):\n        if nums[i] < 0:\n            return i\n    return -1\n`, `print(first_negative(${J(a)}))`, r, `Cùng khung tìm tuyến tính, chỉ đổi điều kiện thành 'nhỏ hơn 0': số âm đầu tiên ở chỉ số ${r}.`) },
    verdict: KV("Hà nói: 'linear_search đặt return -1 BÊN TRONG vòng for cho gọn thì vẫn đúng'. Hà nói đúng hay sai?", "Hà nói: 'return -1 phải nằm ngoài vòng for, vì chỉ kết luận không có sau khi đã mở hết hộp'. Hà nói đúng hay sai?", "Chỉ kết luận 'không có' sau khi đã xét hết mọi hộp", "Python không cho return trong vòng for", "return -1 chạy nhanh hơn khi nằm trong vòng for", "Sai: đặt trong vòng for thì hàm kết luận 'không có' ngay sau hộp đầu tiên không khớp."),
    read: () => { const a = pDistinct(4, 9), k = fR(1, 3); return opt(LS, `print(linear_search(${J(a)}, ${a[k]}))`, `${k}: đây là chỉ số của ${a[k]}`, [`${a[k]}: chính số cần tìm`, "-1"], [String(k)], "", `Hàm trả về VỊ TRÍ (chỉ số) của số cần tìm, không phải chính số đó. Số ${a[k]} đứng ở chỉ số ${k}.`) }
  };
  bank("w2", "read", [() => { const v = fR(1, 5); return opt(LES.w2.ref, `print(linear_search([${v}, 9, ${v}, 7], ${v}))`, "0: gặp lần đầu thì trả về luôn", ["2: lần xuất hiện cuối", "[0, 2]: cả hai vị trí"], ["0"], "", `${v} xuất hiện ở chỉ số 0 và 2, nhưng return dừng hàm ngay lần gặp đầu tiên nên trả 0.`) }]);

  /* ===== w3: second_max ===== */
  const SM = `def second_max(nums):\n    uniq = set(nums)\n    uniq.remove(max(uniq))\n    return max(uniq)\n`;
  PRB.w3 = {
    same: () => { const hi = fR(6, 9), lo = fR(1, 4), mid = fR(lo + 1, hi - 1), a = pShuf([hi, hi, mid, lo, mid]), r = mid; return num(SM, `print(second_max(${J(a)}))`, r, `set bỏ trùng còn {${lo}, ${mid}, ${hi}}, bỏ ${hi} còn lại lớn nhất là ${r}. Số ${hi} xuất hiện hai lần vẫn chỉ là MỘT giá trị.`) },
    flip: () => { const hi = fR(7, 9), lo = fR(1, 3), mid = fR(lo + 1, hi - 1); return aPy(fT(`${fPre(SM)}Biết second_max([${hi}, ${lo}, ?]) trả về ${mid}. Dấu ? là số mấy? (? khác ${hi} và ${lo})`, mid, `Tập giá trị là {${hi}, ${lo}, ?}. Để lớn thứ hai là ${mid}, mà ${lo} < ${mid} < ${hi} thì ? phải là ${mid}.`), SM + `print(second_max([${hi}, ${lo}, ${mid}]))`, [String(mid)]) },
    new: () => { const a = arr(fR(6, 8), 1, 5), r = new Set(a).size; return num(`def count_distinct(nums):\n    return len(set(nums))\n`, `print(count_distinct(${J(a)}))`, r, `set giữ mỗi giá trị đúng một lần: ${J(a)} có ${r} giá trị khác nhau.`, "In ra mấy? (cùng công cụ set, bài toán khác)") },
    verdict: KV("Hà nói: 'second_max([7, 7, 3]) trả 7, vì số 7 xuất hiện hai lần nên có hai số lớn nhất'. Hà nói đúng hay sai?", "Hà nói: 'second_max([7, 7, 3]) trả 3, vì hai số 7 chỉ là một giá trị lớn nhất'. Hà nói đúng hay sai?", "set bỏ trùng nên 7 chỉ còn một lần; lớn thứ hai là 3", "Python luôn giữ số trùng trong set", "Lớn thứ hai luôn bằng lớn nhất", "Sai: đề đã chốt 'lớn thứ hai' là theo GIÁ TRỊ khác nhau, không phải theo vị trí."),
    read: () => { const v = fR(1, 9); return opt(LES.w3.ref, `print(second_max([${v}, ${v}, ${v}]))`, "Báo lỗi ValueError vì chỉ có 1 giá trị khác nhau", [`In ra ${v}`, "In ra 0"], [], "ValueError", "Sau khi bỏ trùng chỉ còn một giá trị, không có 'lớn thứ hai', nên hàm chủ động báo ValueError.") }
  };
  bank("w3", "read", [() => opt(LES.w3.ref, `print(second_max([5]))`, "Báo lỗi ValueError vì cần ít nhất 2 giá trị khác nhau", ["In ra 5", "In ra None"], [], "ValueError", "Một phần tử thì không có lớn thứ hai: ca biên này đề đã chốt là lỗi.")]);

  /* ===== w4 (và w5, w6 cùng ý): two_sum bằng dict ===== */
  const TS = `def two_sum(nums, target):\n    seen = {}\n    for i, x in enumerate(nums):\n        y = target - x\n        if y in seen:\n            return [seen[y], i]\n        seen[x] = i\n    raise ValueError("khong co cap")\n`;
  const tsJs = (n, t) => { const s = new Map(); for (let i = 0; i < n.length; i++) { const y = t - n[i]; if (s.has(y)) return [s.get(y), i]; s.set(n[i], i) } return null };
  PRB.w4 = {
    same: () => { let a, t, r; do { a = pDistinct(5, 14); const i = fR(0, 3), j = fR(i + 1, 4); t = a[i] + a[j]; r = tsJs(a, t) } while (!r); return num(TS, `i, j = two_sum(${J(a)}, ${t})\nprint(j)`, r[1], `Hàm dừng ở lần đầu một số có 'bạn cùng cặp' đã được ghi trong seen: trả [${r[0]}, ${r[1]}], nên j = ${r[1]}.`, "In ra mấy? (chỉ số j của cặp tìm thấy)") },
    flip: () => { let a = null, t; for (let k = 0; k < 300 && !a; k++) { const c = pDistinct(4, 12); t = c[1] + c[3]; const r = tsJs(c, t); if (r && r[0] == 1 && r[1] == 3) a = c } if (!a) { a = [1, 6, 2, 5]; t = 11 } const x = a[3]; return aPy(fT(`${fPre(TS)}nums = [${a[0]}, ${a[1]}, ${a[2]}, ?], target = ${t}. Biết two_sum(nums, ${t}) trả về [1, 3]. Dấu ? là số mấy?`, x, `Cặp là nums[1] + nums[3] = ${t}, nên nums[3] = ${t} - ${a[1]} = ${x}.`), TS + `print(two_sum(${J(a)}, ${t}))`, ["[1, 3]"]) },
    new: () => { const a = arr(fR(6, 8), 1, 6); let r = -1; const s = new Set(); for (const x of a) { if (s.has(x)) { r = x; break } s.add(x) } return num(`def first_repeat(nums):\n    seen = set()\n    for x in nums:\n        if x in seen:\n            return x\n        seen.add(x)\n    return -1\n`, `print(first_repeat(${J(a)}))`, r, `Cùng ý 'ghi lại những gì đã thấy rồi tra': số đầu tiên xuất hiện lần thứ hai là ${r}.`) },
    verdict: KV("Hà nói: 'two_sum dùng hai vòng for lồng nhau thì nhanh hơn dùng dict, vì dict tốn thêm bộ nhớ'. Hà nói đúng hay sai?", "Hà nói: 'two_sum dùng dict để mỗi số chỉ cần xét một lần, đổi lại tốn thêm bộ nhớ'. Hà nói đúng hay sai?", "Dict cho biết 'y đã thấy chưa' trong một bước, nên chỉ quét dãy một lần; đổi lại tốn bộ nhớ", "Hai vòng lồng nhau luôn nhanh hơn", "Dict chậm hơn danh sách khi tra cứu", "Sai: hai vòng lồng nhau phải so sánh rất nhiều cặp; dict đổi bộ nhớ lấy tốc độ."),
    read: () => { const v = fR(2, 9); return opt(TS, `print(two_sum([${v}, ${v}], ${2 * v}))`, "[0, 1]: số thứ hai tìm thấy bản sao đã lưu", ["Báo ValueError vì hai số giống nhau", "[0, 0]"], ["[0, 1]"], "", `Ở i = 0, seen còn rỗng nên chưa có cặp; sau đó lưu ${v} -> 0. Ở i = 1, y = ${v} đã có trong seen, trả [0, 1]. Kiểm tra TRƯỚC khi lưu nên một số không ghép với chính nó.`) }
  };
  bank("w4", "new", [() => { const a = arr(fR(5, 7), 1, 6), t = fR(5, 8), s = new Set(a), c = a.filter(x => s.has(t - x)).length; return num(`def count_with_partner(nums, t):\n    s = set(nums)\n    c = 0\n    for x in nums:\n        if t - x in s:\n            c += 1\n    return c\n`, `print(count_with_partner(${J(a)}, ${t}))`, c, `Với mỗi số x, hỏi 'bạn cùng cặp ${t} - x có trong tập không': có ${c} số như vậy (một số có thể tự ghép với chính nó).`) }]);
  bank("w4", "read", [() => { const a = [fR(1, 3), fR(4, 6), fR(7, 9)]; return opt(TS, `print(two_sum(${J(a)}, 100))`, "Báo lỗi ValueError vì không có cặp nào", ["[0, 1]", "In ra -1"], [], "ValueError", "Duyệt hết mà không cặp nào có tổng 100 thì chạy tới dòng raise ValueError. Hàm này không trả -1.") }]);
  PRB.w5 = Object.assign({}, PRB.w4); PRB.w6 = Object.assign({}, PRB.w4);

  /* ===== w7: has_duplicate bằng set ===== */
  const HD = `def has_duplicate(nums):\n    seen = set()\n    for x in nums:\n        if x in seen:\n            return True\n        seen.add(x)\n    return False\n`;
  const boolQ = (q, v, w, src, body) => aPy(fC(q, [v ? "True" : "False", v ? "False" : "True", "Báo lỗi"], w), src + body, [v ? "True" : "False"]);
  PRB.w7 = {
    same: () => { const a = arr(fR(4, 6), 1, 8), v = new Set(a).size < a.length; return boolQ(`${fPre(HD + `print(has_duplicate(${J(a)}))`)}In ra gì?`, v, v ? "Có số xuất hiện hai lần nên trả True." : "Mọi số khác nhau nên chạy hết vòng và trả False.", HD, `print(has_duplicate(${J(a)}))`) },
    flip: () => { const n = fR(5, 12); return fT(`has_duplicate trả về False cho một danh sách có ${n} phần tử. Danh sách đó có bao nhiêu giá trị khác nhau?`, n, `Không có số trùng nghĩa là ${n} phần tử đều khác nhau: ${n} giá trị khác nhau.`) },
    new: () => { const ids = ["u1", "u2", "u3", "u4"], a = Array.from({ length: fR(6, 8) }, () => aPick(ids)); let d = 0; const s = new Set(); for (const x of a) { if (s.has(x)) d++; else s.add(x) } return num(`def duplicate_logins(users):\n    seen = set()\n    dups = 0\n    for u in users:\n        if u in seen:\n            dups += 1\n        else:\n            seen.add(u)\n    return dups\n`, `print(duplicate_logins(${J(a)}))`, d, `Mỗi lần gặp một tài khoản đã có trong seen thì cộng 1: có ${d} lần đăng nhập lặp. Cùng ý, đổi từ số sang tài khoản và từ True/False sang đếm.`) },
    verdict: KV("Hà nói: 'kiểm tra x in seen với seen là LIST thì nhanh y như với seen là SET, cả khi danh sách rất dài'. Hà nói đúng hay sai?", "Hà nói: 'dùng set cho seen vì kiểm tra x in seen không phải quét từng phần tử'. Hà nói đúng hay sai?", "set tra cứu trực tiếp, list phải quét từng phần tử", "list và set tra cứu giống hệt nhau", "set luôn tốn ít bộ nhớ hơn list", "Sai: với list, mỗi lần x in seen có thể phải quét hết danh sách."),
    read: () => opt(HD, `print(has_duplicate([]))`, "False: rỗng thì không có số nào trùng", ["Báo lỗi vì danh sách rỗng", "True"], ["False"], "", "Danh sách rỗng là ca hợp lệ: vòng lặp không chạy lần nào, chạy xuống return False. Không phải mọi ca rỗng đều là lỗi, phải đọc hàm cụ thể.")
  };
  bank("w7", "read", [() => opt(LES.w7.ref, `print(has_duplicate("abca"))`, "Báo lỗi TypeError vì không phải list", ["True vì chữ a lặp lại", "False"], [], "TypeError", "Dòng bảo vệ isinstance(nums, list) chặn chuỗi trước khi duyệt, dù chuỗi có chữ a lặp.")]);

  /* ===== w8: factorial (đệ quy) ===== */
  const FA = `def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)\n`, fact = n => n <= 1 ? 1 : n * fact(n - 1);
  PRB.w8 = {
    same: () => { const n = fR(3, 6); return num(FA, `print(factorial(${n}))`, fact(n), `factorial(${n}) = ${Array.from({ length: n }, (_, i) => n - i).join(" x ")} = ${fact(n)}.`) },
    flip: () => { const n = fR(3, 6); return aPy(fT(`${fPre(FA)}Biết factorial(?) trả về ${fact(n)}. Dấu ? là số mấy?`, n, `1, 2, 6, 24, 120, 720: ${fact(n)} là factorial(${n}).`), FA + `print(factorial(${n}))`, [String(fact(n))]) },
    new: () => { const n = fR(3, 7), k = fR(2, 4); return num(`def total_steps(n):\n    if n == 0:\n        return 0\n    return ${k} + total_steps(n - 1)\n`, `print(total_steps(${n}))`, k * n, `Mỗi tầng cộng ${k}, có ${n} tầng, ca cơ sở là 0: ${k} x ${n} = ${k * n}. Cùng khung đệ quy, chỉ đổi phép kết hợp.`) },
    verdict: KV("Hà nói: 'factorial(0) phải bằng 0 vì không có số nào để nhân'. Hà nói đúng hay sai?", "Hà nói: 'factorial(0) = 1 vì đó là ca cơ sở, và nhân với 1 không làm đổi kết quả'. Hà nói đúng hay sai?", "Ca cơ sở trả 1 để phép nhân dây chuyền không bị về 0", "Python tự quy định factorial(0) là 0", "Ca cơ sở có thể bỏ đi", "Sai: nếu ca cơ sở trả 0 thì mọi giai thừa đều thành 0."),
    read: () => { const n = fR(1, 5); return opt(LES.w8.ref, `print(factorial(-${n}))`, "Báo lỗi ValueError vì n âm", ["In ra 1", `In ra -${n}`], [], "ValueError", "Dòng bảo vệ n < 0 chặn trước khi tới ca cơ sở. Nếu không có dòng này, n âm sẽ trả 1 một cách sai lặng lẽ.") }
  };
  bank("w8", "read", [() => opt(LES.w8.ref, `print(factorial(3.0))`, "Báo lỗi TypeError vì 3.0 không phải int", ["In ra 6", "In ra 6.0"], [], "TypeError", "3.0 trông như số 3 nhưng là float; hàm bắt buộc int nên chặn bằng TypeError.")]);

  /* ===== w9: final_balance ===== */
  const FB = `def final_balance(txs):\n    total = 0\n    for t in txs:\n        if t["type"] == "deposit":\n            total += t["amount"]\n        else:\n            total -= t["amount"]\n        if total < 0:\n            raise ValueError("so du khong du")\n    return total\n`;
  const txGen = n => { let bal = 0; const L = []; for (let i = 1; i <= n; i++) { if (bal == 0 || Math.random() < .55) { const a = 10 * fR(1, 5); L.push({ id: i, type: "deposit", amount: a }); bal += a } else { const a = 10 * fR(1, bal / 10); L.push({ id: i, type: "withdraw", amount: a }); bal -= a } } return { L, bal } };
  PRB.w9 = {
    same: () => { const { L, bal } = txGen(fR(3, 5)); return num(FB, `print(final_balance(${J(L)}))`, bal, `Cộng deposit, trừ withdraw lần lượt: số dư cuối là ${bal}, và không lúc nào âm.`) },
    flip: () => { const b = 10 * fR(3, 9), w = 10 * fR(1, 2); return fT(`final_balance của một dãy giao dịch trả về ${b}. Giao dịch cuối cùng là withdraw ${w}. Số dư ngay TRƯỚC giao dịch cuối là bao nhiêu?`, b + w, `Rút ${w} xong còn ${b}, nên trước đó là ${b} + ${w} = ${b + w}.`) },
    new: () => { const k = ["win", "lose"], ev = Array.from({ length: fR(4, 6) }, () => ({ kind: aPick(k), pts: fR(1, 5) })), s = ev.reduce((t, e) => t + (e.kind == "win" ? e.pts : -e.pts), 0); return num(`def score(events):\n    s = 0\n    for e in events:\n        if e["kind"] == "win":\n            s += e["pts"]\n        else:\n            s -= e["pts"]\n    return s\n`, `print(score(${J(ev)}))`, s, `Cùng cách xử lý danh sách dict: win cộng, lose trừ. Tổng là ${s}.`) },
    verdict: KV("Hà nói: 'số dư xuống âm giữa chừng nhưng cuối cùng dương thì vẫn chấp nhận được, chỉ cần kiểm tra số dư cuối'. Hà nói đúng hay sai?", "Hà nói: 'phải kiểm tra số dư sau MỖI giao dịch, không chỉ ở cuối'. Hà nói đúng hay sai?", "Số dư âm giữa chừng nghĩa là có lúc rút quá số tiền đang có", "Chỉ số dư cuối mới quan trọng", "Kiểm tra mỗi giao dịch làm chương trình sai", "Sai: rút quá số tiền đang có là lỗi dù về sau nạp bù."),
    read: () => { const D = 10 * fR(2, 4), W = D + 10 * fR(1, 3), E = W + 10 * fR(1, 3), L = [{ id: 1, type: "deposit", amount: D }, { id: 2, type: "withdraw", amount: W }, { id: 3, type: "deposit", amount: E }]; return opt(FB, `print(final_balance(${J(L)}))`, "Báo ValueError: số dư âm ngay sau giao dịch thứ hai", [`In ra ${D - W + E}`, `In ra ${D - W}`], [], "ValueError", `Số dư cuối nếu cộng hết là ${D - W + E} (dương), nhưng sau giao dịch 2 số dư là ${D - W} (âm) nên hàm báo lỗi ngay. Phải kiểm tra từng bước, không chỉ kết quả cuối.`) }
  };
  bank("w9", "read", [() => opt(FB, `print(final_balance([]))`, "0: không có giao dịch thì số dư là 0", ["Báo ValueError vì danh sách rỗng", "In ra None"], ["0"], "", "Danh sách rỗng là ca hợp lệ: total vẫn là 0 và được trả về.")]);
  bank("w9", "new", [() => { const k = ["deposit", "withdraw"], L = Array.from({ length: fR(4, 6) }, (_, i) => ({ id: i + 1, type: aPick(k), amount: 10 * fR(1, 5) })), t = aPick(k); return num(`def count_type(txs, kind):\n    c = 0\n    for t in txs:\n        if t["type"] == kind:\n            c += 1\n    return c\n`, `print(count_type(${J(L)}, "${t}"))`, L.filter(x => x.type == t).length, `Đếm giao dịch có type là ${t}: ${L.filter(x => x.type == t).length}. Cùng cách đọc từng dict rồi lọc theo một trường.`) }]);

  /* ===== w10: install_order (DFS, phát hiện vòng) ===== */
  const IO = `def install_order(deps):\n    order, state = [], {}\n    def visit(x):\n        if state.get(x) == "done":\n            return\n        if state.get(x) == "doing":\n            raise ValueError("vong")\n        state[x] = "doing"\n        for d in deps[x]:\n            visit(d)\n        state[x] = "done"\n        order.append(x)\n    for name in sorted(deps):\n        visit(name)\n    return order\n`;
  const iOrd = deps => { const o = [], st = {}; const v = x => { if (st[x] === "done") return; st[x] = "doing"; deps[x].forEach(v); st[x] = "done"; o.push(x) }; Object.keys(deps).sort().forEach(v); return o };
  const dGen = n => { const names = pShuf(["app", "db", "web", "log", "net", "ui", "api", "cache"]).slice(0, n), d = {}; names.forEach((x, k) => d[x] = pShuf(names.slice(0, k)).slice(0, fR(0, Math.min(k, 2)))); return d };
  PRB.w10 = {
    same: () => { const d = dGen(4), o = iOrd(d), x = aPick(Object.keys(d)); return num(IO, `print(install_order(${J(d)}).index("${x}"))`, o.indexOf(x), `Kết quả là ${J(o)}: mỗi gói đứng SAU mọi gói nó cần. «${x}» ở vị trí ${o.indexOf(x)} (đếm từ 0).`, `In ra mấy? (vị trí của "${x}" trong kết quả, đếm từ 0)`) },
    flip: () => fC("Với một deps hợp lệ bất kỳ, gói đứng ĐẦU TIÊN trong kết quả của install_order phải là gói như thế nào?", ["Gói không phụ thuộc gói nào", "Gói có nhiều phụ thuộc nhất", "Gói có tên đứng đầu bảng chữ cái"], "Một gói chỉ được ghi vào order sau khi mọi phụ thuộc của nó đã được ghi. Gói đầu tiên chưa có gói nào đứng trước nên nó không được phụ thuộc gì."),
    new: () => { const d = dGen(5), x = aPick(Object.keys(d)), dp = n => d[n].length ? 1 + Math.max(...d[n].map(dp)) : 0; return num(`def depth(deps, x):\n    if not deps[x]:\n        return 0\n    return 1 + max(depth(deps, d) for d in deps[x])\n`, `print(depth(${J(d)}, "${x}"))`, dp(x), `Cùng ý đệ quy trên phụ thuộc: độ sâu của «${x}» là chuỗi phụ thuộc dài nhất dưới nó, bằng ${dp(x)}.`, `In ra mấy? (độ sâu của "${x}")`) },
    verdict: KV("Hà nói: 'a cần b và b cần a thì vẫn cài được, cứ cài cái nào trước cũng được'. Hà nói đúng hay sai?", "Hà nói: 'a cần b và b cần a là vòng phụ thuộc, không có thứ tự cài hợp lệ nào'. Hà nói đúng hay sai?", "Mỗi gói phải đứng sau gói nó cần: a sau b và b sau a là mâu thuẫn", "Python tự chọn thứ tự cho vòng phụ thuộc", "Vòng phụ thuộc chỉ gây cảnh báo", "Sai: không thể có a sau b mà đồng thời b sau a."),
    read: () => { const [x, y] = pShuf(["app", "db", "web", "log"]).slice(0, 2); return opt(IO, `print(install_order({"${x}": ["${y}"], "${y}": ["${x}"]}))`, "Báo lỗi ValueError vì có vòng phụ thuộc", [`[${"'" + x + "'"}, ${"'" + y + "'"}]`, `[${"'" + y + "'"}, ${"'" + x + "'"}]`], [], "ValueError", `Đi vào «${x}» rồi «${y}», rồi lại gặp «${x}» khi nó vẫn đang 'doing': đó là vòng, hàm báo ValueError.`) }
  };
  bank("w10", "read", [() => opt(IO, `print(install_order({}))`, "[]: không có gói nào thì không cần cài gì", ["Báo ValueError vì deps rỗng", "None"], ["[]"], "", "deps rỗng là ca hợp lệ: vòng for không chạy, trả danh sách rỗng.")]);

  /* ===== w11: bracket_error (stack lưu chỉ số) ===== */
  const BE = `def bracket_error(s):\n    pairs = {")": "(", "]": "[", "}": "{"}\n    stack = []\n    for i in range(len(s)):\n        c = s[i]\n        if c in "([{":\n            stack.append(i)\n        elif c in pairs:\n            if len(stack) == 0 or s[stack[-1]] != pairs[c]:\n                return i\n            stack.pop()\n    if len(stack) > 0:\n        return stack[-1]\n    return -1\n`;
  const beJs = s => { const p = { ")": "(", "]": "[", "}": "{" }, st = []; for (let i = 0; i < s.length; i++) { const c = s[i]; if ("([{".includes(c)) st.push(i); else if (p[c]) { if (!st.length || s[st[st.length - 1]] != p[c]) return i; st.pop() } } return st.length ? st[st.length - 1] : -1 };
  const bStr = () => { const o = ["(", "[", "{"], c = { "(": ")", "[": "]", "{": "}" }; let s = ""; for (let k = 0; k < fR(2, 3); k++) { const b = aPick(o); s += b + "x" + c[b] } const r = Math.random(); if (r < .35) return s + aPick([")", "]", "}"]); if (r < .7) return aPick(o) + s; if (r < .85) { const b = aPick(o); return b + aPick(o.filter(z => z != b).map(z => c[z])) + s } return s };
  PRB.w11 = {
    same: () => { const s = bStr(), r = beJs(s); return num(BE, `print(bracket_error('${s}'))`, r, r < 0 ? "Mọi ngoặc đều khớp và đóng đủ nên trả -1." : `Lỗi đầu tiên ở chỉ số ${r}: ký tự '${s[r]}'.`, "In ra mấy? (chỉ số lỗi, hoặc -1 nếu không có lỗi)") },
    flip: () => { let s, r; do { s = bStr(); r = beJs(s) } while (r < 0); return aPy(fC(`${fPre(BE + `s = '${s}'\nprint(s[bracket_error(s)])`)}Đoạn code in ra ký tự nào?`, [s[r], ...pShuf([...new Set([...s, "(", ")", "[", "]", "{", "}"])].filter(c => c != s[r])).slice(0, 2)], `bracket_error trả chỉ số ${r}, và s[${r}] = '${s[r]}'.`), BE + `s = '${s}'\nprint(s[bracket_error(s)])`, [s[r]]) },
    new: () => { const s = Array.from({ length: fR(6, 9) }, () => aPick(["(", "(", ")", "x"])).join(""); let d = 0, m = 0; for (const c of s) { if (c == "(") m = Math.max(m, ++d); else if (c == ")") d-- } return num(`def max_depth(s):\n    d = 0\n    best = 0\n    for c in s:\n        if c == "(":\n            d += 1\n            best = max(best, d)\n        elif c == ")":\n            d -= 1\n    return best\n`, `print(max_depth('${s}'))`, m, `Cùng ý theo dõi trạng thái khi duyệt chuỗi, nhưng chỉ cần một bộ đếm thay vì stack: độ sâu lớn nhất là ${m}.`) },
    verdict: KV("Hà nói: 'chỉ cần đếm số ngoặc mở bằng số ngoặc đóng là biết chuỗi ngoặc đúng'. Hà nói đúng hay sai?", "Hà nói: 'chuỗi \")(\" có số ngoặc mở bằng số ngoặc đóng nhưng vẫn sai, vì đóng xuất hiện trước mở'. Hà nói đúng hay sai?", "Thứ tự và loại ngoặc cũng quan trọng, đếm số lượng thôi chưa đủ", "Đếm bằng nhau luôn là đúng", "Thứ tự ngoặc không quan trọng", "Sai: \")(\" và \"([)]\" đều có số lượng khớp nhưng vẫn sai."),
    read: () => { const a = fR(0, 1) ? "(" : "[", b = a == "(" ? ")" : "]"; const s = `${a}${a == "(" ? "[" : "("}${b}`, r = beJs(s); return opt(BE, `print(bracket_error('${s}'))`, `${r}: chỉ số của ngoặc đóng sai chỗ`, [r == 0 ? "1" : "0", "-1"], [String(r)], "", `Ngoặc '${s[r]}' ở chỉ số ${r} không khớp với ngoặc mở đang chờ trên đỉnh stack, nên hàm trả ngay chỉ số đó.`) }
  };
  bank("w11", "read", [() => { const n = fR(1, 3), s = "(".repeat(n) + "x" + ")".repeat(n - 1); return opt(BE, `print(bracket_error('${s}'))`, "0: ngoặc mở đầu tiên chưa được đóng", ["-1: vì không có ngoặc nào sai thứ tự", `${s.length - 1}`], ["0"], "", "Không có ngoặc đóng nào sai chỗ, nhưng cuối chuỗi stack còn một ngoặc mở chưa đóng: hàm trả chỉ số của nó. Thiếu ngoặc đóng cũng là lỗi.") }]);
  bank("w11", "read", [() => opt(BE, `print(bracket_error(''))`, "-1: chuỗi rỗng không có lỗi", ["Báo lỗi vì chuỗi rỗng", "0"], ["-1"], "", "Chuỗi rỗng là ca hợp lệ: không có ngoặc nào, nên không có lỗi.")]);

  /* ===== w12: allowed_requests (hàng đợi thời điểm) ===== */
  const AL = `def allowed_requests(times, limit, window):\n    q = []\n    result = []\n    for t in times:\n        while q and q[0] <= t - window:\n            q.pop(0)\n        if len(q) < limit:\n            q.append(t)\n            result.append(True)\n        else:\n            result.append(False)\n    return result\n`;
  const alJs = (ts, L, W) => { const q = [], r = []; for (const t of ts) { while (q.length && q[0] <= t - W) q.shift(); if (q.length < L) { q.push(t); r.push(true) } else r.push(false) } return r };
  PRB.w12 = {
    same: () => { let t = 0; const ts = Array.from({ length: 6 }, () => (t += fR(0, 4))), L = fR(1, 3), W = fR(3, 8), r = alJs(ts, L, W); return num(AL, `print(sum(allowed_requests(${J(ts)}, ${L}, ${W})))`, r.filter(Boolean).length, `Kết quả là ${pyBL(r)}: có ${r.filter(Boolean).length} yêu cầu được chấp nhận. Yêu cầu bị từ chối không được ghi vào hàng đợi.`, "In ra mấy? (số yêu cầu được chấp nhận; True tính là 1)") },
    flip: () => { const W = fR(4, 9), a = fR(0, 3), b = a + fR(0, W - 1), t = a + W; return aPy(fT(`${fPre(AL)}limit = 2, window = ${W}. Hai yêu cầu lúc ${a} và ${b} đều được chấp nhận. Một yêu cầu thứ ba đến lúc t. Thời điểm t SỚM NHẤT (t ≥ ${b}) mà nó được chấp nhận là bao nhiêu?`, t, `Yêu cầu lúc ${a} chỉ rời cửa sổ khi ${a} <= t - ${W}, tức t >= ${a + W}. Trước đó hàng đợi còn đủ 2 nên bị từ chối.`), AL + `print(allowed_requests([${a}, ${b}, ${t - 1}, ${t}], 2, ${W}))`, ["[True, True, False, True]"]) },
    new: () => { const ts = []; let t = 0; for (let k = 0; k < fR(6, 8); k++) ts.push(t += fR(0, 3)); const W = fR(3, 6); let best = 0, l = 0; for (let r = 0; r < ts.length; r++) { while (ts[r] - ts[l] >= W) l++; best = Math.max(best, r - l + 1) } return num(`def max_in_window(times, window):\n    best = 0\n    left = 0\n    for right in range(len(times)):\n        while times[right] - times[left] >= window:\n            left += 1\n        best = max(best, right - left + 1)\n    return best\n`, `print(max_in_window(${J(ts)}, ${W}))`, best, `Cùng ý 'cửa sổ trượt': bỏ mốc quá cũ khỏi đầu rồi đếm. Nhiều nhất ${best} mốc nằm trong một cửa sổ ${W}.`) },
    verdict: KV("Hà nói: 'trong allowed_requests, yêu cầu bị TỪ CHỐI vẫn được thêm vào hàng đợi q'. Hà nói đúng hay sai về code đã học?", "Hà nói: 'trong allowed_requests, chỉ yêu cầu được CHẤP NHẬN mới được thêm vào q; đây là một giả định nghiệp vụ phải ghi rõ'. Hà nói đúng hay sai?", "Dòng q.append(t) nằm trong nhánh chấp nhận, nhánh từ chối chỉ ghi False", "Mọi yêu cầu đều vào q", "Hàm không dùng q để đếm", "Sai: nhánh else chỉ thêm False vào result, không đụng tới q."),
    read: () => { const W = fR(3, 9); return opt(AL, `print(allowed_requests([0, ${W}], 1, ${W}))`, "[True, True]: ở thời điểm " + W + ", yêu cầu lúc 0 đã ra khỏi cửa sổ", ["[True, False]", "[False, False]"], ["[True, True]"], "", `Điều kiện bỏ mốc cũ là q[0] <= t - window, tức ${0} <= ${W} - ${W} = 0: đúng (có dấu bằng), nên mốc 0 bị bỏ và yêu cầu mới được nhận. Ca biên có dấu bằng quyết định kết quả.`) }
  };
  bank("w12", "read", [() => { const W = fR(5, 9); return opt(AL, `print(allowed_requests([0, 1, ${W - 1}], 2, ${W}))`, "[True, True, False]", ["[True, True, True]", "[True, False, False]"], ["[True, True, False]"], "", `Ở t = ${W - 1}: ${0} <= ${W - 1} - ${W} = -1 là sai, nên mốc 0 chưa ra khỏi cửa sổ, hàng đợi còn đủ 2 và yêu cầu bị từ chối.`) }]);

  /* mẫu "bối cảnh mới" thứ hai (chống học vẹt: cùng ý, khung code khác) */
  bank("w7", "new", [() => { const a = arr(fR(4, 6), 1, 8), t = fR(6, 11); const seen = new Set(); let v = false; for (const x of a) { if (seen.has(t - x)) { v = true; break } seen.add(x) } return boolQ(`${fPre(`def has_pair_sum(nums, t):\n    seen = set()\n    for x in nums:\n        if t - x in seen:\n            return True\n        seen.add(x)\n    return False\nprint(has_pair_sum(${J(a)}, ${t}))`)}In ra gì?`, v, v ? `Có một số mà bạn cùng cặp (${t} - x) đã nằm trong seen nên trả True.` : `Không số nào có bạn cùng cặp đã được thấy trước đó nên trả False.`, `def has_pair_sum(nums, t):\n    seen = set()\n    for x in nums:\n        if t - x in seen:\n            return True\n        seen.add(x)\n    return False\n`, `print(has_pair_sum(${J(a)}, ${t}))`) }]);
  bank("w8", "new", [() => { const a = fR(2, 4), n = fR(2, 5); return num(`def power(a, n):\n    if n == 0:\n        return 1\n    return a * power(a, n - 1)\n`, `print(power(${a}, ${n}))`, a ** n, `Ca cơ sở n = 0 trả 1; mỗi tầng nhân thêm ${a}: ${a} nhân ${n} lần = ${a ** n}. Cùng khung đệ quy với factorial.`) }]);
  bank("w12", "new", [() => { let t = 0; const ts = Array.from({ length: fR(5, 7) }, () => (t += fR(0, 3))), W = fR(3, 6), now = ts[ts.length - 1] + fR(0, 2), c = ts.filter(x => x > now - W).length; return num(`def count_recent(times, now, window):\n    q = list(times)\n    while q and q[0] <= now - window:\n        q.pop(0)\n    return len(q)\n`, `print(count_recent(${J(ts)}, ${now}, ${W}))`, c, `Bỏ khỏi đầu hàng đợi mọi mốc <= ${now} - ${W} = ${now - W}; còn ${c} mốc. Cùng ý loại mốc quá cũ như allowed_requests.`) }]);

  /* ===== tiền đề: mọi tiền đề đứng TRƯỚC trong lộ trình ===== */
  Object.assign(PREQ, {
    w1: ["l3", "b6"], w2: ["l2", "b6"], w3: ["l3", "w1"], w4: ["h3", "w2"], w5: ["w4"], w6: ["w5"], w7: ["w6"],
    w8: ["r3"], w9: ["m3", "w4"], w10: ["g3", "w9"], w11: ["stk", "w2"], w12: ["rl1", "w11"]
  });
})();
