/* Kiểm tra hiểu thật cho 16 bài còn lại: xưởng ghép b1-b6, mini project m1-m3, rl1, ứng dụng ap1-ap6.
   Nạp sau probe-extra.js. Câu có code gắn _py (chạy Python thật); câu về cú pháp gắn _syn = [[code, ok]] (kiểm bằng compile()). */
const zSyn = (o, arr) => { o._syn = arr; return o };
const zRepr = L => "[" + L.map(t => "{" + Object.entries(t).map(([k, v]) => `'${k}': ${typeof v == "string" ? `'${v}'` : v}`).join(", ") + "}").join(", ") + "]";
const zValid = L => { const seen = new Set(); let bad = 0; for (const t of L) { const dup = seen.has(t.id); seen.add(t.id); if (dup || !["deposit", "withdraw"].includes(t.type) || t.amount < 0) bad++ } return bad };
const zTxs = (n, faults) => { const L = Array.from({ length: n }, (_, i) => ({ id: i + 1, type: aPick(["deposit", "withdraw"]), amount: fR(2, 9) * 10 })); const pos = pShuf(Array.from({ length: n - 1 }, (_, i) => i + 1)); faults.forEach((f, i) => { const p = pos[i]; if (f == "dup") L[p].id = L[p - 1].id; else if (f == "type") L[p].type = aPick(["gift", "refund"]); else L[p].amount = -L[p].amount }); return L };
const zPyValid = "def bad(L):\n    seen = set(); n = 0\n    for t in L:\n        dup = t['id'] in seen\n        seen.add(t['id'])\n        if dup or t['type'] not in ('deposit', 'withdraw') or t['amount'] < 0:\n            n += 1\n    return n\n";

/* ===== m1: yêu cầu thật luôn thiếu chi tiết ===== */
const zM1Doms = [["Yêu cầu: 'tính tổng tiền của giỏ hàng'.", "Giá khuyến mãi, thuế và phí ship có tính vào tổng không?"], ["Yêu cầu: 'tính điểm trung bình của học sinh'.", "Ô điểm bỏ trống khác điểm 0 không, có tính vào trung bình không?"], ["Yêu cầu: 'tính tuổi từ ngày sinh'.", "Tính theo ngày hôm nay hay ngày cố định, và ngày sinh ở tương lai thì xử lý sao?"], ["Yêu cầu: 'tính số ngày nghỉ phép còn lại của nhân viên'.", "Ngày nghỉ nửa buổi và ngày lễ trùng ngày nghỉ có tính không?"]];
PRB.m1 = {
  same: () => { const n = fR(4, 6), L = Array.from({ length: n }, (_, i) => ({ id: i + 1, type: "deposit", amount: fR(2, 9) * 10 })), bad = pShuf(L.map((_, i) => i)).slice(0, fR(1, 2)); bad.forEach(i => delete L[i][aPick(["id", "type", "amount"])]); const ok = L.filter(t => "id" in t && "type" in t && "amount" in t).length, c = `txs = ${zRepr(L)}\nprint(sum(1 for t in txs if 'id' in t and 'type' in t and 'amount' in t))`; return aPy(fT(`Mỗi giao dịch BẮT BUỘC có đủ 3 trường: id, type, amount. Thiếu một trường là dữ liệu hỏng.${fPre(`txs = ${zRepr(L)}`)}Có bao nhiêu giao dịch đủ cả 3 trường?`, ok, `Đếm giao dịch có đủ id, type, amount: ${ok}. ${n - ok} giao dịch thiếu trường.`), c, [String(ok)]) },
  flip: () => { const n = fR(6, 12), t = fR(1, 3); return fT(`Một lô có ${n} giao dịch. Mỗi giao dịch hỏng thiếu đúng 1 trường, và tổng cộng thiếu ${t} trường. Có bao nhiêu giao dịch đủ trường?`, n - t, `${t} giao dịch hỏng (mỗi cái thiếu 1 trường): ${n} - ${t} = ${n - t}.`) },
  new: () => { const d = aPick(zM1Doms); return fC(`${d[0]} Câu hỏi làm rõ nào quan trọng nhất TRƯỚC khi viết code?`, [d[1], "Dùng màu nào để hiển thị kết quả?", "Viết bằng laptop hãng nào?"], "Câu hỏi ảnh hưởng tới kết quả thật (tiền, điểm, ngày) phải được làm rõ trước. Giao diện, máy móc thì tính sau.") },
  verdict: KV("Hà nói: 'khách chưa trả lời thì cứ tự chọn một cách rồi làm, không cần báo ai'. Hà nói đúng hay sai?", "Hà nói: 'khách chưa trả lời thì ghi rõ giả định mình chọn và gửi để họ xác nhận'. Hà nói đúng hay sai?", "Giả định không ghi ra sẽ thành bất ngờ sau này", "Tự chọn là đủ", "Không cần làm gì", "Sai: giả định phải được ghi ra giấy trắng mực đen."),
  read: () => { const bal = fR(2, 5) * 10, w = bal + fR(1, 4) * 10; return fC(`Khách đã xác nhận: "số dư KHÔNG BAO GIỜ được âm". Số dư đang là ${bal}, có yêu cầu rút ${w}. Hệ thống nên làm gì?`, ["Từ chối giao dịch và báo rõ lý do (rút quá số dư)", `Cho phép, số dư thành ${bal - w}`, "Bỏ qua im lặng, coi như chưa có yêu cầu"], `Số dư sau khi rút là ${bal - w}, vi phạm yêu cầu đã chốt. Phải từ chối và nói rõ, không được im lặng.`) }
};
bank("m1", "verdict", [KV("Nam nói: 'yêu cầu ngắn gọn thì đã đủ rõ, không cần hỏi lại'. Nam nói đúng hay sai?", "Nam nói: 'yêu cầu ngắn thường thiếu chi tiết, nên cần hỏi lại trước khi code'. Nam nói đúng hay sai?", "Đoán sai yêu cầu thì code đẹp cũng vô ích", "Ngắn nghĩa là đủ", "Code xong rồi hỏi sau", "Sai: yêu cầu ngắn là chỗ dễ hiểu sai nhất.")]);
bank("m1", "read", [() => fC('Khách đã xác nhận: "giao dịch có amount bằng 0 là HỢP LỆ". Có một giao dịch amount = 0. Hệ thống nên làm gì?', ["Chấp nhận, vì yêu cầu đã chốt là hợp lệ", "Từ chối, vì 0 trông vô nghĩa", "Bỏ qua im lặng"], "Quy tắc nghiệp vụ do khách chốt, không phải do mình thấy hợp lý hay không. Đọc kỹ yêu cầu.")]);

/* ===== m2: liệt kê giao dịch không hợp lệ trước khi code ===== */
PRB.m2 = {
  same: () => { const L = zTxs(fR(5, 6), pShuf(["dup", "type", "neg", "dup", "neg"]).slice(0, fR(2, 3))), bad = zValid(L), c = zPyValid + `print(bad(${zRepr(L)}))`; return aPy(fT(`Quy tắc: mỗi id chỉ xuất hiện một lần (lần đầu hợp lệ, các lần lặp lại là lỗi); type chỉ là 'deposit' hoặc 'withdraw'; amount không được âm.${fPre(`txs = ${zRepr(L)}`)}Có bao nhiêu giao dịch KHÔNG hợp lệ?`, bad, `Dò từng giao dịch theo ba quy tắc: ${bad} giao dịch vi phạm.`), c, [String(bad)]) },
  flip: () => { const a = fR(1, 3), b = fR(1, 3), r = fR(1, 3); return fT(`Một lô có ${a + b + r} giao dịch lỗi (mỗi cái chỉ vi phạm một quy tắc): ${a} cái trùng id, ${b} cái sai type, còn lại là amount âm. Có bao nhiêu giao dịch amount âm?`, r, `${a + b + r} - ${a} - ${b} = ${r}.`) },
  new: () => { const emails = ["a@x.com", "b@x.com", "c@x.com", "d@x.com", "e@x.com"], u = Array.from({ length: fR(4, 5) }, (_, i) => ({ email: emails[i], age: fR(18, 60) })); const pos = pShuf(u.map((_, i) => i)); if (u.length > 1) u[pos[0]].email = u[pos[0]].email.replace("@", ""); u[pos[1]].age = aPick([-3, 150]); if (Math.random() < 0.6) u[pos[2] ?? 1].email = u[(pos[2] ?? 1) == 0 ? 1 : 0].email; const seen = new Set(); let bad = 0; for (const t of u) { const dup = seen.has(t.email); seen.add(t.email); if (!t.email.includes("@") || t.age < 0 || t.age > 120 || dup) bad++ } const c = `def bad(L):\n    seen = set(); n = 0\n    for t in L:\n        dup = t['email'] in seen\n        seen.add(t['email'])\n        if '@' not in t['email'] or t['age'] < 0 or t['age'] > 120 or dup:\n            n += 1\n    return n\nprint(bad(${zRepr(u)}))`; return aPy(fT(`Quy tắc đăng ký: email phải có dấu @; email chỉ đăng ký một lần (lần đầu hợp lệ); tuổi từ 0 đến 120.${fPre(`users = ${zRepr(u)}`)}Có bao nhiêu bản ghi không hợp lệ?`, bad, `Đếm bản ghi vi phạm ít nhất một quy tắc: ${bad}.`), c, [String(bad)]) },
  verdict: KV("Hà nói: 'gặp một giao dịch xấu thì bỏ nó đi, im lặng tính tiếp là an toàn nhất'. Hà nói đúng hay sai?", "Hà nói: 'với tiền, nên từ chối cả lô và báo rõ giao dịch nào sai'. Hà nói đúng hay sai?", "Im lặng bỏ qua làm số dư sai mà không ai biết", "Bỏ qua im lặng luôn an toàn", "Báo lỗi làm chậm hệ thống", "Sai: im lặng bỏ qua dữ liệu xấu rất nguy hiểm."),
  read: () => { const k = fR(3, 4), ids = ["A", "B"], seq = []; const rep = fR(2, 3); for (let i = 0; i < rep; i++) seq.push("A"); seq.push("B"); while (seq.length < k + 1) seq.push("C"); const sh = pShuf(seq), dup = sh.length - new Set(sh).size, c = `ids = ${pJ(sh)}\nprint(len(ids) - len(set(ids)))`; return aPy(aNum(`Quy ước: giao dịch đầu tiên của một id là hợp lệ, các lần lặp lại sau là lỗi. Danh sách id: ${pJ(sh)}. Có bao nhiêu giao dịch lỗi do trùng id?`, dup, `Chỉ tính các lần lặp lại sau lần đầu: ${dup}. Không tính lần xuất hiện đầu tiên.`, [dup + 1, sh.length - dup]), c, [String(dup)]) }
};
bank("m2", "verdict", [KV("Nam nói: 'amount âm do người dùng nhập sai là lỗi bất ngờ của hệ thống'. Nam nói đúng hay sai?", "Nam nói: 'amount âm là lỗi đầu vào dự đoán được: kiểm tra trước rồi raise ValueError'. Nam nói đúng hay sai?", "Ta biết trước người dùng có thể nhập sai", "Không ai đoán được", "Phải bắt bằng try ở tầng ngoài", "Sai: đó là lỗi dự đoán được.")]);
bank("m2", "read", [() => { const c = zPyValid + "print(bad([{'id': 1, 'type': 'gift', 'amount': -5}, {'id': 2, 'type': 'deposit', 'amount': 10}]))"; return aPy(aNum(`${fPre("txs = [{'id': 1, 'type': 'gift', 'amount': -5}, {'id': 2, 'type': 'deposit', 'amount': 10}]")}Giao dịch đầu vừa sai type vừa amount âm. Có bao nhiêu GIAO DỊCH không hợp lệ (không phải số quy tắc bị vi phạm)?`, 1, "Đề hỏi số giao dịch: giao dịch đầu chỉ tính một lần dù vi phạm hai quy tắc.", [2, 3]), c, ["1"]) }]);

/* ===== m3: đường ống kiểm tra, tính, trả ===== */
const zBal = a => { let s = 0, first = 0; a.forEach((x, i) => { s += x; if (s < 0 && !first) first = i + 1 }); return { s, first } };
PRB.m3 = {
  same: () => { const a = [fR(5, 10) * 10, -fR(1, 4) * 10, -fR(1, 4) * 10, fR(1, 3) * 10], s = zBal(a).s, c = `t = ${pJ(a)}\ntotal = 0\nfor x in t:\n    total += x\nprint(total)`; return aPy(fT(`${fPre(c)}(số dương là nạp, số âm là rút) In ra mấy?`, s, `${a.join(" ")} cộng dồn = ${s}.`), c, [String(s)]) },
  flip: () => { const f = fR(2, 9) * 10, x = fR(1, 5) * 10; return fT(`Sau giao dịch cuối (nạp ${x}), số dư là ${f}. Ngay trước giao dịch cuối, số dư là bao nhiêu?`, f - x, `${f} - ${x} = ${f - x}.`) },
  new: () => { const a = [fR(3, 6) * 10, -fR(7, 9) * 10, fR(5, 9) * 10, -fR(1, 3) * 10]; const r = zBal(a), c = `t = ${pJ(a)}\ntotal = 0\nfirst = 0\nfor i in range(len(t)):\n    total += t[i]\n    if total < 0 and first == 0:\n        first = i + 1\nprint(first)`; return aPy(fT(`${fPre(`t = ${pJ(a)}`)}Số dư bắt đầu từ 0 và KHÔNG được âm. Giao dịch thứ mấy (đếm từ 1) là giao dịch đầu tiên làm số dư âm? (Không có thì ghi 0.)`, r.first, `Cộng dồn từng bước: ${(() => { let s = 0; return a.map(x => (s += x)).join(", ") })()}.`), c, [String(r.first)]) },
  verdict: KV("Hà nói: 'chỉ cần kiểm tra số dư không âm ở cuối là đủ'. Hà nói đúng hay sai?", "Hà nói: 'số dư phải hợp lệ ở mọi thời điểm, nên kiểm tra sau mỗi giao dịch rút'. Hà nói đúng hay sai?", "Giữa chừng âm thì đã sai dù cuối cùng dương", "Chỉ kết quả cuối mới quan trọng", "Không cần kiểm tra", "Sai: số dư âm giữa chừng đã vi phạm."),
  read: () => { const a = fR(3, 5) * 10, b = a + fR(2, 4) * 10, c2 = b + fR(2, 4) * 10, t = [a, -b, c2], k = zBal(t), c = `t = ${pJ(t)}\ntotal = 0\nmin_total = 0\nfor x in t:\n    total += x\n    min_total = min(min_total, total)\nprint(total, min_total)`; return aPy(fC(`Danh sách giao dịch ${pJ(t)} (dương là nạp, âm là rút), số dư đầu 0. Số dư cuối là ${k.s}, dương. Quy tắc "số dư không bao giờ âm" có bị vi phạm không?`, [`Có, vi phạm ở giao dịch thứ ${k.first}`, "Không, vì số dư cuối dương", "Không đủ thông tin"], `Sau giao dịch thứ ${k.first} số dư là ${a - b}, âm, dù cuối cùng lại dương.`), c, [`${k.s} ${a - b}`]) }
};
bank("m3", "new", [() => { const D = [["tính điểm trung bình của lớp từ danh sách điểm", "Kiểm tra danh sách có rỗng không và điểm có nằm trong 0 đến 10 không"], ["tính tổng tiền từ danh sách giá", "Kiểm tra danh sách có rỗng không và giá có âm không"], ["tính nhiệt độ trung bình từ danh sách số đo", "Kiểm tra danh sách có rỗng không và số đo có hợp lý không"]], d = aPick(D); return fC(`Hàm cần ${d[0]}. Theo đường ống (kiểm tra, tính, trả), bước làm ĐẦU TIÊN là gì?`, [d[1], "Chia tổng cho số phần tử", "Trả kết quả cho người gọi"], "Kiểm tra đầu vào trước: dữ liệu hỏng thì tính có ý nghĩa gì? Danh sách rỗng còn gây chia cho 0.") }]);
bank("m3", "verdict", [KV("Nam nói: 'tính trước rồi kiểm tra sau cũng như kiểm tra trước rồi tính'. Nam nói đúng hay sai?", "Nam nói: 'kiểm tra đầu vào trước khi tính'. Nam nói đúng hay sai?", "Dữ liệu hỏng thì kết quả tính ra vô nghĩa", "Thứ tự không quan trọng", "Chỉ kiểm tra ở cuối", "Sai: kiểm tra trước, tính sau.")]);
bank("m3", "read", [() => { const a = fR(2, 4) * 10, b = fR(5, 9) * 10, t = [a, -b], k = zBal(t); return fC(`Số dư đầu 0, giao dịch ${pJ(t)}. Yêu cầu: số dư không âm. Theo đường ống, hàm nên làm gì khi gặp giao dịch thứ 2?`, ["Dừng và báo lỗi rõ ràng (rút quá số dư)", `Tiếp tục và trả ${k.s}`, "Bỏ qua giao dịch đó, im lặng trả kết quả"], `Sau giao dịch 2 số dư là ${k.s}, âm. Phải báo lỗi chứ không được trả số sai hoặc im lặng bỏ qua.`) }]);

/* ===== rl1: rate limiter ===== */
const zRl = (times, L, W) => { const q = [], acc = []; for (const t of times) { while (q.length && q[0] <= t - W) q.shift(); if (q.length < L) { q.push(t); acc.push(1) } else acc.push(0) } return acc };
const zRlPy = "def sim(times, L, W):\n    q = []; out = []\n    for t in times:\n        while q and q[0] <= t - W:\n            q.pop(0)\n        if len(q) < L:\n            q.append(t); out.append(1)\n        else:\n            out.append(0)\n    return out\n";
const zTimes = n => { let t = 0; return Array.from({ length: n }, () => (t += fR(0, 2))) };
const zRule = (L, W) => `Giới hạn: tối đa ${L} yêu cầu trong mỗi ${W} giây. Với yêu cầu đến lúc t, chỉ các thời điểm đã chấp nhận LỚN HƠN t - ${W} còn được tính. Yêu cầu bị từ chối không được ghi lại.`;
PRB.rl1 = {
  same: () => { const L = fR(1, 3), W = fR(3, 5), T = zTimes(fR(6, 8)), a = zRl(T, L, W), n = a.reduce((x, y) => x + y, 0); return aPy(fT(`${zRule(L, W)} Các yêu cầu đến lúc: ${pJ(T)}. Có bao nhiêu yêu cầu được chấp nhận?`, n, `Dò từng yêu cầu: kết quả (1 là chấp nhận) ${a.join(", ")}.`), zRlPy + `print(sum(sim(${pJ(T)}, ${L}, ${W})))`, [String(n)]) },
  flip: () => { const W = fR(3, 6), t1 = fR(1, 3), t2 = t1 + fR(1, 2); return aPy(fT(`${zRule(2, W)} Hàng đợi đang giữ [${t1}, ${t2}]. Yêu cầu mới sớm nhất đến lúc giây thứ mấy thì được chấp nhận? (Giây là số nguyên.)`, t1 + W, `Thời điểm ${t1} chỉ hết hạn khi t - ${W} >= ${t1}, tức t >= ${t1 + W}. Đến lúc đó hàng còn 1 chỗ trống.`), zRlPy + `t = ${t2}\nwhile sim([${t1}, ${t2}, t], 2, ${W})[2] == 0:\n    t += 1\nprint(t)`, [String(t1 + W)]) },
  new: () => { const T = zTimes(fR(6, 8)), a = zRl(T, 3, 10), rej = a.filter(x => !x).length; const T2 = T.map(x => x * 2); const b = zRl(T2, 3, 10), r2 = b.filter(x => !x).length; return aPy(fT(`Tối đa 3 lần đăng nhập sai trong mỗi 10 phút (cùng quy tắc: chỉ tính thời điểm lớn hơn t - 10, lần bị từ chối không ghi). Các lần thử đến lúc (phút): ${pJ(T2)}. Có bao nhiêu lần thử bị TỪ CHỐI?`, r2, `Dò từng lần: ${b.join(", ")} (0 là bị từ chối).`), zRlPy + `print(sim(${pJ(T2)}, 3, 10).count(0))`, [String(r2)]) },
  verdict: KV("Hà nói: 'yêu cầu bị từ chối cũng phải ghi vào hàng đợi, nếu không người dùng sẽ gửi dồn dập mãi'. Hà nói đúng hay sai (với giả định đã chọn: chỉ ghi yêu cầu được chấp nhận)?", "Hà nói: 'với giả định đã chọn, yêu cầu bị từ chối không làm hàng đợi dài thêm'. Hà nói đúng hay sai?", "Chỉ yêu cầu được chấp nhận mới chiếm chỗ trong cửa sổ", "Mọi yêu cầu đều chiếm chỗ", "Hàng đợi luôn đầy", "Sai: theo giả định đã chọn, chỉ ghi yêu cầu được chấp nhận."),
  read: () => { const W = fR(3, 5), a = fR(1, 3), b = a + 1, edge = Math.random() < 0.5, t = a + W - (edge ? 0 : 1), acc = zRl([a, b, t], 2, W)[2]; return aPy(fC(`${zRule(2, W)} Hàng đợi đang giữ [${a}, ${b}]. Yêu cầu mới đến lúc ${t}. Chấp nhận hay từ chối?`, acc ? ["Chấp nhận", "Từ chối", "Không đủ thông tin"] : ["Từ chối", "Chấp nhận", "Không đủ thông tin"], acc ? `${a} > ${t} - ${W} = ${t - W}? Không (${a} <= ${t - W}), nên ${a} đã hết hạn. Còn chỗ: chấp nhận.` : `${a} > ${t} - ${W} = ${t - W}? Có, nên ${a} vẫn còn tính. Cả hai chỗ đã đầy: từ chối.`), zRlPy + `print(sim([${a}, ${b}, ${t}], 2, ${W})[2])`, [String(acc)]) }
};
bank("rl1", "verdict", [KV("Nam nói: 'thời điểm cũ nhất nằm ở cuối hàng đợi'. Nam nói đúng hay sai?", "Nam nói: 'thời điểm cũ nhất nằm ở đầu hàng đợi và hết hạn trước'. Nam nói đúng hay sai?", "Vào trước thì ra trước: queue", "Vào sau thì ra trước", "Thứ tự không quan trọng", "Sai: cũ nhất ở đầu hàng.")]);
bank("rl1", "read", [() => { const W = fR(3, 5), L = 3, T = [1, 2, 3, 4].map(x => x + fR(0, 1) * 0), t = 4 + W - 1, q = zRl([1, 2, 3, t], L, W); const cnt = [1, 2, 3].filter(x => x > t - W).length; return aPy(aNum(`${zRule(L, W)} Hàng đợi đang giữ [1, 2, 3]. Yêu cầu mới đến lúc ${t}. Trước khi quyết định, còn BAO NHIÊU thời điểm trong cửa sổ (lớn hơn ${t - W})?`, cnt, `Giữ lại các thời điểm > ${t - W}: ${cnt} cái.`, [3 - cnt, 3]), `print(len([x for x in [1, 2, 3] if x > ${t - W}]))`, [String(cnt)]) }]);

/* ===== ap1: cache ===== */
const zSeq = n => Array.from({ length: n }, () => aPick(["A", "B", "C", "D"]));
PRB.ap1 = {
  same: () => { const s = zSeq(fR(6, 8)), seen = new Set(); let h = 0; s.forEach(k => seen.has(k) ? h++ : seen.add(k)); const c = `seen = set()\nhits = 0\nfor k in ${pJ(s)}:\n    if k in seen:\n        hits += 1\n    else:\n        seen.add(k)\nprint(hits)`; return aPy(fT(`${fPre(c)}Đoạn này mô phỏng cache: gặp lại khóa đã thấy là trúng (hit). In ra mấy?`, h, `Chỉ ${seen.size} khóa khác nhau nên ${seen.size} lần trượt, còn lại ${h} lần trúng.`), c, [String(h)]) },
  flip: () => { const n = fR(6, 10), h = fR(2, n - 2), T = 100 * (n - h) + h; return fT(`Hỏi cơ sở dữ liệu (trượt cache) mất 100ms, tra cache (trúng) mất 1ms. ${n} lần gọi tốn tổng cộng ${T}ms. Có bao nhiêu lần trúng cache?`, h, `Nếu h lần trúng: 100 x (${n} - h) + h = ${T}, suy ra h = ${h}.`) },
  new: () => { const ttl = fR(3, 8), q = fR(1, ttl + 3), old = q < ttl; return fC(`Cache giữ giá sản phẩm trong ${ttl} phút kể từ lúc lưu (phút 0). Ở phút 1, giá thật trong cơ sở dữ liệu đổi. Ở phút ${q}, người dùng hỏi giá. Họ thấy giá nào? (Hết hạn đúng phút ${ttl}: lúc đó cache đã hết hạn.)`, old ? ["Giá cũ (cache chưa hết hạn)", "Giá mới", "Không thấy giá nào"] : ["Giá mới (cache đã hết hạn, hỏi lại cơ sở dữ liệu)", "Giá cũ", "Không thấy giá nào"], old ? `Phút ${q} < ${ttl}: cache còn hạn nên trả giá cũ (dữ liệu cũ, stale).` : `Phút ${q} >= ${ttl}: cache hết hạn, phải hỏi lại và lấy giá mới.`) },
  verdict: KV("Hà nói: 'cache luôn cho dữ liệu mới nhất'. Hà nói đúng hay sai?", "Hà nói: 'cache có thể giữ dữ liệu cũ, nên cần hạn dùng hoặc cách làm mới'. Hà nói đúng hay sai?", "Cache không tự biết dữ liệu gốc đã đổi", "Cache luôn đồng bộ", "Cache tự cập nhật", "Sai: cache có thể cũ (stale)."),
  read: () => { const s = zSeq(fR(6, 8)), d = new Set(s).size, h = s.length - d, c = `print(len(set(${pJ(s)})))`; return aPy(aNum(`Các khóa gọi lần lượt: ${pJ(s)}. Cache rỗng lúc đầu. Đề hỏi: có bao nhiêu lần TRƯỢT cache (không hỏi trúng)?`, d, `Mỗi khóa trượt đúng lần đầu gặp: ${d} khóa khác nhau nên ${d} lần trượt. ${h} là số lần trúng.`, [h, s.length]), c, [String(d)]) }
};
bank("ap1", "new", [() => { const n = fR(2, 5) * 4, h = n / 4 * fR(1, 3), pct = h * 100 / n; return fT(`Một cache được gọi ${n} lần, trúng ${h} lần. Tỉ lệ trúng (hit rate) là bao nhiêu phần trăm?`, pct, `${h} / ${n} x 100 = ${pct}%.`) }]);
bank("ap1", "verdict", [KV("Nam nói: 'cache dùng list vì list tra nhanh nhất'. Nam nói đúng hay sai?", "Nam nói: 'cache dùng dictionary vì tra theo khóa gần như một bước'. Nam nói đúng hay sai?", "Dictionary tra theo khóa là O(1)", "List tra theo khóa là O(1)", "Cache không cần cấu trúc dữ liệu", "Sai: list phải duyệt từng phần tử.")]);
bank("ap1", "read", [() => { const s = zSeq(fR(6, 8)), seen = new Set(); let h = 0; s.forEach(k => seen.has(k) ? h++ : seen.add(k)); const first = s[0], c = `print(0)`; return aPy(fC(`Cache rỗng. Các khóa gọi lần lượt: ${pJ(s)}. Lần gọi ĐẦU TIÊN (khóa ${first}) là trúng hay trượt?`, ["Trượt, vì cache còn rỗng", "Trúng", "Không đủ thông tin"], "Chưa có gì trong cache thì lần đầu luôn phải hỏi nguồn gốc."), c, ["0"]) }]);

/* ===== ap2: job queue ===== */
const zJobs = () => { const q = [], ops = [], ran = []; const names = pShuf(["A", "B", "C", "D", "E"]); let i = 0; const n = fR(4, 5); const seq = []; for (let k = 0; k < n; k++) { seq.push(["add", names[i++]]); if (k >= 1 && Math.random() < 0.6) seq.push(["run"]) } seq.push(["run"]); return seq };
PRB.ap2 = {
  same: () => { const seq = zJobs(), q = [], ran = []; seq.forEach(o => { if (o[0] == "add") q.push(o[1]); else if (q.length) ran.push(q.shift()) }); const c = "q = []\nran = []\n" + seq.map(o => o[0] == "add" ? `q.append("${o[1]}")` : "ran.append(q.pop(0))").join("\n") + "\nprint(len(q))"; return aPy(fT(`${fPre(c)}Công việc xếp hàng chờ xử lý (append là thêm việc, pop(0) lấy việc ra làm). Cuối cùng còn bao nhiêu việc đang chờ?`, q.length, `Đã làm ${ran.length} việc (${ran.join(", ")}), còn ${q.length} việc.`), c, [String(q.length)]) },
  flip: () => { const done = fR(2, 5), left = fR(1, 4); return fT(`Hàng đợi công việc đã xử lý xong ${done} việc và còn ${left} việc chờ. Không có việc nào bị bỏ. Ban đầu có tổng cộng bao nhiêu việc?`, done + left, `${done} + ${left} = ${done + left}.`) },
  new: () => { const m = fR(3, 9), k = fR(2, 4); return fT(`Máy xử lý đúng 1 việc mỗi lần, mỗi việc mất ${k} giây, theo thứ tự đến. ${m + 3} việc đến cùng lúc. Việc thứ ${m} (đếm từ 1) phải chờ bao nhiêu giây trước khi BẮT ĐẦU?`, (m - 1) * k, `Phải chờ ${m - 1} việc đứng trước, mỗi việc ${k} giây: ${(m - 1) * k}.`) },
  verdict: KV("Hà nói: 'hàng chờ in dùng stack cho công bằng'. Hà nói đúng hay sai?", "Hà nói: 'hàng chờ in dùng queue vì việc đến trước được làm trước'. Hà nói đúng hay sai?", "Stack làm việc đến sau chen lên trước", "Stack công bằng hơn", "Không khác nhau", "Sai: stack khiến việc đến trước phải chờ mãi."),
  read: () => { const n = pShuf(["A", "B", "C", "D"]).slice(0, 3), c = `q = []\n${n.map(x => `q.append("${x}")`).join("\n")}\nprint(q.pop())`; return aPy(aStr(`${fPre(c)}Hàng chờ xử lý việc, nhưng đọc kỹ lệnh lấy việc ra: print(q.pop()) (không có số 0). Việc nào được lấy ra?`, n[2], n, `pop() lấy phần tử CUỐI (như stack), tức ${n[2]}, không phải việc đến đầu tiên (${n[0]}). Hàng chờ đúng phải dùng pop(0).`), c, [n[2]]) }
};
bank("ap2", "verdict", [KV("Nam nói: 'khi việc dồn lên đột ngột, tốt nhất là xử lý hết cùng lúc'. Nam nói đúng hay sai?", "Nam nói: 'cho việc vào hàng đợi và xử lý dần theo khả năng giúp hệ thống không quá tải'. Nam nói đúng hay sai?", "Làm hết cùng lúc có thể làm sập máy", "Xử lý cùng lúc luôn nhanh hơn", "Từ chối mọi việc", "Sai: dồn cùng lúc dễ quá tải.")]);
bank("ap2", "read", [() => { const a = fR(2, 5), b = fR(1, a - 1 || 1), c = `q = []\nfor i in range(${a}):\n    q.append(i)\nfor i in range(${b}):\n    q.pop(0)\nprint(q[0])`; return aPy(aNum(`${fPre(c)}Đọc kỹ: in ra phần tử ĐẦU hàng còn lại. Mấy?`, b, `Đã lấy ra ${b} việc đầu (0 đến ${b - 1}), việc đầu hàng giờ là ${b}.`, [a - 1, 0]), c, [String(b)]) }]);

/* ===== ap3: stack Undo và ngoặc ===== */
const zBr = s => { const st = []; const m = { ")": "(", "]": "[" }; for (const ch of s) { if ("([".includes(ch)) st.push(ch); else { if (!st.length) return "R2"; if (st.pop() != m[ch]) return "R3" } } return st.length ? "R1" : "OK" };
const zBrPy = "def chk(s):\n    st = []\n    m = {')': '(', ']': '['}\n    for ch in s:\n        if ch in '([':\n            st.append(ch)\n        else:\n            if not st:\n                return 'R2'\n            if st.pop() != m[ch]:\n                return 'R3'\n    return 'R1' if st else 'OK'\n";
const zBrR = { R1: "còn ngoặc mở chưa được đóng", R2: "gặp ngoặc đóng khi chưa có ngoặc mở nào", R3: "ngoặc đóng không khớp với ngoặc mở gần nhất" };
const zBrGen = () => { const pool = ["(", ")", "[", "]"]; let s; do { s = Array.from({ length: fR(3, 6) }, () => aPick(pool)).join("") } while (false); return s };
PRB.ap3 = {
  same: () => { const n = fR(3, 6), u = fR(1, n - 1), c = "history = []\n" + Array.from({ length: n }, (_, i) => `history.append("${String.fromCharCode(97 + i)}")`).join("\n") + "\n" + Array.from({ length: u }, () => "history.pop()").join("\n") + "\nprint(len(history))"; return aPy(fT(`${fPre(c)}Mỗi append là một thao tác soạn thảo, mỗi pop là một lần Undo. Còn bao nhiêu thao tác trong lịch sử?`, n - u, `${n} thao tác, ${u} lần hoàn tác: ${n - u}.`), c, [String(n - u)]) },
  flip: () => { const u = fR(1, 3), r = fR(1, 4); return fT(`Sau khi bấm Undo ${u} lần, lịch sử còn ${r} thao tác. Ban đầu người dùng đã thực hiện bao nhiêu thao tác?`, u + r, `${r} + ${u} = ${u + r}.`) },
  new: () => { let s; do { s = zBrGen() } while (zBr(s) == "OK" && Math.random() < 0.5); const r = zBr(s), c = zBrPy + `print(chk('${s}'))`; return aPy(fC(`Kiểm tra chuỗi ngoặc "${s}" bằng stack (mở thì cất vào, đóng thì lấy ra so khớp). Kết luận?`, r == "OK" ? ["Hợp lệ", "Không hợp lệ", "Không đủ thông tin"] : [`Không hợp lệ: ${zBrR[r]}`, "Hợp lệ", `Không hợp lệ: ${zBrR[r == "R1" ? "R2" : "R1"]}`], r == "OK" ? "Mọi ngoặc đóng đều khớp ngoặc mở gần nhất và stack rỗng ở cuối." : `Dừng theo stack: ${zBrR[r]}.`), c, [r]) },
  verdict: KV("Hà nói: 'Undo hoàn tác thao tác đầu tiên mà người dùng đã làm'. Hà nói đúng hay sai?", "Hà nói: 'Undo hoàn tác thao tác gần nhất, vì stack vào sau ra trước'. Hà nói đúng hay sai?", "Ngoặc/thao tác mới nhất phải được xử lý trước", "Thao tác cũ nhất ra trước", "Thứ tự ngẫu nhiên", "Sai: Undo hoàn tác thao tác gần nhất."),
  read: () => { const S = ["(()", "())", ")(", "[(])", "(]"], s = aPick(S), r = zBr(s), c = zBrPy + `print(chk('${s}'))`, eq = s.split("(").length - 1 == s.split(")").length - 1 && !s.includes("["); return aPy(fC(`Chuỗi "${s}". ${eq ? "Số ngoặc mở bằng số ngoặc đóng. " : ""}Có hợp lệ không?`, [`Không hợp lệ: ${zBrR[r]}`, "Hợp lệ, vì ngoặc đủ cặp", `Không hợp lệ: ${zBrR[r == "R1" ? "R2" : "R1"]}`], `Đếm đủ cặp chưa đủ: thứ tự mới quan trọng. Stack báo: ${zBrR[r]}.`), c, [r]) }
};
bank("ap3", "verdict", [KV("Nam nói: 'chuỗi ([)] hợp lệ vì có đủ ngoặc mở và đóng'. Nam nói đúng hay sai?", "Nam nói: 'chuỗi ([)] không hợp lệ vì ] phải đóng [ chứ không phải ('. Nam nói đúng hay sai?", "Ngoặc mở gần nhất phải được đóng trước", "Chỉ cần đủ số lượng", "Thứ tự không quan trọng", "Sai: lồng nhau phải đóng đúng thứ tự.")]);
bank("ap3", "new", [() => { const n = fR(3, 5), b = fR(1, n - 1), pg = ["A", "B", "C", "D", "E"].slice(0, n); return fC(`Trình duyệt: mở lần lượt các trang ${pg.join(", ")} (mỗi trang mới đẩy vào lịch sử). Bấm Back ${b} lần. Đang ở trang nào?`, [pg[n - 1 - b], ...pg.filter((_, i) => i != n - 1 - b).slice(0, 2)], `Back lùi về trang trước trong lịch sử: stack, bỏ ${b} trang trên cùng.`) }]);

/* ===== ap4: phụ thuộc gói là đồ thị ===== */
function zDag(n) { const nm = pShuf(["app", "web", "lib", "log", "core", "db", "ui"]).slice(0, n), deps = {}; nm.forEach(x => deps[x] = []); for (let i = 0; i < n - 1; i++) { const k = fR(1, Math.min(2, n - 1 - i)); const cand = pShuf(nm.slice(i + 1)).slice(0, k); deps[nm[i]] = cand } return { nm, deps } }
const zTopo = deps => { const out = [], seen = new Set(); const f = x => { if (seen.has(x)) return; seen.add(x); deps[x].forEach(f); out.push(x) }; Object.keys(deps).forEach(f); return out };
const zValidOrd = (o, deps) => { const pos = {}; o.forEach((x, i) => pos[x] = i); return Object.keys(deps).every(x => deps[x].every(y => pos[y] < pos[x])) };
const zDepLit = d => "deps = {" + Object.keys(d).map(x => `"${x}": [${d[x].map(y => `"${y}"`).join(", ")}]`).join(", ") + "}";
const zClosure = (deps, s) => { const seen = new Set(); const f = x => { if (seen.has(x)) return; seen.add(x); deps[x].forEach(f) }; f(s); return seen.size };
PRB.ap4 = {
  same: () => { const G = zDag(fR(4, 5)), s = G.nm[0], n = zClosure(G.deps, s), c = zDepLit(G.deps) + `\nseen = set()\ndef f(x):\n    if x in seen:\n        return\n    seen.add(x)\n    for y in deps[x]:\n        f(y)\nf("${s}")\nprint(len(seen))`; return aPy(fT(`${fPre(zDepLit(G.deps))}Mỗi khóa là một gói, danh sách là các gói nó CẦN. Để cài "${s}" cần cài tổng cộng bao nhiêu gói (kể cả "${s}")?`, n, `Gom "${s}" và mọi gói nó cần, trực tiếp hay gián tiếp: ${n} gói.`), c, [String(n)]) },
  flip: () => { const k = fR(2, 4); return fT(`Gói X cần đúng ${k} gói khác, và mỗi gói trong số đó không cần gói nào. Cài X cần tổng cộng bao nhiêu gói (kể cả X)?`, k + 1, `${k} gói nền + X = ${k + 1}.`) },
  new: () => { const cyc = Math.random() < 0.5, k = fR(2, 4), nm = pShuf(["Toán A", "Toán B", "Lý", "Hóa", "Tin"]).slice(0, k), d = {}; nm.forEach((x, i) => d[x] = cyc ? [nm[(i + 1) % k]] : (i < k - 1 ? [nm[i + 1]] : [])); const ok = !cyc; return fC(`Môn học và môn tiên quyết (phải học trước): ${nm.map(x => `"${x}" cần ${d[x].length ? `"${d[x][0]}"` : "không môn nào"}`).join("; ")}. Có thứ tự học nào hợp lệ không?`, ok ? ["Có", "Không: phụ thuộc vòng", "Không đủ thông tin"] : ["Không: phụ thuộc vòng, môn nào cũng phải đợi môn khác", "Có", "Không đủ thông tin"], ok ? `Đi theo chuỗi, môn cuối không cần ai nên học trước, rồi lùi dần.` : "Mỗi môn đều cần một môn khác trong vòng nên không môn nào học trước được.") },
  verdict: KV("Hà nói: 'phụ thuộc vòng thì vẫn luôn tìm được một thứ tự cài hợp lệ'. Hà nói đúng hay sai?", "Hà nói: 'phụ thuộc vòng thì không có thứ tự hợp lệ, hệ thống phải báo lỗi'. Hà nói đúng hay sai?", "Gói nào cũng phải đợi gói khác", "Cài song song là xong", "Bỏ qua một gói", "Sai: vòng thì không có điểm xuất phát."),
  read: () => { const a = aPick(["app", "web"]), b = aPick(["lib", "core"]); const c = `deps = {"${a}": ["${b}"], "${b}": []}\nprint("${b}")`; return aPy(fC(`${fPre(`deps = {"${a}": ["${b}"], "${b}": []}`)}Danh sách của mỗi khóa là các gói nó CẦN. Gói nào phải cài TRƯỚC?`, [b, a, "Thứ tự không quan trọng"], `"${a}" cần "${b}", nên "${b}" phải có trước. Mũi tên "cần" chỉ về gói phải cài trước.`), c, [b]) }
};
bank("ap4", "verdict", [KV("Nam nói: 'cài gói nào trước cũng được, miễn cài đủ'. Nam nói đúng hay sai?", "Nam nói: 'gói không cần ai phải được cài trước những gói dựa vào nó'. Nam nói đúng hay sai?", "Mỗi gói chỉ cài được khi các gói nó cần đã có", "Thứ tự không quan trọng", "Cài ngược cũng được", "Sai: thứ tự phải tôn trọng phụ thuộc.")]);
bank("ap4", "new", [() => { const G = zDag(4), good = zTopo(G.deps); let bad; do { bad = pShuf(good) } while (zValidOrd(bad, G.deps)); const bad2 = (() => { let b2; let t = 0; do { b2 = pShuf(good); t++ } while ((zValidOrd(b2, G.deps) || b2.join() == bad.join()) && t < 200); return zValidOrd(b2, G.deps) ? good.slice().reverse() : b2 })(); const opts = [good.join(", "), bad.join(", "), bad2.join(", ")]; if (new Set(opts).size < 3 || !zValidOrd(good, G.deps) || zValidOrd(bad, G.deps) || zValidOrd(bad2, G.deps)) return PRB.ap4.same(); return aPy(fC(`${fPre(zDepLit(G.deps))}Thứ tự cài nào HỢP LỆ (mỗi gói chỉ cài khi các gói nó cần đã có)?`, opts, "Gói nào không cần ai đứng đầu, rồi các gói dựa vào chúng. Hai thứ tự kia có gói đứng trước gói nó cần."), `${zDepLit(G.deps)}\ndef ok(o):\n    p = {x: i for i, x in enumerate(o)}\n    return all(p[y] < p[x] for x in deps for y in deps[x])\nprint(ok(${pJ(good)}), ok(${pJ(bad)}), ok(${pJ(bad2)}))`, ["True False False"]) }]);
bank("ap4", "read", [() => { let G, cnt, w; do { G = zDag(5); cnt = {}; Object.values(G.deps).flat().forEach(y => cnt[y] = (cnt[y] || 0) + 1); const mx = Math.max(...Object.values(cnt)); const ws = Object.keys(cnt).filter(k => cnt[k] == mx); w = ws.length == 1 && mx >= 2 ? ws[0] : null } while (!w); return aPy(aStr(`${fPre(zDepLit(G.deps))}Đọc kỹ: gói nào được NHIỀU gói khác cần nhất (xuất hiện trong nhiều danh sách nhất)?`, w, G.nm, `"${w}" xuất hiện trong ${cnt[w]} danh sách, nhiều nhất. Đề không hỏi gói cần nhiều gói nhất.`), `${zDepLit(G.deps)}\nfrom collections import Counter\nc = Counter(y for x in deps for y in deps[x])\nprint(c.most_common(1)[0][0])`, [w]) }]);

/* ===== ap5: thư mục là cây, đệ quy ===== */
function zFs(sizeRoot) { const leaf = () => ({ size: fR(1, 9), children: [] }); const dir = () => ({ size: 0, children: [leaf(), leaf()].slice(0, fR(1, 2)) }); const root = { size: sizeRoot, children: [leaf(), dir()] }; if (Math.random() < 0.5) root.children.push(leaf()); return root }
const zFsLit = n => `{"size": ${n.size}, "children": [${n.children.map(zFsLit).join(", ")}]}`;
const zFsTot = n => n.size + n.children.reduce((s, c) => s + zFsTot(c), 0);
const zFsCnt = n => 1 + n.children.reduce((s, c) => s + zFsCnt(c), 0);
const zFsDepth = n => 1 + Math.max(0, ...n.children.map(zFsDepth));
const zFsFn = "def total(n):\n    s = n[\"size\"]\n    for c in n[\"children\"]:\n        s += total(c)\n    return s\n";
PRB.ap5 = {
  same: () => { const t = zFs(0), c = `tree = ${zFsLit(t)}\n` + zFsFn + "print(total(tree))"; return aPy(fT(`${fPre(c.replace("\nprint(total(tree))", ""))}Mỗi nút là tệp (size là dung lượng) hoặc thư mục (size 0, children là các nút con). In ra total(tree) là mấy?`, zFsTot(t), `Cộng dung lượng mọi nút từ lá lên: ${zFsTot(t)}.`), c, [String(zFsTot(t))]) },
  flip: () => { const a = fR(2, 9), b = fR(2, 9), x = fR(2, 9); return fT(`Thư mục gốc (size 0) chứa ba tệp: ${a}, ${b} và một tệp chưa biết. total(gốc) = ${a + b + x}. Tệp chưa biết có dung lượng bao nhiêu?`, x, `${a + b + x} - ${a} - ${b} = ${x}.`) },
  new: () => { const t = zFs(0), n = zFsCnt(t), c = `tree = ${zFsLit(t)}\ndef dem(n):\n    k = 1\n    for c in n["children"]:\n        k += dem(c)\n    return k\nprint(dem(tree))`; return aPy(fT(`${fPre(`tree = ${zFsLit(t)}`)}Sơ đồ công ty: mỗi nút là một nhân sự, children là người họ quản lý. Hàm dem đếm mỗi nút một lần (1 + tổng dem của các con). dem(tree) bằng mấy?`, n, `Đếm mọi nút: ${n}.`), c, [String(n)]) },
  verdict: KV("Hà nói: 'thư mục tự có sẵn một con số dung lượng, chỉ cần đọc ra'. Hà nói đúng hay sai?", "Hà nói: 'dung lượng thư mục là tổng dung lượng mọi thứ nằm trong nó, tính bằng đệ quy'. Hà nói đúng hay sai?", "Thư mục chỉ là cái chứa, dung lượng nằm ở các tệp", "Thư mục tự biết dung lượng", "Chỉ cộng tệp cấp ngoài cùng", "Sai: phải cộng từ lá lên."),
  read: () => { const s = fR(2, 4), t = zFs(s), tot = zFsTot(t), kids = tot - s, c = `tree = ${zFsLit(t)}\n` + zFsFn + "print(total(tree))"; return aPy(aNum(`${fPre(`tree = ${zFsLit(t)}`)}Hàm total cộng size của chính nút rồi cộng total của các con. Chú ý: nút GỐC này có size ${s}, không phải 0. total(tree) bằng mấy?`, tot, `Phải cộng cả size của gốc (${s}) với phần các con (${kids}): ${tot}.`, [kids, s]), c, [String(tot)]) }
};
bank("ap5", "new", [() => { const t = zFs(0), d = zFsDepth(t), c = `tree = ${zFsLit(t)}\ndef cao(n):\n    return 1 + max([cao(c) for c in n["children"]] + [0])\nprint(cao(tree))`; return aPy(fT(`${fPre(`tree = ${zFsLit(t)}`)}Hàm cao cho biết số tầng của cây thư mục (gốc tính là 1 tầng). cao(tree) bằng mấy?`, d, `Đường dài nhất từ gốc xuống nút sâu nhất có ${d} nút.`), c, [String(d)]) }]);
bank("ap5", "verdict", [KV("Nam nói: 'hàm total không cần ca cơ sở'. Nam nói đúng hay sai?", "Nam nói: 'ca cơ sở của total là nút không có con: vòng for không chạy'. Nam nói đúng hay sai?", "Không có con thì không gọi đệ quy nữa", "total luôn gọi tiếp", "Cây rỗng là ca cơ sở duy nhất", "Sai: nút lá chính là chỗ dừng.")]);
bank("ap5", "read", [() => { const a = fR(2, 9), b = fR(2, 9), t = { size: 0, children: [{ size: a, children: [] }, { size: 0, children: [{ size: b, children: [] }] }] }, c = `tree = ${zFsLit(t)}\n` + zFsFn + `print(total(tree["children"][1]))`; return aPy(aNum(`${fPre(`tree = ${zFsLit(t)}`)}Đọc kỹ: gọi total trên nút con thứ HAI (tree["children"][1]), không phải cả cây. In ra mấy?`, b, `Nút con thứ hai là thư mục chứa một tệp ${b}: total = ${b}. Tệp ${a} nằm ở nút con thứ nhất, không tính.`, [a + b, a]), c, [String(b)]) }]);

/* ===== ap6: chọn cấu trúc dữ liệu ===== */
const zDS = ["Dictionary (hash map)", "Stack", "Queue", "Set", "Đồ thị (BFS/DFS)", "Cây (đệ quy)", "List"];
const zSc = [
  ["Tìm khách hàng theo số điện thoại trong 10 triệu bản ghi, thật nhanh", 0], ["Chức năng hoàn tác (Undo) khi chỉnh sửa tài liệu", 1], ["Xử lý các yêu cầu gửi đến server theo đúng thứ tự đến", 2], ["Loại các email trùng khỏi danh sách gửi tin", 3], ["Hỏi hai người có quan hệ gián tiếp qua bạn bè không", 4], ["Tính tổng dung lượng của một thư mục lồng nhiều tầng", 5],
  ["Tra giá sản phẩm từ mã sản phẩm", 0], ["Kiểm tra dấu ngoặc trong một đoạn code có khớp không", 1], ["Hàng chờ in: tài liệu gửi trước in trước", 2], ["Kiểm tra mã giảm giá đã được dùng chưa", 3], ["Tìm đường đi ít trạm nhất giữa hai ga tàu", 4], ["Mục lục sách có chương, mục, tiểu mục", 5],
  ["Đếm số lần mỗi từ xuất hiện trong một văn bản dài", 0], ["Nút Back của trình duyệt", 1], ["Phân việc cho nhân viên theo lượt, ai đến trước phục vụ trước", 2]];
const zScTrap = [["Một 'hàng đợi' đĩa bẩn chồng lên nhau: luôn lấy cái ở TRÊN cùng ra rửa trước", 1], ["Một 'danh sách' mã đơn hàng chỉ cần biết mã đã xử lý hay chưa, không bao giờ có hai mã giống nhau", 3], ["Một 'bảng' tra tên viết tắt ra tên đầy đủ", 0], ["Một 'hàng' người nhưng quy định người đến SAU được phục vụ trước", 1], ["Xếp hàng ở quầy: ai đến trước được phục vụ trước", 2]];
PRB.ap6 = {
  same: () => { const s = aPick(zSc.slice(0, 6)); return fC(`Yêu cầu: ${s[0]}. Nên dùng gì?`, [zDS[s[1]], ...pShuf(zDS.filter((_, i) => i != s[1])).slice(0, 2)], `Đây là bài toán của ${zDS[s[1]]}.`) },
  flip: () => { const d = aPick([0, 1, 2, 3, 4, 5]), good = aPick(zSc.filter(x => x[1] == d)), bad = pShuf(zSc.filter(x => x[1] != d)).slice(0, 2); return fC(`${zDS[d]} phù hợp nhất cho tình huống nào?`, [good[0], ...bad.map(x => x[0])], `${zDS[d]} sinh ra cho đúng kiểu việc này.`) },
  new: () => { const s = aPick(zSc.slice(6)); return fC(`Yêu cầu: ${s[0]}. Nên dùng gì?`, [zDS[s[1]], ...pShuf(zDS.filter((_, i) => i != s[1])).slice(0, 2)], `Đây là bài toán của ${zDS[s[1]]}.`) },
  verdict: KV("Hà nói: 'dùng list cho mọi thứ là đủ và luôn tốt nhất'. Hà nói đúng hay sai?", "Hà nói: 'cùng một dữ liệu, chọn cấu trúc khác nhau cho tốc độ tra cứu khác hẳn'. Hà nói đúng hay sai?", "Mỗi cấu trúc mạnh ở một loại thao tác", "List tốt nhất cho mọi việc", "Cấu trúc không ảnh hưởng tốc độ", "Sai: chọn đúng cấu trúc quyết định tốc độ."),
  read: () => { const s = aPick(zScTrap); return fC(`Đọc kỹ cách hoạt động, đừng chỉ nhìn tên gọi: ${s[0]}. Cấu trúc nào khớp?`, [zDS[s[1]], ...pShuf(zDS.filter((_, i) => i != s[1])).slice(0, 2)], `Điều quyết định là hành vi thật (${zDS[s[1]]}), không phải từ ngữ trong mô tả.`) }
};
bank("ap6", "verdict", [KV("Nam nói: 'chọn cấu trúc dữ liệu nên chọn theo cái mình quen nhất'. Nam nói đúng hay sai?", "Nam nói: 'nên chọn cấu trúc dữ liệu theo thao tác chính mà bài toán cần'. Nam nói đúng hay sai?", "Thao tác chính quyết định cấu trúc phù hợp", "Cái quen nhất luôn đúng", "Cấu trúc nào cũng như nhau", "Sai: chọn theo thao tác cần làm.")]);
bank("ap6", "read", [() => { const s = aPick(zScTrap.filter(x => x[1] != 2)); return fC(`Đề viết: ${s[0]}. Nếu chọn sai cấu trúc, rủi ro lớn nhất là gì?`, ["Hành vi sai so với yêu cầu hoặc quá chậm khi dữ liệu lớn", "Chương trình đổi màu", "Không có rủi ro"], "Cấu trúc sai thì thao tác chính hoặc chậm hoặc sai thứ tự.") }]);

/* ===== xưởng ghép b1-b6 ===== */
PRB.b1 = {
  same: () => { const v = aPick(["x", "y", "kq", "dem"]), n = fR(2, 9); return zSyn(fC(`Dòng nào Python hiểu là "bỏ số ${n} vào hộp tên ${v}"?`, [`${v} = ${n}`, `${n} = ${v}`, `${v} ${n} =`], "Tên hộp bên trái, dấu =, giá trị bên phải."), [[`${v} = ${n}`, true], [`${n} = ${v}`, false], [`${v} ${n} =`, false]]) },
  flip: () => { const k = fR(2, 9); return fC(`Đọc dòng "y = x + ${k}" bằng lời:`, [`Lấy x cộng ${k}, bỏ kết quả vào hộp y`, `Lấy y cộng ${k}, bỏ kết quả vào hộp x`, `So sánh y với x cộng ${k}`], "Bên phải được tính trước, rồi bỏ vào hộp tên ở bên trái.") },
  new: () => { const k = fR(2, 9); return zSyn(fC(`Dòng nào làm hộp x TĂNG thêm ${k} (lấy x cộng ${k}, bỏ lại vào chính hộp x)?`, [`x = x + ${k}`, `x + ${k} = x`, `${k} = x + x`], "Tên hộp nhận kết quả đứng bên trái dấu =."), [[`x = x + ${k}`, true], [`x + ${k} = x`, false], [`${k} = x + x`, false]]) },
  verdict: KV("Hà nói: 'x = x + 1 vô lý vì x không thể bằng chính nó cộng 1'. Hà nói đúng hay sai?", "Hà nói: 'x = x + 1 nghĩa là lấy x cộng 1 rồi bỏ lại vào hộp x'. Hà nói đúng hay sai?", "Dấu = trong Python là bỏ vào hộp, không phải so sánh bằng nhau", "Dấu = luôn là so sánh", "Python không cho phép", "Sai: = là phép gán."),
  read: () => zSyn(fC("Dòng nào KHÔNG gây SyntaxError?", ["print(x)", "print(x", "print x)"], "Mỗi ngoặc mở cần một ngoặc đóng, và ngoặc mở đứng ngay sau print."), [["print(x)", true], ["print(x", false], ["print x)", false]])
};
bank("b1", "read", [() => fC('Muốn in GIÁ TRỊ trong hộp x (không phải chữ x). Chọn dòng đúng:', ["print(x)", 'print("x")', "Print(x)"], 'Ngoặc kép biến x thành chữ. Và Python phân biệt chữ hoa chữ thường: print, không phải Print.')]);
PRB.b2 = {
  same: () => { const k = fR(2, 9); return zSyn(fC(`Dòng viết đúng cho "nếu n lớn hơn ${k} thì":`, [`if n > ${k}:`, `if n > ${k}`, `n > ${k}: if`], "Dòng if luôn bắt đầu bằng if và kết thúc bằng dấu hai chấm."), [[`if n > ${k}:\n    pass`, true], [`if n > ${k}\n    pass`, false], [`n > ${k}: if\n    pass`, false]]) },
  flip: () => { const k = fR(2, 9); return fC(`Đọc dòng "if n > ${k}:" bằng lời:`, [`Nếu n lớn hơn ${k} thì (làm các dòng thụt vào bên dưới)`, `Gán ${k} cho n`, `In n khi n bằng ${k}`], "Dòng if đặt câu hỏi; các dòng thụt vào là việc làm khi câu trả lời là đúng.") },
  new: () => { const v = fR(1, 9), k = fR(1, 9), r = v > k ? "A" : "B", c = `n = ${v}\nif n > ${k}:\n    print("A")\nelse:\n    print("B")`; return aPy(fC(`${fPre(c)}Màn hình in ra gì?`, [r, r == "A" ? "B" : "A", "A rồi B"], v > k ? `${v} > ${k} đúng: vế if.` : `${v} > ${k} sai: vế else.`), c, [r]) },
  verdict: KV("Hà nói: 'thụt dòng chỉ để cho đẹp mắt, bỏ đi Python vẫn hiểu như cũ'. Hà nói đúng hay sai?", "Hà nói: 'thụt dòng cho Python biết dòng nào thuộc khối nào'. Hà nói đúng hay sai?", "Độ thụt là một phần của cú pháp", "Thụt chỉ để đẹp", "Python bỏ qua khoảng trắng", "Sai: thụt dòng quyết định dòng nào thuộc if."),
  read: () => aPy(fC(`${fPre('print("A")\nif 3 > 1\n    print("B")')}Dòng if thiếu dấu hai chấm. Chạy chương trình thì sao?`, ["Không in gì cả: Python báo SyntaxError trước khi chạy bất kỳ dòng nào", 'In A rồi mới báo lỗi', 'In A rồi B'], "Python đọc cả chương trình trước; lỗi cú pháp ở bất kỳ đâu thì không dòng nào được chạy."), 'print("A")\nif 3 > 1\n    print("B")', [], "SyntaxError")
};
bank("b2", "read", [() => { const k = fR(1, 4); return zSyn(fC("Dòng else: đặt ở đâu so với dòng if tương ứng?", ["Thẳng hàng với if (cùng độ thụt)", "Thụt vào bên trong khối if", "Thụt vào sâu hơn một cấp nữa"], "if và else là hai vế của cùng một câu hỏi nên cùng cấp."), [["if 1 > 2:\n    pass\nelse:\n    pass", true], ["if 1 > 2:\n    pass\n    else:\n        pass", false]]) }]);
PRB.b3 = {
  same: () => { const n = fR(2, 6); return zSyn(fC(`Dòng viết đúng cho "lặp ${n} lần, mỗi lần gọi số hiện tại là i":`, [`for i in range(${n}):`, `for i range(${n}):`, `for i in range ${n}:`], "for, tên biến, in, range(số lần), dấu hai chấm."), [[`for i in range(${n}):\n    pass`, true], [`for i range(${n}):\n    pass`, false], [`for i in range ${n}:\n    pass`, false]]) },
  flip: () => { const n = fR(3, 9); return fT(`Dòng "for i in range(${n}):" làm khối thụt vào bên dưới chạy mấy lần?`, n, `range(${n}) cho ${n} số: 0 đến ${n - 1}.`) },
  new: () => { const n = fR(3, 6), c = `for i in range(${n}):\n    total = 0\n    total = total + i\nprint(total)`; return aPy(fT(`${fPre(c)}total = 0 nằm TRONG vòng for. In ra số mấy?`, n - 1, `Mỗi vòng đặt total về 0 rồi cộng i, nên mất tổng cũ. Vòng cuối i = ${n - 1}.`), c, [String(n - 1)]) },
  verdict: KV("Hà nói: 'total = 0 đặt trong vòng for cũng cho tổng đúng'. Hà nói đúng hay sai?", "Hà nói: 'total = 0 phải đặt trước vòng for, nếu không mỗi vòng đặt lại về 0'. Hà nói đúng hay sai?", "Việc chuẩn bị làm một lần trước khi lặp", "Đặt đâu cũng được", "Python tự nhớ tổng", "Sai: đặt trong vòng thì mất tổng đã cộng."),
  read: () => { const n = fR(3, 5), c = `total = 0\nfor i in range(${n}):\n    total = total + i\n    print(total)`; return aPy(aNum(`${fPre(c)}Đọc kỹ chỗ thụt của print. Dòng ĐẦU TIÊN in ra số mấy?`, 0, `print nằm trong vòng lặp, vòng đầu i = 0 nên total = 0 rồi in ngay.`, [(n - 1) * n / 2, n]), c, Array.from({ length: n }, (_, i) => String(i * (i + 1) / 2))) }
};
bank("b3", "read", [() => { const n = fR(3, 5), c = `total = 0\nfor i in range(${n}):\n    total = total + i\nprint(total)`, s = n * (n - 1) / 2; return aPy(aNum(`${fPre(c)}print không thụt vào. Có bao nhiêu DÒNG được in ra, và dòng đó là số mấy? Chọn số được in.`, s, `print chạy một lần sau vòng lặp, in tổng ${s}.`, [0, n - 1]), c, [String(s)]) }]);
PRB.b4 = {
  same: () => { const f = aPick(["gap_doi", "tinh", "nhan"]); return zSyn(fC(`Dòng viết đúng để "tạo hàm tên ${f}, nhận vào x":`, [`def ${f}(x):`, `${f} def(x):`, `def ${f} x:`], "def, tên hàm, ngoặc chứa đầu vào, dấu hai chấm."), [[`def ${f}(x):\n    pass`, true], [`${f} def(x):\n    pass`, false], [`def ${f} x:\n    pass`, false]]) },
  flip: () => { const k = fR(2, 5); return fC(`Dòng "return x * ${k}" nghĩa là gì?`, [`Trả kết quả x nhân ${k} ra cho nơi đã gọi hàm`, `In x nhân ${k} ra màn hình`, `Gán ${k} cho x`], "return đưa kết quả về cho người gọi, khác với print (in ra màn hình).") },
  new: () => { const k = fR(2, 5), v = fR(2, 9), c = `def gap(x):\n    return x * ${k}\nprint(gap(${v}))`; return aPy(fT(`${fPre(c)}In ra số mấy?`, k * v, `gap(${v}) = ${v} x ${k}.`), c, [String(k * v)]) },
  verdict: KV("Hà nói: 'dòng print(gap_doi(4)) phải thụt vào vì nó dùng hàm'. Hà nói đúng hay sai?", "Hà nói: 'dòng gọi hàm nằm ngoài hàm nên không thụt vào'. Hà nói đúng hay sai?", "Chỉ phần định nghĩa hàm mới thụt vào", "Mọi dòng liên quan đều thụt", "Thụt tùy ý", "Sai: gọi hàm nằm ngoài hàm."),
  read: () => aPy(fC(`${fPre("print(f(3))\ndef f(x):\n    return x * 2")}Gọi hàm TRƯỚC khi tạo nó. Chuyện gì xảy ra?`, ["Báo NameError: lúc gọi f, Python chưa biết f", "In 6", "In None"], "Python chạy từ trên xuống: phải tạo hàm trước rồi mới gọi."), "print(f(3))\ndef f(x):\n    return x * 2", [], "NameError")
};
bank("b4", "read", [() => { const a = fR(2, 5), c = `def g(x):\n    print(x)\ny = g(${a})\nprint(y)`; return aPy(fC(`${fPre(c)}Hàm g chỉ print, không return. Hai dòng in ra là gì?`, [`${a} rồi None`, `${a} rồi ${a}`, `None rồi ${a}`], "Không có return thì hàm trả về None."), c, [String(a), "None"]) }]);
PRB.b5 = {
  same: () => { const i = fR(0, 3); return zSyn(fC(`Viết "lấy hộp số ${i} của hàng hộp a":`, [`a[${i}]`, `[${i}]a`, `a[${i}`], "Tên hàng hộp, rồi chỉ số trong ngoặc vuông."), [[`a[${i}]`, true], [`[${i}]a`, false], [`a[${i}`, false]]) },
  flip: () => { const n = fR(3, 9); return fT(`Mảng a có ${n} hộp. len(a) trả về mấy?`, n, `len đếm số hộp: ${n}. Chỉ số cuối là ${n - 1}.`) },
  new: () => { const a = xArr(fR(3, 5), 1, 9), c = `a = ${pJ(a)}\nfor i in range(len(a)):\n    last = i\nprint(last)`; return aPy(fT(`${fPre(c)}In ra số mấy?`, a.length - 1, `i là SỐ THỨ TỰ của hộp, đi từ 0 đến ${a.length - 1}.`), c, [String(a.length - 1)]) },
  verdict: KV("Hà nói: 'for x in a cho ra số thứ tự của từng hộp'. Hà nói đúng hay sai?", "Hà nói: 'for x in a cho ra chính giá trị trong từng hộp'. Hà nói đúng hay sai?", "x là giá trị, còn i trong range(len(a)) mới là chỉ số", "x là chỉ số", "x luôn là 0", "Sai: x là giá trị."),
  read: () => { const i = fR(0, 2); return zSyn(fC(`Dòng nào BỎ số 9 vào hộp số ${i} của a?`, [`a[${i}] = 9`, `a[${i}] == 9`, `a(${i}) = 9`], "= là bỏ vào (gán), == là hỏi có bằng nhau không. Và hộp dùng ngoặc vuông."), [[`a = [1, 2, 3]\na[${i}] = 9`, true], [`a(${i}) = 9`, false]]) }
};
bank("b5", "new", [() => { const a = xArr(fR(3, 5), 1, 9), c = `a = ${pJ(a)}\nfor x in a:\n    last = x\nprint(last)`; return aPy(fT(`${fPre(c)}In ra số mấy?`, a[a.length - 1], `x là chính giá trị trong từng hộp; vòng cuối x = ${a[a.length - 1]}.`), c, [String(a[a.length - 1])]) }]);
const zMax = (n, v) => `def find_${n}(nums):\n    best = nums[0]\n    for x in nums:\n        if x ${v} best:\n            best = x\n    return best\n`;
PRB.b6 = {
  same: () => { const mx = Math.random() < 0.5, n = mx ? "max" : "min", op = mx ? ">" : "<"; return fC(`${fPre(`def find_${n}(nums):\n    best = nums[0]\n    for x in nums:`)}Hàm tìm số ${mx ? "LỚN" : "NHỎ"} nhất đang viết dở. Dòng TIẾP THEO (thụt thêm 4 dấu cách) là gì?`, [`if x ${op} best:`, "return best", `def find_${n}(nums):`], `Trong vòng lặp ta so từng x với best. ${mx ? "Lớn" : "Nhỏ"} hơn thì thay.`) },
  flip: () => { const c = zMax("max", ">") + zMax("max", ">").replace("find_max", "bad").replace("    return best\n", "        return best\n") + "print(find_max([3, 9, 2]), bad([3, 9, 2]))"; return aPy(fC("Dòng return best thụt vào TRONG vòng for (cùng độ thụt với if) thay vì thẳng hàng với for. Hàm trả về gì với [3, 9, 2]?", ["3: return chạy ngay ở vòng đầu rồi hàm kết thúc", "9 như bình thường", "2"], "return nằm trong vòng lặp thì kết thúc hàm ngay ở lần lặp đầu tiên."), c, ["9 3"]) },
  new: () => { const c = "def sum_all(nums):\n    total = 0\n    for x in nums:\n        total = total + x\n    return total\nprint(sum_all([1, 2, 3]))"; return aPy(fC(`${fPre("def sum_all(nums):\n    total = 0\n    for x in nums:\n        total = total + x\n    return total")}Dòng nào đứng ngay TRƯỚC dòng for x in nums:?`, ["total = 0", "return total", "total = total + x"], "Chuẩn bị tờ giấy ghi tổng trước khi lặp, đúng như best = nums[0] trong find_max."), c, ["6"]) },
  verdict: KV("Hà nói: 'best = nums[0] đặt sau vòng for cũng được'. Hà nói đúng hay sai?", "Hà nói: 'best = nums[0] phải đứng trước vòng for vì vòng for cần so với best'. Hà nói đúng hay sai?", "Phải có tờ giấy trước khi so", "Thứ tự không quan trọng", "best tự có", "Sai: chưa có best thì không thể so."),
  read: () => { const a = pDistinct(4, 9); let nums = a; if (Math.max(...nums) == nums[3]) nums = [nums[3], nums[0], nums[1], nums[2]]; const last = nums[3], mx = Math.max(...nums), c = `def find_max(nums):\n    best = nums[0]\n    for x in nums:\n        if x > best:\n        best = x\n    return best`, c2 = `def find_max(nums):\n    best = nums[0]\n    for x in nums:\n        if x > best:\n            pass\n        best = x\n    return best\nprint(find_max(${pJ(nums)}))`; return aPy(aNum(`${fPre(`def find_max(nums):\n    best = nums[0]\n    for x in nums:\n        if x > best:\n            pass\n        best = x\n    return best\nprint(find_max(${pJ(nums)}))`)}Dòng best = x không thụt vào trong if. In ra số mấy?`, last, `best = x chạy ở MỌI vòng, nên cuối cùng best là phần tử cuối (${last}), không phải số lớn nhất (${mx}).`, [mx, nums[0]]), c2, [String(last)]) }
};
bank("b6", "new", [() => { const mx = Math.random() < 0.5, n = mx ? "max" : "min", op = mx ? ">" : "<"; return fC(`Hàm tìm số ${mx ? "lớn" : "nhỏ"} nhất, đang viết dở:${fPre(`def find_${n}(nums):\n    best = nums[0]\n    for x in nums:\n        if x ${op} best:\n            best = x`)}Dòng cuối cùng của hàm là gì, và nó thụt vào đâu?`, ["return best, thẳng hàng với for (ngoài vòng lặp)", "return best, thụt vào trong if", "return x, thụt vào trong vòng for"], "Chỉ trả kết quả sau khi xem hết các hộp, nên return nằm ngoài vòng lặp.") }]);

Object.assign(PREQ, { b1: ["p1"], b2: ["p2", "b1"], b3: ["p3", "b2"], b4: ["p4", "b3"], b5: ["a3", "b3"], b6: ["b5", "b4", "l3", "sm"], m1: ["d2", "e4"], m2: ["m1"], m3: ["m2", "e3"], rl1: ["que", "m2"], ap1: ["d2", "h3"], ap2: ["que"], ap3: ["stk"], ap4: ["g2", "g1"], ap5: ["t2"], ap6: ["ap1", "ap2", "ap3", "ap4", "ap5"] });
