/* Ngân hàng mẫu bổ sung cho các bài cũ chỉ có 1 mẫu (que, bs, k2, k5, k8, k9, tp, bub, h1, h2, h3).
   Nạp sau probe-adv.js (dùng aPy, aNum, aStr, aInt, bubPass, others). Mọi mẫu sinh ngẫu nhiên, có đáp án tính bằng code. */
const xSort = a => a.slice().sort((x, y) => x - y);

/* que: hàng đợi */
bank("que", "new", [() => { const n = pDistinct(3, 9), c = aPick([0, 1]); const who = n.map(x => aNm[x % aNm.length]); const names = pShuf(aNm).slice(0, 3); return fC(`Ở quầy vé, ${names[0]}, ${names[1]}, ${names[2]} xếp hàng theo đúng thứ tự đó (${names[0]} đứng đầu). Người mới đến phải xếp ở đâu, và ai được phục vụ trước?`, [`Người mới xếp cuối hàng; ${names[0]} được phục vụ trước`, `Người mới xếp đầu hàng; ${names[2]} được phục vụ trước`, `Người mới xếp cuối hàng; ${names[2]} được phục vụ trước`], "Queue: vào ở cuối, ra ở đầu (vào trước, ra trước).") }, () => { const k = fR(3, 7), m = fR(1, k - 1); return fT(`Hàng đợi đang có ${k} người. Phục vụ xong ${m} người (mỗi lần lấy người ở đầu hàng), và không ai mới đến. Còn mấy người trong hàng?`, k - m, `${k} - ${m} = ${k - m}.`) }]);
bank("que", "read", [() => { let a, ops, front, q; do { const v = pDistinct(6, 9); q = []; ops = []; let i = 0, removed = []; ops.push(`enqueue(${v[i]})`); q.push(v[i++]); ops.push(`enqueue(${v[i]})`); q.push(v[i++]); ops.push("dequeue()"); removed.push(q.shift()); ops.push(`enqueue(${v[i]})`); q.push(v[i++]); ops.push(`enqueue(${v[i]})`); q.push(v[i++]); front = q[0]; a = [front, q[q.length - 1], removed[0]] } while (new Set(a).size < 3); return fC(`${ops.join(", ")}. Phần tử sẽ ra TIẾP THEO (lần dequeue kế tiếp) là gì?`, a.map(String), `Hàng đợi hiện còn ${q.join(", ")} (đầu hàng là ${front}). Ra trước là người đứng đầu, không phải người vào cuối.`) }]);

/* bs: tìm nhị phân */
bank("bs", "new", [() => { const m = fR(2, 4), n = 2 ** m, k = fR(1, m - 1); return fT(`Mỗi lần so sánh loại bỏ đúng một nửa số hộp. Từ ${n} hộp, sau ${k} lần so sánh còn mấy hộp?`, n / 2 ** k, `${n} chia 2, ${k} lần: ${n / 2 ** k}.`) }, () => { const m = fR(3, 10); return fT(`Có ${2 ** m} hộp. Cần chia đôi tối thiểu mấy lần để chỉ còn đúng 1 hộp?`, m, `2^${m} = ${2 ** m}: chia đôi ${m} lần thì còn 1.`) }]);
bank("bs", "read", [() => { const a = xSort(pDistinct(7, 30)), mid = a[3]; const t = Math.random() < 0.25 ? mid : aPick(a.filter(x => x != mid)), L = `Bỏ nửa TRÁI (${t} lớn hơn ${mid})`, R = `Bỏ nửa PHẢI (${t} nhỏ hơn ${mid})`, F = `Dừng: hộp giữa ${mid} chính là số cần tìm`, right = t == mid ? F : t > mid ? L : R; return fC(`Mảng ${pJ(a)} đã sắp xếp. Tìm ${t}. Hộp giữa (chỉ số 3) chứa ${mid}. Bước tiếp theo là gì?`, [right, ...[L, R, F].filter(x => x != right)], t == mid ? "Gặp đúng số cần tìm thì dừng." : t > mid ? "Mảng tăng dần: số lớn hơn hộp giữa chỉ có thể nằm bên phải." : "Mảng tăng dần: số nhỏ hơn hộp giữa chỉ có thể nằm bên trái.") }, () => { let a, sorted; do { a = pDistinct(6, 30); sorted = JSON.stringify(a) == JSON.stringify(xSort(a)) } while (sorted && false); const ok = Math.random() < 0.5; if (!ok) { do { a = pShuf(a) } while (JSON.stringify(a) == JSON.stringify(xSort(a))) } else a = xSort(a); const Y = "Dùng được: mảng đã sắp xếp", N = "Chưa dùng được: mảng chưa sắp xếp, phải sắp xếp trước (hoặc tìm tuần tự)", D = "Dùng được với mọi mảng"; return fC(`Mảng ${pJ(a)}. Có thể áp dụng ngay tìm nhị phân (chia đôi) để tìm một số không?`, ok ? [Y, N, D] : [N, Y, D], ok ? "Tìm nhị phân cần mảng đã sắp xếp, và mảng này đã đúng thứ tự." : "Chia đôi chỉ đúng khi mảng có thứ tự, nếu không bỏ nửa nào cũng có thể bỏ mất số cần tìm.") }]);

/* k2: so sánh nhiều hơn / ít hơn / bằng */
bank("k2", "new", [() => { const a = fR(2, 9), b = Math.random() < 0.3 ? a : fR(2, 9), r = a > b ? "Hà" : a < b ? "Nam" : "Bằng nhau"; return fC(`Hà có ${a} viên bi, Nam có ${b} viên bi. Ai có NHIỀU bi hơn?`, [r, ...["Hà", "Nam", "Bằng nhau"].filter(x => x != r)], a == b ? "Hai số bằng nhau thì không ai nhiều hơn." : "Số lớn hơn là nhiều hơn.") }]);

/* k5: máy chỉ làm đúng từng lệnh */
bank("k5", "new", [() => { const x = fR(5, 9), a = fR(1, 4), b = fR(1, 4), c = fR(1, 4); return fT(`Hộp chứa ${x}. Lệnh 1: lấy ra ${a}. Lệnh 2: bỏ thêm ${b}. Lệnh 3: bỏ thêm ${c}. Sau lệnh 3 hộp chứa mấy?`, x - a + b + c, `${x} - ${a} + ${b} + ${c} = ${x - a + b + c}.`) }]);
bank("k5", "read", [() => { const x = fR(3, 6), a = fR(2, 4), b = fR(1, 2); return aNum(`Hộp chứa ${x}. Lệnh 1: bỏ thêm ${a}. Lệnh 2: lấy ra ${b}. NGAY SAU lệnh 1 (lệnh 2 chưa chạy), hộp chứa mấy?`, x + a, `Mới chạy lệnh 1: ${x} + ${a} = ${x + a}. ${x + a - b} là kết quả sau lệnh 2.`, [x + a - b, x]) }]);

/* k8: tìm quy luật */
bank("k8", "new", [() => { const s = fR(2, 4), a = fR(14, 20); return fT(`Dãy số đang GIẢM dần: ${a}, ${a - s}, ${a - 2 * s}, ${a - 3 * s}, ?  Số tiếp theo là mấy?`, a - 4 * s, `Mỗi số kém số trước ${s}.`) }]);
bank("k8", "read", [() => { const E = pShuf(["🔴", "🔵", "⭐", "🌙", "🍎", "🍌"]).slice(0, 2), tri = aPick([[E[0], E[1], E[1]], [E[0], E[0], E[1]]]), L = aPick([7, 8, 10]), seq = Array.from({ length: L }, (_, i) => tri[i % 3]), nx = tri[L % 3]; return fC(`${seq.join(" ")} ?  Hình tiếp theo là gì?`, [nx, ...E.filter(x => x != nx), "Không đoán được"].slice(0, 3), `Cứ ${tri.join(" ")} lặp lại: đây là quy luật lặp sau mỗi 3 hình, hình thứ ${L + 1} là ${nx}.`) }]);

/* k9: biến và print */
bank("k9", "new", [() => { const a = fR(1, 9), b = fR(1, 9), c = `x = ${a}\ny = ${b}\nx = y\nprint(x)`; return aPy(fT(`${fPre(c)}Máy in ra số mấy?`, b, `Dòng x = y đặt hộp x chứa giá trị của y: ${b}.`), c, [String(b)]) }, () => { const a = fR(1, 9), b = fR(1, 9), c = `x = ${a}\nx = x + ${b}\nprint(x)`; return aPy(fT(`${fPre(c)}Máy in ra số mấy?`, a + b, `Lấy ${a} trong hộp x, cộng ${b}, bỏ lại vào x: ${a + b}.`), c, [String(a + b)]) }]);
bank("k9", "read", [() => { const a = fR(1, 5), b = fR(6, 9), c = `x = ${a}\nx = ${b}\nprint(x)`; return aPy(aNum(`${fPre(c)}Đọc kỹ từng lệnh. Máy in ra số mấy?`, b, `Lệnh sau ghi đè lệnh trước: x chứa ${b}. ${a} đã bị thay thế.`, [a, a + b]), c, [String(b)]) }]);

/* tp: hai con trỏ */
bank("tp", "new", [() => { const a = pDistinct(4, 9), c = `a = ${pJ(a)}\ni = 1\nj = 2\na[i], a[j] = a[j], a[i]\nprint(a[j])`; return aPy(fT(`Hai hộp ở giữa đổi chỗ cho nhau.${fPre(c)}Sau khi đổi, hộp j chứa số mấy?`, a[1], `Hai hộp 1 và 2 đổi chỗ cho nhau: hộp 2 giờ chứa số cũ của hộp 1, tức ${a[1]}.`), c, [String(a[1])]) }]);
bank("tp", "read", [() => { const n = fR(5, 9), k = fR(1, 3), R = `i = ${k}, j = ${n - 1 - k}`; return fC(`Mảng có ${n} hộp. Ban đầu i = 0, j = ${n - 1}. Sau ${k} bước (mỗi bước i tăng 1, j giảm 1) thì i và j bằng bao nhiêu?`, [R, `i = ${k}, j = ${n - k}`, `i = 0, j = ${n - 1 - k}`], `i: 0 thành ${k}; j: ${n - 1} thành ${n - 1 - k}.`) }]);

/* bub: nổi bọt */
bank("bub", "new", [() => { const a = pDistinct(3, 9), p = bubPass(a); return fT(`${fPre(`a = ${pJ(a)}  # một lượt nổi bọt: so sánh cặp (0,1), rồi (1,2), nếu trái lớn hơn phải thì đổi chỗ`)}Sau một lượt, hộp CUỐI CÙNG chứa số mấy?`, p[2], `Số lớn nhất nổi dần về cuối: ${p[2]}.`) }]);
bank("bub", "read", [() => { const a = pDistinct(3, 9), sw = a.slice(); if (sw[0] > sw[1]) [sw[0], sw[1]] = [sw[1], sw[0]]; const forced = a.slice(); [forced[0], forced[1]] = [forced[1], forced[0]]; const cand = [...new Set([pJ(sw), pJ(a), pJ(forced), pJ(xSort(a)), pJ(a.slice().reverse())])], right = pJ(sw); return fC(`a = ${pJ(a)}. So sánh hai hộp đầu: ${a[0]} ${a[0] > a[1] ? ">" : "<"} ${a[1]}. Làm đúng quy tắc (trái lớn hơn phải thì đổi chỗ). Ngay bây giờ mảng là gì?`, [right, ...cand.filter(x => x != right).slice(0, 2)], a[0] > a[1] ? "Trái lớn hơn phải nên đổi chỗ; mới xử lý một cặp." : "Trái nhỏ hơn phải nên KHÔNG đổi chỗ; mảng giữ nguyên.") }]);

/* h1, h2: dictionary */
bank("h1", "new", [() => { const a = fR(10, 20), b = fR(10, 20), c = `tuoi = {"An": ${a}}\ntuoi["Binh"] = ${b}\nprint(tuoi["An"] + tuoi["Binh"])`; return aPy(fT(`${fPre(c)}In ra số mấy?`, a + b, `Thêm khóa "Binh", rồi cộng hai giá trị: ${a + b}.`), c, [String(a + b)]) }]);
bank("h1", "read", [() => { const a = fR(1, 5), b = fR(6, 9), c = `d = {"a": ${a}}\nd["a"] = ${b}\nprint(d["a"])`; return aPy(aNum(`${fPre(c)}Đọc kỹ: in ra mấy?`, b, `Gán vào khóa đã có thì GHI ĐÈ giá trị cũ: ${b}.`, [a, a + b]), c, [String(b)]) }]);
bank("h2", "read", [() => { const c = `d = {}\nprint(d.get("x", 0))`; return aPy(fC(`${fPre(c)}Chuyện gì xảy ra?`, ["In ra 0", "Báo lỗi KeyError", "In ra None"], "get trả về giá trị mặc định (0) khi chưa có khóa, không báo lỗi."), c, ["0"]) }]);

/* h3: khi nào dùng dictionary/set */
bank("h3", "new", [() => fC("Muốn đếm xem mỗi từ xuất hiện bao nhiêu lần trong 1 triệu từ, nên dùng gì?", ["Dictionary: khóa là từ, giá trị là số lần", "List các cặp, mỗi lần tìm lại từ đầu", "Set (không lưu được số lần)"], "Dictionary vừa tra nhanh vừa lưu được số đếm."), () => fC("Cần kiểm tra 'mã đơn hàng này đã xử lý chưa' cho hàng triệu đơn, nhanh nhất là dùng gì?", ["Set các mã đã xử lý", "List các mã, duyệt từng phần tử", "Sắp xếp lại list mỗi lần"], "Set tra gần như một bước, không phụ thuộc số lượng.")]);
bank("h3", "read", [() => { const n = aPick([50, 200, 1000]); return fC(`Chỉ cần tra ĐÚNG MỘT lần trong một list có sẵn ${n} phần tử. Có đáng dựng dictionary rồi mới tra không?`, ["Không: dựng dictionary cũng phải duyệt n phần tử, không lợi cho một lần tra", "Có, dictionary luôn nhanh hơn", "Có, vì list không tra được"], "Dựng bảng băm tốn cỡ n bước. Chỉ có lợi khi tra nhiều lần.") }]);

/* d2: đếm bằng dictionary; stk: stack */
bank("d2", "new", [() => { const w = aPick(["banana", "mama", "abba", "aabca"]), c = `d = {}\nfor ch in "${w}":\n    d[ch] = d.get(ch, 0) + 1\nprint(d["a"])`; return aPy(fT(`${fPre(c)}In ra số mấy?`, [...w].filter(x => x == "a").length, `Đếm chữ "a" trong "${w}".`), c, [String([...w].filter(x => x == "a").length)]) }]);
bank("d2", "read", [() => { const seq = Array.from({ length: fR(3, 5) }, () => aPick(["a", "b"])); if (!seq.includes("a")) seq[0] = "a"; const na = seq.filter(x => x == "a").length, nb = seq.length - na, c = "d = {}\n" + seq.map(x => `d["${x}"] = d.get("${x}", 0) + 1`).join("\n") + "\nprint(d[\"a\"])"; return aPy(aNum(`${fPre(c)}Đọc kỹ: d["a"] (không phải d["b"]) bằng mấy?`, na, `Chỉ các dòng có khóa "a" mới cộng vào d["a"]: ${na} lần. Còn ${nb} dòng thuộc khóa "b".`, [seq.length, nb]), c, [String(na)]) }]);
bank("stk", "new", [() => { const n = fR(3, 4), L = ["A", "B", "C", "D"].slice(0, n), k = fR(1, n - 1), gone = L[n - k]; return fC(`Soạn văn bản: gõ lần lượt ${L.map(x => `"${x}"`).join(", ")}. Bấm Undo ${k} lần. Thao tác ${k > 1 ? "CUỐI CÙNG bị hoàn tác (lần Undo thứ " + k + ")" : "bị hoàn tác"} là gõ chữ nào?`, [`"${gone}"`, ...L.filter(x => x != gone).slice(0, 2).map(x => `"${x}"`)], "Undo hoàn tác thao tác gần nhất trước: vào sau, ra trước (stack).") }]);
bank("stk", "read", [() => { let a, top, popped, bottom, st, ops; do { const v = pDistinct(5, 9); st = []; ops = []; ops.push(`push(${v[0]})`); st.push(v[0]); ops.push(`push(${v[1]})`); st.push(v[1]); ops.push(`push(${v[2]})`); st.push(v[2]); ops.push("pop()"); popped = st.pop(); ops.push(`push(${v[3]})`); st.push(v[3]); top = st[st.length - 1]; bottom = st[0]; a = [top, popped, bottom] } while (new Set(a).size < 3); return fC(`${ops.join(", ")}. Bây giờ phần tử trên cùng của stack là gì?`, a.map(String), `Sau pop còn ${st.slice(0, -1).join(", ")}, rồi push ${top} nằm trên cùng. ${popped} đã bị lấy ra.`) }]);

/* d1: dictionary cơ bản */
bank("d1", "new", [() => { const a = fR(2, 9), b = fR(2, 9), k = aPick(["a", "b"]), c = `d = {"a": ${a}, "b": ${b}}\nprint(d["${k}"] * 2)`; return aPy(fT(`${fPre(c)}In ra số mấy?`, (k == "a" ? a : b) * 2, `d["${k}"] là ${k == "a" ? a : b}, nhân 2.`), c, [String((k == "a" ? a : b) * 2)]) }, () => { const a = fR(2, 9), c = `d = {"x": ${a}}\nprint(len(d))`; return aPy(fT(`${fPre(c)}In ra số mấy?`, 1, `len(d) đếm số MỤC (số khóa), không phải giá trị ${a}.`), c, ["1"]) }]);
bank("d1", "read", [() => { const a = fR(2, 9), b = fR(2, 9), c = `d = {"a": ${a}, "b": ${b}}\nprint(d["b"])`; return aPy(aNum(`${fPre(c)}Đọc kỹ: in ra giá trị ứng với khóa "b". Mấy?`, b, `Tra theo khóa, không theo thứ tự: d["b"] = ${b}.`, [a, a + b]), c, [String(b)]) }, () => { const a = fR(2, 9), c = `d = {"a": ${a}}\nprint(d[${a}])`; return aPy(fC(`${fPre(c)}Đọc kỹ dòng print (tra bằng số ${a}). Chuyện gì xảy ra?`, [`Báo lỗi KeyError: ${a} không phải khóa, khóa là "a"`, `In ra ${a}`, "In ra None"], `Khóa là chữ "a" (có nháy), còn ${a} là một giá trị. Tra theo ${a} thì không thấy.`), c, [], "KeyError") }]);

/* ===== Các bài nền: bx0, p1, p2, p3, sm, k3, k4, k6, k7, a2, a3, cn, p4 ===== */
const xArr = (n, lo, hi) => Array.from({ length: n }, () => fR(lo, hi));
bank("bx0", "new", [() => { const n = aPick(["z", "kq", "dem"]), v = fR(2, 9); return fC(`Trong Python, viết "bỏ số ${v} vào hộp tên ${n}":`, [`${n} = ${v}`, `${v} = ${n}`, `${n} ${v} =`], "Tên hộp bên trái, dấu =, giá trị bên phải.") }]);
bank("bx0", "read", [() => { const a = fR(1, 4), b = fR(1, 4); return fC(`Một bạn viết "${a} ${b} + = ${a + b}". Bạn ấy đã sai ở đâu?`, ["Kết quả đúng, nhưng thứ tự viết sai", "Thứ tự viết đúng, nhưng kết quả sai", "Cả hai đều đúng"], `${a} + ${b} thật sự bằng ${a + b}, nhưng cách viết phải là ${a} + ${b} = ${a + b}: đúng ý chưa chắc đúng cách viết.`) }]);
bank("p1", "new", [() => { const a = fR(1, 5), y = fR(1, 5), z = fR(6, 9), c = `a = ${a}\nb = a + ${y}\na = ${z}\nprint(b)`; return aPy(fT(`${fPre(c)}In ra số mấy?`, a + y, `b tính xong lúc a còn ${a}: ${a + y}. a đổi sau đó không làm b đổi.`), c, [String(a + y)]) }]);
bank("p1", "read", [() => { const a = fR(1, 4), b = fR(5, 9), c = `x = ${a}\ny = x\ny = ${b}\nprint(x)`; return aPy(aNum(`${fPre(c)}Đọc kỹ: in ra giá trị của x. Mấy?`, a, `x vẫn giữ ${a}. Chỉ hộp y bị đổi thành ${b}.`, [b, a + b]), c, [String(a)]) }]);
bank("p2", "new", [() => { const t = fR(3, 8), v = aPick([t - 1, t, t + 1]), r = v >= t ? "Lớn" : "Nhỏ"; return fC(`Luật: nếu tuổi >= ${t} thì "Lớn", nếu không thì "Nhỏ". Tuổi ${v} thì kết quả là gì?`, [r, ...["Lớn", "Nhỏ", "Không đủ thông tin"].filter(x => x != r)], v >= t ? `${v} >= ${t} đúng.` : `${v} >= ${t} sai.`) }]);
bank("p2", "read", [() => { const a = fR(1, 9), b = fR(1, 9), yes = a > b, c = `if ${a} > ${b}:\n    print("X")\nprint("Y")`, o = yes ? ["X", "Y"] : ["Y"]; return aPy(fC(`${fPre(c)}Dòng print("Y") không thụt vào. Màn hình in ra gì?`, yes ? ["X rồi Y", "Y", "X"] : ["Y", "X rồi Y", "X"], yes ? "Điều kiện đúng nên in X, rồi Y luôn chạy." : "Điều kiện sai nên bỏ qua X, nhưng Y không thuộc if nên vẫn chạy."), c, o) }]);
bank("p3", "new", [() => { const s = fR(0, 5), n = fR(2, 5), k = fR(2, 4), c = `t = ${s}\nfor i in range(${n}):\n    t = t + ${k}\nprint(t)`; return aPy(fT(`${fPre(c)}In ra số mấy?`, s + n * k, `Bắt đầu ${s}, lặp ${n} lần cộng ${k}: ${s + n * k}.`), c, [String(s + n * k)]) }]);
bank("p3", "verdict", [KV("Hà nói: 'range(5) cho ra các số 1, 2, 3, 4, 5'. Hà nói đúng hay sai?", "Hà nói: 'range(5) cho ra 0, 1, 2, 3, 4: năm số, bắt đầu từ 0'. Hà nói đúng hay sai?", "range(n) bắt đầu từ 0 và dừng trước n", "range(n) bắt đầu từ 1", "range(n) dừng ở n", "Sai: range(5) bắt đầu từ 0 và không có 5.")]);
bank("p3", "read", [() => { const n = fR(3, 6), c = `for i in range(${n}):\n    print(i)`; return aPy(aNum(`${fPre(c)}Dòng CUỐI CÙNG in ra số mấy?`, n - 1, `Các số in ra là 0 đến ${n - 1}; số ${n} không xuất hiện.`, [n, n + 1]), c, Array.from({ length: n }, (_, i) => String(i))) }]);
bank("sm", "new", [() => { const a = xArr(fR(3, 4), 1, 9), s = a.reduce((x, y) => x + y, 0), c = `a = ${pJ(a)}\nt = 0\nfor x in a:\n    t = t + x\nprint(t)`; return aPy(fT(`${fPre(c)}In ra số mấy?`, s, `${a.join(" + ")} = ${s}.`), c, [String(s)]) }]);
bank("sm", "read", [() => { let a; do { a = pDistinct(4, 9) } while (false); const c = `a = ${pJ(a)}\nt = 0\nfor x in a:\n    t = x\nprint(t)`, s = a.reduce((x, y) => x + y, 0); return aPy(fC(`${fPre(c)}Đọc kỹ dòng trong vòng lặp: nó là t = x chứ không phải t = t + x. In ra mấy?`, [String(a[3]), String(s), String(a[0])], `t bị ghi đè mỗi vòng, cuối cùng giữ phần tử cuối: ${a[3]}.`), c, [String(a[3])]) }]);
bank("k3", "new", [() => { const n = fR(4, 9), m = fR(2, n); return fT(`Máy đếm từ 0. ${n} bạn xếp hàng. Bạn đứng thứ ${m} (bạn đầu hàng là thứ 1) được máy gán số mấy?`, m - 1, `Thứ ${m} thì có ${m - 1} người đứng trước, và máy gán đúng số người đứng trước.`) }]);
bank("k3", "verdict", [KV("Nam nói: 'máy đếm từ 0 nên bạn đầu hàng được gán số 1'. Nam nói đúng hay sai?", "Nam nói: 'bạn đầu hàng được gán số 0 vì chưa có ai đứng trước'. Nam nói đúng hay sai?", "Số máy gán bằng số người đứng trước", "Máy gán số thứ tự bắt đầu từ 1", "Máy gán ngẫu nhiên", "Sai: bạn đầu hàng được gán 0.")]);
bank("k3", "read", [() => { const n = fR(3, 9); return aNum(`Hàng có ${n} bạn, máy đếm từ 0. Số LỚN NHẤT máy gán là mấy?`, n - 1, `Từ 0 đến ${n - 1}: ${n} số, số lớn nhất là ${n - 1}.`, [n, n + 1]) }]);
bank("k4", "new", [() => { const x = fR(2, 6), y = fR(1, 4); return fT(`Hộp "a" chứa ${x}. Em bỏ thêm ${y} vào hộp "a". Hộp "a" giờ chứa mấy?`, x + y, `${x} + ${y} = ${x + y}.`) }]);
bank("k4", "read", [() => { const n = aPick(["bi", "keo", "sach"]), v = fR(3, 9); return fC(`Hộp có nhãn "${n}" đang chứa ${v}. Đề hỏi: GIÁ TRỊ nằm trong hộp là gì?`, [String(v), n, "hộp"], `Giá trị là thứ nằm TRONG hộp (${v}); "${n}" là tên dán bên ngoài.`) }]);
bank("k6", "new", [() => { const t = fR(3, 7), v = aPick([t - 1, t, t + 1]), r = v > t ? "Đỏ" : "Xanh"; return fC(`Luật: nếu số lớn hơn ${t} thì tô đỏ, nếu không thì tô xanh. Số ${v} được tô màu gì?`, [r, ...["Đỏ", "Xanh", "Cả hai"].filter(x => x != r)], v > t ? `${v} lớn hơn ${t}.` : `${v} không lớn hơn ${t}.`) }]);
bank("k6", "read", [() => { const t = fR(3, 8); return fC(`Luật: nếu số LỚN HƠN HOẶC BẰNG ${t} thì tô đỏ. Số ${t} có được tô đỏ không?`, [`Có, vì ${t} bằng ${t}`, "Không", "Không đủ thông tin"], `"Hoặc bằng" nghĩa là gặp đúng ${t} cũng thỏa.`) }]);
bank("k7", "new", [() => { const k = fR(2, 4), n = fR(2, 5), s = fR(1, 4), g = s + k * n; return fT(`Việc "thêm ${k} viên" được lặp cho đến khi hộp có đúng ${g} viên. Hộp đang có ${s} viên. Phải lặp mấy lần?`, n, `(${g} - ${s}) / ${k} = ${n}.`) }]);
bank("k7", "read", [() => { const s = fR(3, 9); return aNum(`Hộp đang có ${s} viên. Lặp 0 lần việc "thêm 2 viên". Hộp có bao nhiêu viên?`, s, `Lặp 0 lần nghĩa là không làm gì: vẫn ${s}.`, [s + 2, 0]) }]);
bank("a2", "new", [() => { const a = xArr(5, 1, 9), c = `a = ${pJ(a)}\nprint(a[2] + a[0])`; return aPy(fT(`${fPre(c)}In ra số mấy?`, a[2] + a[0], `a[2] = ${a[2]}, a[0] = ${a[0]}: ${a[2] + a[0]}.`), c, [String(a[2] + a[0])]) }]);
bank("a2", "verdict", [KV("Hà nói: 'mảng có 5 hộp thì chỉ số hợp lệ là 1 đến 5'. Hà nói đúng hay sai?", "Hà nói: 'mảng có 5 hộp thì chỉ số hợp lệ là 0 đến 4'. Hà nói đúng hay sai?", "Chỉ số đầu là 0, chỉ số cuối là số hộp trừ 1", "Chỉ số bắt đầu từ 1", "Chỉ số cuối bằng số hộp", "Sai: chỉ số hợp lệ là 0 đến 4.")]);
bank("a2", "read", [() => { const a = xArr(3, 1, 9), c = `a = ${pJ(a)}\nprint(a[len(a)])`; return aPy(fC(`${fPre(c)}Đọc kỹ chỉ số trong ngoặc vuông. Chuyện gì xảy ra?`, ["Báo lỗi IndexError: len(a) là 3, nhưng chỉ số lớn nhất chỉ là 2", `In ra ${a[2]}`, "In ra 0"], "len(a) bằng số hộp, còn chỉ số cuối là len(a) - 1."), c, [], "IndexError") }]);
bank("a3", "new", [() => { const a = xArr(3, 1, 9), c = `a = ${pJ(a)}\na[1] = a[1] * 2\nprint(a[1])`; return aPy(fT(`${fPre(c)}In ra số mấy?`, a[1] * 2, `Lấy ${a[1]}, nhân 2, bỏ lại vào hộp 1: ${a[1] * 2}.`), c, [String(a[1] * 2)]) }]);
bank("a3", "read", [() => { const a = xArr(3, 1, 9), c = `a = ${pJ(a)}\na[3] = 9\nprint(a)`; return aPy(fC(`${fPre(c)}Mảng chỉ có 3 hộp. Chuyện gì xảy ra?`, ["Báo lỗi IndexError: không có hộp chỉ số 3 để ghi đè", `In ra ${pJ([...a, 9])}`, `In ra ${pJ(a)}`], "Ghi đè chỉ làm được với hộp đã tồn tại."), c, [], "IndexError") }]);
bank("cn", "new", [() => { const a = xArr(fR(4, 6), 1, 9), t = fR(3, 6), v = a.filter(x => x > t).length, c = `a = ${pJ(a)}\nc = 0\nfor x in a:\n    if x > ${t}:\n        c = c + 1\nprint(c)`; return aPy(fT(`${fPre(c)}In ra số mấy?`, v, `Đếm các số lớn hơn ${t}: ${v}.`), c, [String(v)]) }]);
bank("cn", "read", [() => { const t = fR(3, 6), a = pShuf([t, t, ...xArr(3, 1, 9).filter(x => x != t)]).slice(0, 5); const gt = a.filter(x => x > t).length, ge = a.filter(x => x >= t).length; if (gt == ge || gt == a.length || ge == a.length) return PRB.cn.read(); return aNum(`Mảng ${pJ(a)}. Có bao nhiêu số LỚN HƠN ${t} (không tính số bằng ${t})?`, gt, `Chỉ đếm số > ${t}: ${gt}. Nếu tính cả số bằng ${t} thì là ${ge}, một câu hỏi khác.`, [ge, a.length]) }]);
bank("p4", "new", [() => { const k = fR(1, 5), a = fR(1, 5), b = fR(1, 5), c = `def f(x):\n    return x + ${k}\nprint(f(${a}) + f(${b}))`; return aPy(fT(`${fPre(c)}In ra số mấy?`, a + b + 2 * k, `f(${a}) = ${a + k}, f(${b}) = ${b + k}: tổng ${a + b + 2 * k}.`), c, [String(a + b + 2 * k)]) }]);
bank("p4", "read", [() => { const a = fR(2, 6), c = `def g(x):\n    return x * 2\ng(${a})\nprint("xong")`; return aPy(fC(`${fPre(c)}Đọc kỹ: màn hình in ra gì?`, ['Chỉ chữ "xong"', `${2 * a} rồi xong`, String(2 * a)], `g(${a}) trả về ${2 * a} nhưng không có lệnh print nào in giá trị đó. return không phải in.`), c, ["xong"]) }]);
