/* Kiểm tra hiểu thật: đệ quy (r1-r3), linked list (n1-n3), cây (t1-t2), đồ thị (g1-g3),
   quy hoạch động (dp1-dp2), phòng debug (e1-e4). Nạp sau probe-more.js.
   Mọi câu có code đều gắn _py = {code, out, err}: tools/verify-adv.js chạy Python thật để đối chiếu đáp án. */
const aPick = a => a[Math.floor(Math.random() * a.length)];
const aPy = (o, code, out, err) => { o._py = { code, out: out || [], err: err || "" }; return o };
const aNum = (q, right, w, wr) => { const o = [String(right)]; for (const x of (wr || []).concat([right + 1, right - 1, right + 2, right - 2, right * 2])) { if (o.length >= 3) break; if (x >= 0 && !o.includes(String(x))) o.push(String(x)) } return fC(q, o, w) };
const aInt = (q, right, w, wr) => { const o = [String(right)]; for (const x of (wr || []).concat([right - 1, right + 1, right - 2, right + 2, 0])) { if (o.length >= 3) break; if (!o.includes(String(x))) o.push(String(x)) } return fC(q, o, w) };
const aStr = (q, right, pool, w) => fC(q, [right, ...pShuf(pool.filter(x => x != right)).slice(0, 2)], w);
const aNm = ["An", "Binh", "Chi", "Dung", "Ha", "Khoa", "Lan"];

/* ===== r1: đệ quy, bài nhỏ hơn giống hệt bài lớn ===== */
const DEM = "def dem(n):\n    if n == 0:\n        return 0\n    return n + dem(n - 1)\n";
PRB.r1 = {
  same: () => { const n = fR(2, 6), t = n * (n + 1) / 2, c = DEM + `print(dem(${n}))`; return aPy(fT(`${fPre(c)}In ra mấy?`, t, `dem(${n}) = ${n} + dem(${n - 1}) = ... cộng từ 1 đến ${n}.`), c, [String(t)]) },
  flip: () => { const n = fR(2, 6), t = n * (n + 1) / 2; return fT(`Với dem(n) = n + dem(n - 1) và dem(0) = 0, biết dem(?) = ${t}. Dấu ? là mấy?`, n, `dem(1)=1, dem(2)=3, dem(3)=6, ... dem(${n})=${t}.`) },
  new: () => { const n = fR(2, 6), c = `def gap(n):\n    if n == 0:\n        return 0\n    return 2 + gap(n - 1)\nprint(gap(${n}))`; return aPy(fT(`${fPre(c)}In ra mấy?`, 2 * n, `Mỗi tầng cộng 2, có ${n} tầng, gốc là 0: ${2 * n}.`), c, [String(2 * n)]) },
  verdict: KV("Hà nói: 'hàm đệ quy cứ gọi lại chính nó với đúng cùng n thì sẽ giải được dần'. Hà nói đúng hay sai?", "Hà nói: 'mỗi lần gọi đệ quy bài toán phải nhỏ đi một chút để cuối cùng chạm ca cơ sở'. Hà nói đúng hay sai?", "Bài phải nhỏ dần để chạm được ca cơ sở", "Bài càng lớn dần càng tốt", "Không cần quan tâm n", "Sai: không nhỏ đi thì không bao giờ tới ca cơ sở."),
  read: () => { const n = fR(3, 6), t = n * (n + 1) / 2; return aNum(`${fPre(DEM)}Đề hỏi: khi gọi dem(${n}), hàm dem được GỌI tổng cộng bao nhiêu lần (kể cả lần đầu)? Đề KHÔNG hỏi giá trị trả về.`, n + 1, `Đếm số lần gọi: dem(${n}) xuống dem(0) là ${n + 1} lần. ${t} là giá trị trả về, không phải số lần gọi.`, [t, n]) }
};
bank("r1", "new", [() => { const n = fR(2, 5), c = `def luy(n):\n    if n == 0:\n        return 1\n    return 2 * luy(n - 1)\nprint(luy(${n}))`; return aPy(fT(`${fPre(c)}In ra mấy? (chú ý ca cơ sở trả về mấy)`, 2 ** n, `luy(0) = 1, mỗi tầng nhân 2: 2^${n} = ${2 ** n}.`), c, [String(2 ** n)]) }]);
bank("r1", "verdict", [KV("Nam nói: 'dem(3) không cần biết dem(2), nó tự tính được một mình'. Nam nói đúng hay sai?", "Nam nói: 'muốn có dem(3) thì phải có dem(2) trước'. Nam nói đúng hay sai?", "dem(3) được xây từ kết quả của bài nhỏ hơn", "Mỗi lần gọi độc lập hoàn toàn", "dem(3) bằng dem(2)", "Sai: dem(3) = 3 + dem(2).")]);
bank("r1", "read", [() => { const n = fR(2, 5), t = n * (n + 1) / 2, c = `def dem(n):\n    if n == 0:\n        return 1\n    return n + dem(n - 1)\nprint(dem(${n}))`; return aPy(aNum(`${fPre(c)}Nhìn giống dem đã học nhưng đọc kỹ: in ra mấy?`, t + 1, `Ca cơ sở đổi thành return 1, nên kết quả hơn bài cũ 1: ${t + 1}.`, [t, t + 2]), c, [String(t + 1)]) }]);

/* ===== r2: ca cơ sở và thứ tự in ra ===== */
const DD = "def dd(n):\n    if n == 0:\n        print(\"xong\")\n        return\n    print(n)\n    dd(n - 1)\n";
const EE = "def e(n):\n    if n == 0:\n        return\n    e(n - 1)\n    print(n)\n";
PRB.r2 = {
  same: () => { const n = fR(3, 6), k = fR(2, n), c = DD + `dd(${n})`, out = []; for (let i = n; i >= 1; i--) out.push(String(i)); out.push("xong"); return aPy(fT(`${fPre(c)}Dòng thứ ${k} in ra số mấy?`, n - k + 1, `In ra ${out.join(", ")}. Dòng ${k} là ${n - k + 1}.`), c, out) },
  flip: () => { const n = fR(3, 6); return fT(`${fPre(EE)}Gọi e(?) thì màn hình in ra lần lượt 1, 2, ..., ${n} (dòng cuối là ${n}). Dấu ? là mấy?`, n, `e(n) in 1 đến n, dòng cuối là n.`) },
  new: () => { const n = fR(2, 5), c = `def u(n):\n    if n == 0:\n        return\n    u(n - 1)\n    print(n * 10)\nu(${n})`; return aPy(fT(`${fPre(c)}Dòng CUỐI CÙNG in ra số mấy?`, n * 10, `print nằm sau lời gọi, in từ nhỏ đến lớn: 10, 20, ..., ${n * 10}.`), c, Array.from({ length: n }, (_, i) => String((i + 1) * 10))) },
  verdict: KV("Nam nói: 'print đặt SAU lời gọi đệ quy thì in từ lớn xuống nhỏ'. Nam nói đúng hay sai?", "Nam nói: 'print đặt TRƯỚC lời gọi đệ quy in lúc đi xuống, đặt SAU thì in lúc quay về'. Nam nói đúng hay sai?", "Print sau lời gọi phải đợi các tầng sâu hơn xong", "Print luôn chạy trước", "Vị trí print không ảnh hưởng", "Sai: print sau lời gọi in lúc quay về, tức từ nhỏ lên lớn."),
  read: () => { const n = fR(3, 6), c = `def e(n):\n    if n == 0:\n        return\n    print(n)\n    e(n - 1)\ne(${n})`; return aPy(aNum(`${fPre(c)}Nhìn giống hàm e đã học nhưng đọc kỹ code. Dòng ĐẦU TIÊN in ra số mấy?`, n, `Lần này print nằm TRƯỚC lời gọi, nên dòng đầu là ${n}.`, [1, 0]), c, Array.from({ length: n }, (_, i) => String(n - i))) }
};
bank("r2", "new", [() => { const n = fR(2, 3), k = fR(1, 2 * n), seq = []; const s = m => { if (m == 0) return; seq.push(m); s(m - 1); seq.push(m) }; s(n); const c = `def s(n):\n    if n == 0:\n        return\n    print(n)\n    s(n - 1)\n    print(n)\ns(${n})`; return aPy(fT(`${fPre(c)}Dòng thứ ${k} in ra số mấy?`, seq[k - 1], `Thứ tự: ${seq.join(", ")}. Đi xuống in một lần, quay về in thêm một lần.`), c, seq.map(String)) }]);
bank("r2", "verdict", [KV("Hà nói: 'hàm đệ quy thiếu ca cơ sở vẫn tự dừng bình thường'. Hà nói đúng hay sai?", "Hà nói: 'hàm đệ quy thiếu ca cơ sở sẽ gọi mãi và Python báo RecursionError'. Hà nói đúng hay sai?", "Không có điểm dừng thì không gì ngăn việc gọi tiếp", "Python tự biết chỗ dừng", "Hàm trả về 0", "Sai: thiếu ca cơ sở là lỗi đệ quy phổ biến nhất.")]);
bank("r2", "read", [() => { const n = fR(2, 5), c = DD + `dd(${n})`, out = []; for (let i = n; i >= 1; i--) out.push(String(i)); out.push("xong"); return aPy(aNum(`${fPre(c)}Gọi dd(${n}). Có bao nhiêu DÒNG được in ra màn hình (kể cả dòng "xong")?`, n + 1, `${n} dòng số và 1 dòng "xong" = ${n + 1}.`, [n, n + 2]), c, out) }]);

/* ===== r3: mỗi lần gọi là một tầng ===== */
const aDepth = (code, fnCall) => code;
PRB.r3 = {
  same: () => { const n = fR(3, 9), c = `c = 0\ndef dem(n):\n    global c\n    c += 1\n    if n == 0:\n        return 0\n    return n + dem(n - 1)\ndem(${n})\nprint(c)`; return aPy(fT(`${fPre(DEM)}Gọi dem(${n}). Tổng cộng có bao nhiêu lần gọi hàm dem (kể cả lần đầu)?`, n + 1, `dem(${n}), dem(${n - 1}), ..., dem(0): ${n + 1} lần.`), c, [String(n + 1)]) },
  flip: () => { const n = fR(3, 12); return fT(`Gọi dem(?) thì có đúng ${n + 1} tầng gọi chồng nhau (tính cả dem(0)). Dấu ? là mấy?`, n, `n + 1 tầng nên n = ${n}.`) },
  new: () => { const n = aPick([4, 6, 8, 10]), cnt = m => m <= 0 ? 1 : 1 + cnt(m - 2), c = `c = 0\ndef ha(n):\n    global c\n    c += 1\n    if n <= 0:\n        return\n    ha(n - 2)\nha(${n})\nprint(c)`, vis = "def ha(n):\n    if n <= 0:\n        return\n    ha(n - 2)\n"; return aPy(fT(`${fPre(vis)}Gọi ha(${n}). Tổng cộng có bao nhiêu lần gọi hàm ha (kể cả lần đầu)?`, cnt(n), `${n}, ${n - 2}, ... đến khi n <= 0: ${cnt(n)} lần.`), c, [String(cnt(n))]) },
  verdict: KV("Hà nói: 'đệ quy không tốn thêm bộ nhớ nào so với vòng lặp'. Hà nói đúng hay sai?", "Hà nói: 'mỗi lần gọi đệ quy giữ một tầng bộ nhớ cho tới khi quay về'. Hà nói đúng hay sai?", "Mỗi lời gọi chưa xong phải được giữ lại", "Python xóa ngay mỗi lời gọi", "Chỉ tầng đầu tiên được giữ", "Sai: dem(n) cần n + 1 tầng cùng lúc."),
  read: () => { const n = fR(2, 4), c = `d = 0\nbest = 0\ndef k(n):\n    global d, best\n    d += 1\n    best = max(best, d)\n    if n > 0:\n        k(n - 1)\n        k(n - 1)\n    d -= 1\nk(${n})\nprint(best)`, vis = "def k(n):\n    if n == 0:\n        return\n    k(n - 1)\n    k(n - 1)\n", tot = 2 ** (n + 1) - 1; return aPy(aNum(`${fPre(vis)}Gọi k(${n}). TỐI ĐA bao nhiêu tầng gọi tồn tại CÙNG LÚC? (không hỏi tổng số lần gọi)`, n + 1, `Độ sâu tối đa là ${n + 1}. ${tot} là tổng số lần gọi, một câu hỏi khác.`, [tot, n]), c, [String(n + 1)]) }
};
bank("r3", "new", [() => { const m = fR(3, 7), a = Array.from({ length: m }, () => fR(1, 9)), vis = `def tong(a, i):\n    if i == len(a):\n        return 0\n    return a[i] + tong(a, i + 1)\nprint(tong(${JSON.stringify(a)}, 0))`, c = `d = 0\nbest = 0\ndef tong(a, i):\n    global d, best\n    d += 1\n    best = max(best, d)\n    r = 0 if i == len(a) else a[i] + tong(a, i + 1)\n    d -= 1\n    return r\ntong(${JSON.stringify(a)}, 0)\nprint(best)`; return aPy(fT(`${fPre(vis)}Danh sách có ${m} phần tử. Tối đa bao nhiêu tầng gọi tong tồn tại cùng lúc?`, m + 1, `Từ i = 0 đến i = ${m}: ${m + 1} tầng.`), c, [String(m + 1)]) }]);
bank("r3", "verdict", [KV("Nam nói: 'Python cho phép đệ quy sâu vô hạn'. Nam nói đúng hay sai?", "Nam nói: 'Python giới hạn độ sâu đệ quy (mặc định khoảng 1000), vượt thì RecursionError'. Nam nói đúng hay sai?", "Mỗi tầng tốn bộ nhớ nên phải có giới hạn", "Bộ nhớ vô hạn", "Giới hạn là 10", "Sai: có giới hạn, khoảng 1000 mặc định.")]);
bank("r3", "read", [() => aPy(aNum(`${fPre(DEM)}Gọi dem(0). Hàm dem được gọi bao nhiêu lần?`, 1, "Chỉ lần gọi đầu tiên, rồi gặp ca cơ sở và dừng.", [0, 2]), "c = 0\ndef dem(n):\n    global c\n    c += 1\n    if n == 0:\n        return 0\n    return n + dem(n - 1)\ndem(0)\nprint(c)", ["1"])]);

/* ===== n1: linked list, mỗi nút biết nút kế tiếp ===== */
const ANUT = "class Nut:\n    def __init__(self, v):\n        self.v = v\n        self.next = None\n";
const nChain = vals => { const nm = ["a", "b", "c", "d", "e"].slice(0, vals.length); return nm.map((x, i) => `${x} = Nut(${vals[i]})`).join("\n") + "\n" + nm.slice(0, -1).map((x, i) => `${x}.next = ${nm[i + 1]}`).join("\n") + "\n" };
const nExpr = k => "a" + ".next".repeat(k) + ".v";
PRB.n1 = {
  same: () => { const v = pDistinct(3, 9), k = fR(0, 2), c = ANUT + nChain(v) + `print(${nExpr(k)})`; return aPy(fT(`${fPre(c)}In ra số mấy?`, v[k], `${nExpr(k)}: đi theo mũi tên ${k} lần từ a, lấy .v của nút đó = ${v[k]}.`), c, [String(v[k])]) },
  flip: () => { const v = pDistinct(3, 9), t = fR(0, 2), c = ANUT + nChain(v); return aPy(aStr(`${fPre(c)}Muốn in ra số ${v[t]}, dùng print của biểu thức nào?`, nExpr(t), [nExpr(0), nExpr(1), nExpr(2)], `Số ${v[t]} nằm ở nút cách a ${t} mũi tên: ${nExpr(t)}.`), c + `print(${nExpr(t)})`, [String(v[t])]) },
  new: () => { const v = pDistinct(4, 9), k = fR(2, 3), c = ANUT + nChain(v) + `print(${nExpr(k)})`; return aPy(fT(`${fPre(c)}Bốn toa tàu nối nhau. In ra số mấy?`, v[k], `Đi ${k} mũi tên từ a: ${v[k]}.`), c, [String(v[k])]) },
  verdict: KV("Hà nói: 'từ nút đầu có thể nhảy thẳng tới nút thứ 100 trong một bước, giống nums[99]'. Hà nói đúng hay sai?", "Hà nói: 'muốn tới nút thứ 100 phải đi theo từng mũi tên next, từng nút một'. Hà nói đúng hay sai?", "Mỗi nút chỉ biết nút kế tiếp của nó", "Linked list có chỉ số như mảng", "Có một bảng tra vị trí", "Sai: không có chỉ số, phải đi từng nút."),
  read: () => { const v = pDistinct(3, 9), c = ANUT + `a = Nut(${v[0]}); b = Nut(${v[1]}); c = Nut(${v[2]})\na.next = c\nb.next = c\nprint(a.next.v)`; return aPy(aNum(`${fPre(c)}Đọc kỹ các dòng nối. In ra số mấy?`, v[2], `a.next được nối thẳng tới c (bỏ qua b), nên a.next.v = ${v[2]}.`, [v[1], v[0]]), c, [String(v[2])]) }
};
bank("n1", "new", [() => { const k = fR(4, 9); return fT(`Một hàng người xếp liền nhau, mỗi người chỉ biết người đứng ngay sau mình. Muốn tới người thứ ${k} (người đầu tiên là thứ 1) bắt đầu từ người đầu, cần đi qua mấy lần .next?`, k - 1, `Người thứ 1 đã ở sẵn, mỗi bước .next tiến thêm một người: ${k - 1} bước.`) }]);
bank("n1", "verdict", [KV("Nam nói: 'nút cuối của linked list có next trỏ về nút đầu tiên'. Nam nói đúng hay sai?", "Nam nói: 'nút cuối của linked list có next là None'. Nam nói đúng hay sai?", "None đánh dấu không còn nút nào phía sau", "Nút cuối trỏ về đầu", "next của nút cuối là 0", "Sai: nút cuối có next là None.")]);
bank("n1", "read", [() => { const v = pDistinct(3, 9), c = ANUT + nChain(v) + "print(c.next.v)"; return aPy(fC(`${fPre(c)}Đọc kỹ dòng print. Chuyện gì xảy ra?`, ["Báo lỗi AttributeError, vì c.next là None nên không có .v", String(v[0]), String(v[1])], "c là nút cuối, c.next là None. None không có thuộc tính v."), c, [], "AttributeError") }]);

/* ===== n2: đi dọc danh sách ===== */
const nLoop = "cur = a\nwhile cur is not None:\n    print(cur.v)\n    cur = cur.next";
const nLine = vals => { const nm = ["a", "b", "c", "d", "e"].slice(0, vals.length); return nm.map((x, i) => `${x} = Nut(${vals[i]})`).join("; ") + "\n" + nm.slice(0, -1).map((x, i) => `${x}.next = ${nm[i + 1]}`).join("; ") + "\n" };
PRB.n2 = {
  same: () => { const m = fR(3, 5), v = pDistinct(m, 9), k = fR(1, m), c = ANUT + nLine(v) + nLoop; return aPy(fT(`${fPre(c)}Dòng thứ ${k} in ra số mấy?`, v[k - 1], `In lần lượt ${v.join(", ")}.`), c, v.map(String)) },
  flip: () => { const v = pDistinct(3, 9), s = v[0] + v[1] + v[2]; return fT(`Danh sách có 3 nút, giá trị lần lượt ${v[0]}, ${v[1]} và một nút cuối chưa biết. Vòng while cộng dồn giá trị mọi nút vào s rồi in ra ${s}. Nút cuối có giá trị mấy?`, v[2], `${s} - ${v[0]} - ${v[1]} = ${v[2]}.`) },
  new: () => { const m = fR(3, 5), v = pDistinct(m, 9), c = ANUT + nLine(v) + "n = 0\ncur = a\nwhile cur is not None:\n    n += 1\n    cur = cur.next\nprint(n)"; return aPy(fT(`${fPre(c)}In ra mấy?`, m, `Mỗi nút cộng 1 vào n: ${m} nút.`), c, [String(m)]) },
  verdict: KV("Hà nói: 'vòng while duyệt linked list phải biết trước danh sách dài bao nhiêu'. Hà nói đúng hay sai?", "Hà nói: 'vòng while duyệt linked list tự dừng khi cur trở thành None'. Hà nói đúng hay sai?", "Sau nút cuối cur trở thành None", "Phải đếm trước độ dài", "Vòng while dừng sau 10 vòng", "Sai: dừng nhờ None, không cần biết trước độ dài."),
  read: () => { const m = fR(3, 5), v = pDistinct(m, 9), c = ANUT + nLine(v) + "cur = a\nwhile cur.next is not None:\n    print(cur.v)\n    cur = cur.next"; return aPy(aNum(`${fPre(c)}Nhìn giống vòng duyệt đã học. Đọc kỹ điều kiện while: có bao nhiêu dòng được in?`, m - 1, `Khi cur ở nút cuối, cur.next là None nên vòng dừng TRƯỚC khi in nút cuối: ${m - 1} dòng.`, [m, m + 1]), c, v.slice(0, -1).map(String)) }
};
bank("n2", "new", [() => { const m = fR(4, 5), v = Array.from({ length: m }, () => fR(1, 9)), t = fR(3, 6), cnt = v.filter(x => x > t).length, c = ANUT + nLine(v) + `n = 0\ncur = a\nwhile cur is not None:\n    if cur.v > ${t}:\n        n += 1\n    cur = cur.next\nprint(n)`; return aPy(fT(`${fPre(c)}In ra mấy?`, cnt, `Giá trị: ${v.join(", ")}. Có ${cnt} giá trị lớn hơn ${t}.`), c, [String(cnt)]) }]);
bank("n2", "verdict", [KV("Nam nói: 'duyệt hết linked list n nút chỉ mất một bước'. Nam nói đúng hay sai?", "Nam nói: 'duyệt hết linked list n nút cần n bước, tức O(n)'. Nam nói đúng hay sai?", "Mỗi nút cần một bước nhảy", "Chỉ cần nhảy tới nút cuối", "Số bước là n bình phương", "Sai: mỗi nút một bước, tổng n bước.")]);
bank("n2", "read", [() => { const m = fR(3, 5), v = pDistinct(m, 9), c = ANUT + nLine(v) + "cur = a.next\nwhile cur is not None:\n    print(cur.v)\n    cur = cur.next"; return aPy(aNum(`${fPre(c)}Đọc kỹ dòng cur = ... đầu tiên. Dòng ĐẦU TIÊN in ra số mấy?`, v[1], `Vòng bắt đầu từ a.next, tức nút thứ hai: ${v[1]}.`, [v[0], v[2]]), c, v.slice(1).map(String)) }]);

/* ===== n3: chèn vào đầu ===== */
PRB.n3 = {
  same: () => { const [x, y, z] = pDistinct(3, 9), k = fR(1, 2), e = k == 1 ? "head.next.v" : "head.next.next.v", c = ANUT + `a = Nut(${x}); b = Nut(${y})\na.next = b\nhead = a\nnew = Nut(${z})\nnew.next = head\nhead = new\nprint(${e})`, r = k == 1 ? x : y; return aPy(fT(`${fPre(c)}In ra số mấy?`, r, `Sau khi chèn, thứ tự là ${z}, ${x}, ${y}. ${e} = ${r}.`), c, [String(r)]) },
  flip: () => { const [x, y, z] = pDistinct(3, 9); return fT(`Sau khi chèn một nút vào đầu danh sách, vòng duyệt in ra ${z}, ${x}, ${y} (3 dòng). Trước khi chèn, nút đầu tiên của danh sách có giá trị mấy?`, x, `Nút mới là ${z} (đứng đầu), nên danh sách cũ là ${x}, ${y}, và nó bắt đầu bằng ${x}.`) },
  new: () => { const [x, p, q] = pDistinct(3, 9), k = fR(1, 2), e = k == 1 ? "head.next.v" : "head.next.next.v", c = ANUT + `a = Nut(${x})\nhead = a\nn1 = Nut(${p})\nn1.next = head\nhead = n1\nn2 = Nut(${q})\nn2.next = head\nhead = n2\nprint(${e})`, r = k == 1 ? p : x; return aPy(fT(`${fPre(c)}Chèn vào đầu hai lần. In ra số mấy?`, r, `Thứ tự cuối cùng: ${q}, ${p}, ${x}. ${e} = ${r}.`), c, [String(r)]) },
  verdict: KV("Hà nói: 'viết head = new trước rồi new.next = head vẫn nối đúng vào nút cũ'. Hà nói đúng hay sai?", "Hà nói: 'phải viết new.next = head trước, rồi mới đổi head = new'. Hà nói đúng hay sai?", "Đổi head trước thì mất đường tới nút cũ", "Thứ tự hai dòng không quan trọng", "Python tự sắp xếp lại", "Sai: đổi head trước làm mất nút cũ."),
  read: () => { const [x, y, z] = pDistinct(3, 9), c = ANUT + `a = Nut(${x}); b = Nut(${y})\na.next = b\nhead = a\nnew = Nut(${z})\nnew.next = head\nprint(head.v)`; return aPy(aNum(`${fPre(c)}Đọc kỹ từng dòng, đừng đoán theo ý định. In ra số mấy?`, x, `Dòng head = new bị thiếu, nên head vẫn là nút a: ${x}. ${z} chưa phải đầu danh sách.`, [z, y]), c, [String(x)]) }
};
bank("n3", "new", [() => { const n = fR(5, 9); return aNum(`Một mảng có ${n} phần tử. Chèn một số mới vào ĐẦU mảng thì phải dịch bao nhiêu phần tử sang phải một ô?`, n, `Mọi phần tử đều phải dịch: ${n}. Với linked list chỉ đổi hai mũi tên.`, [1, 2]) }]);
bank("n3", "verdict", [KV("Nam nói: 'chèn vào đầu linked list 1 triệu nút phải đi qua cả triệu nút'. Nam nói đúng hay sai?", "Nam nói: 'chèn vào đầu linked list chỉ đổi hai mũi tên, không phụ thuộc độ dài'. Nam nói đúng hay sai?", "Không cần đi qua các nút phía sau", "Phải đi hết danh sách", "Chèn đầu là O(n)", "Sai: chèn đầu là O(1).")]);
bank("n3", "read", [() => { const [x, y, z] = pDistinct(3, 9), c = ANUT + `a = Nut(${x}); b = Nut(${y})\na.next = b\nhead = a\nnew = Nut(${z})\nb.next = new\nprint(head.next.next.v)`; return aPy(aNum(`${fPre(c)}Nút mới được gắn vào đâu? In ra số mấy?`, z, `new được gắn SAU b (cuối danh sách), không phải đầu: ${x}, ${y}, ${z}.`, [y, x]), c, [String(z)]) }]);

/* ===== t1: cây, nút cha và nút con ===== */
const ACAY = "class Cay:\n    def __init__(self, v):\n        self.v = v\n        self.left = None\n        self.right = None\n";
function tGen(k) { const vals = pDistinct(k, 9), nodes = [{ v: vals[0], path: "r", l: -1, r: -1 }], lines = [`r = Cay(${vals[0]})`]; for (let i = 1; i < k; i++) { const sl = []; nodes.forEach((n, j) => { if (n.l < 0) sl.push([j, "left"]); if (n.r < 0) sl.push([j, "right"]) }); const [j, sd] = aPick(sl), nn = { v: vals[i], path: nodes[j].path + "." + sd, l: -1, r: -1 }; nodes[j][sd == "left" ? "l" : "r"] = i; nodes.push(nn); lines.push(`${nn.path} = Cay(${nn.v})`) } return { nodes, code: ACAY + lines.join("\n") + "\n" } }
const tIdx = (T, p) => T.nodes.findIndex(n => n.path == p);
const tPre = (T, i) => i < 0 ? [] : [T.nodes[i].v, ...tPre(T, T.nodes[i].l), ...tPre(T, T.nodes[i].r)];
const tPost = (T, i) => i < 0 ? [] : [...tPost(T, T.nodes[i].l), ...tPost(T, T.nodes[i].r), T.nodes[i].v];
const tH = (T, i) => i < 0 ? 0 : 1 + Math.max(tH(T, T.nodes[i].l), tH(T, T.nodes[i].r));
const tLeaf = T => T.nodes.filter(n => n.l < 0 && n.r < 0).length;
const tLeafPy = "def la(n):\n    if n is None:\n        return 0\n    if n.left is None and n.right is None:\n        return 1\n    return la(n.left) + la(n.right)\n";
PRB.t1 = {
  same: () => { const T = tGen(4), ps = T.nodes.map(n => n.path), p = aPick(ps), n = T.nodes[tIdx(T, p)], c = T.code + `print(${p}.v)`; return aPy(fT(`${fPre(c)}In ra số mấy?`, n.v, `${p} là nút ở đường đi đó, giá trị ${n.v}.`), c, [String(n.v)]) },
  flip: () => { const T = tGen(4), ps = T.nodes.map(n => n.path), t = aPick(ps), v = T.nodes[tIdx(T, t)].v; return aPy(aStr(`${fPre(T.code)}Muốn in ra số ${v}, dùng print của biểu thức nào?`, t + ".v", ps.map(p => p + ".v"), `Số ${v} nằm ở nút ${t}.`), T.code + `print(${t}.v)`, [String(v)]) },
  new: () => { const T = tGen(fR(5, 6)), k = T.nodes.length - 1; return fT(`Thư mục gốc r có sẵn. Mỗi dòng "... = Cay(...)" dưới đây thêm đúng một thư mục con.${fPre(T.code)}Tổng cộng cây thư mục có bao nhiêu nút (kể cả gốc r)?`, k + 1, `1 gốc + ${k} dòng thêm = ${k + 1}.`) },
  verdict: KV("Hà nói: 'mọi nút trong cây đều có đúng hai nút con'. Hà nói đúng hay sai?", "Hà nói: 'nút không có con gọi là lá, left và right của nó đều là None'. Hà nói đúng hay sai?", "Nhiều nút có 0 hoặc 1 con", "Mọi nút đều có hai con", "Nút lá luôn có hai con", "Sai: lá không có con."),
  read: () => { const T = tGen(4), miss = T.nodes.map(n => n.path).flatMap(p => [p + ".left", p + ".right"]).filter(p => tIdx(T, p) < 0), p = aPick(miss), c = T.code + `print(${p}.v)`; return aPy(fC(`${fPre(T.code)}Đọc kỹ cây vừa dựng. Chạy print(${p}.v) thì sao?`, [`Báo lỗi AttributeError, vì ${p} là None`, String(T.nodes[0].v), String(T.nodes[1].v)], `${p} chưa được gán nên là None, None không có .v.`), c, [], "AttributeError") }
};
bank("t1", "new", [() => { const T = tGen(fR(4, 6)), c = T.code + tLeafPy + "print(la(r))"; return aPy(fT(`${fPre(T.code)}Nút không có con nào là LÁ. Cây trên có bao nhiêu lá?`, tLeaf(T), `Lá là nút có left và right đều None: ${tLeaf(T)} nút.`), c, [String(tLeaf(T))]) }]);
bank("t1", "verdict", [KV("Nam nói: 'cây và linked list giống hệt nhau, mỗi nút một mũi tên đi ra'. Nam nói đúng hay sai?", "Nam nói: 'trong cây nhị phân mỗi nút có thể có tới hai mũi tên đi ra: left và right'. Nam nói đúng hay sai?", "Cây nhị phân có thể rẽ trái hoặc phải", "Mỗi nút có đúng một mũi tên", "Cây không có mũi tên", "Sai: cây có thể rẽ nhánh, linked list thì không.")]);
bank("t1", "read", [() => { const T = tGen(4), p = aPick(T.nodes.map(n => n.path).filter(x => x != "r")), n = T.nodes[tIdx(T, p)], c = T.code + `print(${p}.v)`, others = T.nodes.filter(x => x.v != n.v).map(x => String(x.v)); return aPy(fC(`${fPre(T.code)}Đọc kỹ: print(${p}.v) in ra số mấy?`, [String(n.v), ...others.slice(0, 2)], `${p} là nút có giá trị ${n.v}.`), c, [String(n.v)]) }]);

/* ===== t2: duyệt cây bằng đệ quy ===== */
const DEMC = "def dem(nut):\n    if nut is None:\n        return 0\n    return 1 + dem(nut.left) + dem(nut.right)\n";
const PREP = "def p(nut):\n    if nut is None:\n        return\n    print(nut.v)\n    p(nut.left)\n    p(nut.right)\n";
const POSTP = "def p(nut):\n    if nut is None:\n        return\n    p(nut.left)\n    p(nut.right)\n    print(nut.v)\n";
PRB.t2 = {
  same: () => { const k = fR(3, 6), T = tGen(k), c = T.code + DEMC + "print(dem(r))"; return aPy(fT(`${fPre(c.replace(/\n$/, ""))}In ra mấy?`, k, `dem đếm mỗi nút một lần: ${k} nút.`), c, [String(k)]) },
  flip: () => { const a = fR(2, 5), b = fR(1, 4); return fT(`Biết dem(r) = 1 + dem(r.left) + dem(r.right). Với một cây có dem(r) = ${a + b + 1} và dem(r.left) = ${a}, thì dem(r.right) bằng mấy?`, b, `${a + b + 1} - 1 - ${a} = ${b}.`) },
  new: () => { const T = tGen(fR(3, 5)), s = T.nodes.reduce((x, n) => x + n.v, 0), c = T.code + "def tong(nut):\n    if nut is None:\n        return 0\n    return nut.v + tong(nut.left) + tong(nut.right)\nprint(tong(r))"; return aPy(fT(`${fPre(c)}In ra mấy?`, s, `Cộng giá trị mọi nút: ${T.nodes.map(n => n.v).join(" + ")} = ${s}.`), c, [String(s)]) },
  verdict: KV("Hà nói: 'hàm dem trên cây cần vòng for để đi qua từng nút'. Hà nói đúng hay sai?", "Hà nói: 'hàm dem trên cây dừng nhờ ca cơ sở: gặp None thì trả về 0'. Hà nói đúng hay sai?", "Bài nhỏ hơn là cây con trái và cây con phải", "Cây cần vòng for", "dem không có ca cơ sở", "Sai: đệ quy đã tự đi qua mọi nút, không cần for."),
  read: () => { const T = tGen(fR(4, 6)), c = T.code + POSTP + "p(r)", out = tPost(T, 0), first = out[0], pre = tPre(T, 0); const pool = T.nodes.map(n => String(n.v)); return aPy(aStr(`${fPre(c)}Nhìn giống hàm p đã học nhưng đọc kỹ vị trí print. Dòng ĐẦU TIÊN in ra số mấy?`, String(first), pool, `print nằm SAU hai lời gọi, nên in lúc quay về: nút sâu nhất bên trái in trước (${first}), gốc in cuối.`), c, out.map(String)) }
};
bank("t2", "new", [() => { const T = tGen(fR(3, 6)), h = tH(T, 0), c = T.code + "def cao(nut):\n    if nut is None:\n        return 0\n    return 1 + max(cao(nut.left), cao(nut.right))\nprint(cao(r))"; return aPy(fT(`${fPre(c)}Hàm cao tính số tầng của cây. In ra mấy?`, h, `Đường dài nhất từ gốc xuống lá có ${h} nút.`), c, [String(h)]) }]);
bank("t2", "verdict", [KV("Nam nói: 'dem(None) phải trả về số nút của cả cây'. Nam nói đúng hay sai?", "Nam nói: 'dem(None) trả về 0 vì cây rỗng không có nút nào'. Nam nói đúng hay sai?", "Ca cơ sở: cây rỗng có 0 nút", "None là cả cây", "dem(None) báo lỗi", "Sai: cây rỗng có 0 nút.")]);
bank("t2", "read", [() => { const T = tGen(fR(4, 6)), c = T.code + PREP + "p(r)", out = tPre(T, 0), n = T.nodes.length; return aPy(aNum(`${fPre(c)}Gọi p(r). Có bao nhiêu dòng được in ra?`, n, `Mỗi nút in đúng một lần; None không in gì: ${n} dòng.`, [n + 1, n - 1]), c, out.map(String)) }]);

/* ===== g1: đồ thị, nút và đường nối ===== */
function gGen(n, extra) { const ns = pShuf(aNm).slice(0, n), adj = {}; ns.forEach(x => adj[x] = []); const add = (a, b) => { adj[a].push(b); adj[b].push(a) }; for (let i = 1; i < n; i++) add(ns[i], ns[fR(0, i - 1)]); let t = 0; while (extra > 0 && t++ < 60) { const a = aPick(ns), b = aPick(ns); if (a != b && !adj[a].includes(b)) { add(a, b); extra-- } } return { ns, adj, lit: gLit(ns, adj) } }
const gLit = (ns, adj) => "ban = {\n" + ns.map(x => `    "${x}": [${adj[x].map(y => `"${y}"`).join(", ")}]`).join(",\n") + "\n}\n";
const gEdges = adj => Object.values(adj).reduce((s, l) => s + l.length, 0) / 2;
const gBfs = (adj, s, popLast) => { const q = [s], seen = new Set([s]), out = []; while (q.length) { const x = popLast ? q.pop() : q.shift(); out.push(x); for (const y of adj[x]) if (!seen.has(y)) { seen.add(y); q.push(y) } } return out };
const gDfs = (adj, s) => { const seen = new Set(), out = []; const f = x => { seen.add(x); out.push(x); for (const y of adj[x]) if (!seen.has(y)) f(y) }; f(s); return out };
const gDfsPost = (adj, s) => { const seen = new Set(), out = []; const f = x => { seen.add(x); for (const y of adj[x]) if (!seen.has(y)) f(y); out.push(x) }; f(s); return out };
const gDist = (adj, s, t) => { const d = { [s]: 0 }, q = [s]; while (q.length) { const x = q.shift(); for (const y of adj[x]) if (!(y in d)) { d[y] = d[x] + 1; q.push(y) } } return d[t] };
const BFSC = s => `q = ["${s}"]\nseen = {"${s}"}\nwhile q:\n    x = q.pop(0)\n    print(x)\n    for y in ban[x]:\n        if y not in seen:\n            seen.add(y)\n            q.append(y)`;
const DFSC = s => `seen = set()\ndef dfs(x):\n    seen.add(x)\n    print(x)\n    for y in ban[x]:\n        if y not in seen:\n            dfs(y)\ndfs("${s}")`;
const gUniq = (adj, f) => { const d = Object.keys(adj).map(x => [x, adj[x].length]), m = f(...d.map(x => x[1])), w = d.filter(x => x[1] == m); return w.length == 1 ? w[0][0] : null };
PRB.g1 = {
  same: () => { const G = gGen(5, fR(0, 2)), x = aPick(G.ns), c = G.lit + `print(len(ban["${x}"]))`; return aPy(fT(`${fPre(c)}In ra mấy?`, G.adj[x].length, `${x} có ${G.adj[x].length} bạn trong danh sách.`), c, [String(G.adj[x].length)]) },
  flip: () => { const e = fR(3, 7); return fT(`Một đồ thị vô hướng có ${e} đường nối (mỗi đường chỉ đếm một lần), ghi bằng dictionary như bài học. Nếu cộng độ dài của TẤT CẢ các danh sách bạn trong dictionary, ra mấy?`, 2 * e, `Mỗi đường nối được ghi hai lần (một lần ở mỗi đầu): ${e} x 2 = ${2 * e}.`) },
  new: () => { const G = gGen(5, fR(0, 2)), x = aPick(G.ns), c = G.lit.replace("ban", "duong") + `print(len(duong["${x}"]))`; return aPy(fT(`${fPre(c)}Mỗi khóa là một thành phố, danh sách là các thành phố có đường nối trực tiếp. Từ ${x} có bao nhiêu đường đi thẳng ra ngoài?`, G.adj[x].length, `Đếm các thành phố trong danh sách của ${x}.`), c, [String(G.adj[x].length)]) },
  verdict: KV("Hà nói: 'đồ thị vô hướng chỉ cần ghi mỗi đường nối ở MỘT phía của dictionary'. Hà nói đúng hay sai?", "Hà nói: 'đồ thị vô hướng phải ghi mỗi đường nối ở CẢ HAI phía'. Hà nói đúng hay sai?", "Nếu An là bạn của Binh thì Binh cũng là bạn của An", "Ghi một phía là đủ", "Phía còn lại Python tự thêm", "Sai: phải ghi cả hai phía."),
  read: () => { let G, w; do { G = gGen(5, 2); w = gUniq(G.adj, Math.min) } while (!w); return aStr(`${fPre(G.lit)}Đọc kỹ: ai có ÍT bạn nhất?`, w, G.ns, `${w} có ${G.adj[w].length} bạn, ít nhất (không phải nhiều nhất).`) }
};
bank("g1", "new", [() => { const G = gGen(5, fR(0, 2)), c = G.lit + "n = 0\nfor x in ban:\n    n += len(ban[x])\nprint(n // 2)"; return aPy(fT(`${fPre(c)}Đoạn code này đếm số đường nối. In ra mấy?`, gEdges(G.adj), `Tổng độ dài các danh sách chia 2: mỗi đường nối được ghi hai lần.`), c, [String(gEdges(G.adj))]) }]);
bank("g1", "verdict", [KV("Nam nói: 'trong đồ thị mỗi nút chỉ được nối với đúng hai nút khác'. Nam nói đúng hay sai?", "Nam nói: 'trong đồ thị một nút có thể nối với số nút bất kỳ'. Nam nói đúng hay sai?", "Danh sách bạn của mỗi nút có độ dài tùy ý", "Mỗi nút đúng 2 bạn", "Mỗi nút đúng 1 bạn", "Sai: số bạn tùy từng nút.")]);
bank("g1", "read", [() => { const G = gGen(5, fR(0, 2)), n = G.ns.length, e = gEdges(G.adj); return aNum(`${fPre(G.lit)}Đọc kỹ đề: dictionary này có bao nhiêu NGƯỜI (khóa)? Không hỏi số đường nối.`, n, `Đếm các khóa: ${n} người. Số đường nối là ${e}, một câu hỏi khác.`, [e, 2 * e]) }]);

/* ===== g2: BFS ===== */
PRB.g2 = {
  same: () => { const G = gGen(5, fR(0, 2)), s = aPick(G.ns), o = gBfs(G.adj, s), k = fR(2, 5), c = G.lit + BFSC(s); return aPy(aStr(`${fPre(c)}Dòng thứ ${k} in ra tên ai?`, o[k - 1], G.ns, `Thứ tự BFS: ${o.join(", ")}.`), c, o) },
  flip: () => { const d = fR(2, 4); return fT(`BFS xuất phát từ S, in S ở dòng 1. S có đúng ${d} bạn trực tiếp. Mọi bạn trực tiếp của S đều được in trước bất kỳ bạn-của-bạn nào. Vậy các bạn trực tiếp của S được in ở các dòng từ 2 đến dòng số mấy?`, d + 1, `${d} bạn trực tiếp chiếm các dòng 2 đến ${d + 1}, vì BFS xét hết lớp gần trước rồi mới sang lớp xa.`) },
  new: () => { const G = gGen(5, fR(0, 2)), [s, t] = pShuf(G.ns), d = gDist(G.adj, s, t), c = G.lit + `from collections import deque\nd = {"${s}": 0}\nq = deque(["${s}"])\nwhile q:\n    x = q.popleft()\n    for y in ban[x]:\n        if y not in d:\n            d[y] = d[x] + 1\n            q.append(y)\nprint(d["${t}"])`; return aPy(fT(`${fPre(G.lit)}Mỗi khóa là một ga tàu, danh sách là các ga nối trực tiếp. Đi từ ga ${s} tới ga ${t}, ít nhất phải qua bao nhiêu đường nối?`, d, `Đi từng lớp từ ${s}: ga ở lớp ${d} là ${t}.`), c, [String(d)]) },
  verdict: KV("Hà nói: 'BFS dùng stack (vào sau ra trước)'. Hà nói đúng hay sai?", "Hà nói: 'BFS dùng queue (vào trước ra trước) nên xét hết nút gần rồi mới tới nút xa'. Hà nói đúng hay sai?", "Vào trước ra trước giữ nguyên thứ tự từng lớp", "Vào sau ra trước", "Không cần cấu trúc nào", "Sai: BFS dùng queue."),
  read: () => { let G, s, o, p; do { G = gGen(5, fR(1, 2)); s = aPick(G.ns); o = gBfs(G.adj, s); p = gBfs(G.adj, s, true) } while (o[2] == p[2]); const c = G.lit + BFSC(s).replace("q.pop(0)", "q.pop()"); return aPy(aStr(`${fPre(c)}Nhìn giống BFS nhưng đọc kỹ dòng x = q.pop(). Dòng thứ 3 in ra tên ai?`, p[2], G.ns, `q.pop() lấy phần tử CUỐI (như stack), thứ tự là ${p.join(", ")}, không phải thứ tự BFS ${o.join(", ")}.`), c, p) }
};
bank("g2", "new", [() => { const k = fR(3, 6), c = `q = [1]\nfor i in range(${k}):\n    x = q.pop(0)\n    q.append(x * 2)\n    q.append(x * 2 + 1)\nprint(x)`; return aPy(fT(`${fPre(c)}In ra mấy?`, k, `Mỗi lần lấy phần tử ĐẦU hàng đợi, các số được lấy ra theo thứ tự 1, 2, 3, ...: lần thứ ${k} là ${k}.`), c, [String(k)]) }]);
bank("g2", "verdict", [KV("Nam nói: 'BFS không cần tập seen vì đồ thị không có đường vòng'. Nam nói đúng hay sai?", "Nam nói: 'BFS cần tập seen để không xét lại một nút nhiều lần'. Nam nói đúng hay sai?", "An là bạn Binh, Binh là bạn An nên dễ quay vòng", "Đồ thị không bao giờ quay vòng", "seen chỉ để cho đẹp", "Sai: đường nối hai chiều tự tạo vòng quay lại.")]);
bank("g2", "read", [() => { let G, s; do { G = gGen(5, fR(0, 2)); s = aPick(G.ns) } while (s == G.ns[0]); const c = G.lit + BFSC(s); return aPy(aStr(`${fPre(c)}Đọc kỹ dòng q = [...] đầu tiên. Dòng ĐẦU TIÊN in ra tên ai?`, s, G.ns, `BFS bắt đầu từ ${s} (không phải khóa đầu tiên trong dictionary).`), c, gBfs(G.adj, s)) }]);

/* ===== g3: DFS ===== */
PRB.g3 = {
  same: () => { const G = gGen(5, fR(0, 2)), s = aPick(G.ns), o = gDfs(G.adj, s), k = fR(2, 5), c = G.lit + DFSC(s); return aPy(aStr(`${fPre(c)}Dòng thứ ${k} in ra tên ai?`, o[k - 1], G.ns, `Thứ tự DFS: ${o.join(", ")}.`), c, o) },
  flip: () => aPy(fC("DFS in nút S ở dòng 1 và nút X ở dòng 2. X và S có quan hệ nào?", ["X là bạn trực tiếp của S", "X cách S đúng 2 bước", "Không có quan hệ nào"], "Ngay sau khi in S, dfs gọi dfs(y) cho bạn đầu tiên y của S, và y được in ngay."), "", []),
  new: () => { const A = gGen(3, fR(0, 1)), B = gGen(2, 0), names = pShuf(aNm), a = names.slice(0, 3), b = names.slice(3, 5), adj = {}; a.forEach((x, i) => adj[x] = []); b.forEach(x => adj[x] = []); const add = (u, v) => { adj[u].push(v); adj[v].push(u) }; add(a[1], a[0]); add(a[2], a[fR(0, 1)]); add(b[1], b[0]); const ns = pShuf(Object.keys(adj)), s = aPick(a), c = gLit(ns, adj) + DFSC(s); return aPy(fT(`${fPre(c)}Có bao nhiêu dòng được in ra?`, 3, `dfs chỉ đi được tới những nút nối với ${s}: nhóm ${a.join(", ")}. Nhóm kia không có đường tới.`), c, gDfs(adj, s)) },
  verdict: KV("Hà nói: 'DFS luôn tìm được đường đi ít bước nhất'. Hà nói đúng hay sai?", "Hà nói: 'BFS đảm bảo đường ít bước nhất, DFS có thể đi một đường vòng dài trước'. Hà nói đúng hay sai?", "DFS đi sâu một hướng trước khi thử hướng khác", "DFS xét từng lớp", "DFS luôn ngắn nhất", "Sai: chỉ BFS đảm bảo điều đó."),
  read: () => { const G = gGen(5, fR(0, 2)), s = aPick(G.ns), o = gDfsPost(G.adj, s), c = G.lit + DFSC(s).replace("    print(x)\n", "").replace("            dfs(y)\n", "            dfs(y)\n    print(x)\n"); return aPy(aStr(`${fPre(c)}Nhìn giống dfs đã học nhưng đọc kỹ vị trí print. Dòng ĐẦU TIÊN in ra tên ai?`, o[0], G.ns, `print nằm SAU vòng for nên in lúc quay về. Thứ tự: ${o.join(", ")}.`), c, o) }
};
bank("g3", "new", [() => { const names = pShuf(aNm), a = names.slice(0, 3), b = names.slice(3, 5), adj = {}; a.concat(b).forEach(x => adj[x] = []); const add = (u, v) => { adj[u].push(v); adj[v].push(u) }; add(a[1], a[0]); add(a[2], a[fR(0, 1)]); add(b[1], b[0]); const ns = pShuf(Object.keys(adj)), c = gLit(ns, adj) + "seen = set()\ndef dfs(x):\n    seen.add(x)\n    for y in ban[x]:\n        if y not in seen:\n            dfs(y)\nnhom = 0\nfor x in ban:\n    if x not in seen:\n        dfs(x)\n        nhom += 1\nprint(nhom)"; return aPy(fT(`${fPre(c)}In ra mấy? (mỗi lần dfs chạy xong là đi hết một nhóm bạn nối nhau)`, 2, "Có hai nhóm tách rời nhau, nên dfs được khởi động từ ngoài đúng 2 lần."), c, ["2"]) }]);
bank("g3", "verdict", [KV("Nam nói: 'hàm dfs không cần điều kiện dừng'. Nam nói đúng hay sai?", "Nam nói: 'dfs dừng nhờ seen: khi mọi bạn đã được thăm thì không gọi tiếp'. Nam nói đúng hay sai?", "Điều kiện y not in seen chặn các lời gọi thừa", "dfs tự dừng", "dfs gọi vô hạn", "Sai: thiếu seen thì dfs quay vòng mãi.")]);
bank("g3", "read", [() => { const G = gGen(5, fR(0, 2)), s = aPick(G.ns), c = G.lit + DFSC(s), o = gDfs(G.adj, s); return aPy(aStr(`${fPre(c)}Đọc kỹ đề: dòng ĐẦU TIÊN in ra tên ai? (đừng tính trước cả đường đi)`, s, G.ns, `dfs("${s}") in ${s} ngay lập tức, trước mọi lời gọi đệ quy.`), c, o) }]);

/* ===== dp1: quy hoạch động, đừng tính lại ===== */
const FIB = "def fib(n):\n    if n < 2:\n        return n\n    return fib(n - 1) + fib(n - 2)\n";
const fibv = n => n < 2 ? n : fibv(n - 1) + fibv(n - 2);
const fibCalls = (n, t) => { let c = 0; const f = m => { if (m == t) c++; if (m < 2) return; f(m - 1); f(m - 2) }; f(n); return c };
PRB.dp1 = {
  same: () => { const n = fR(4, 8), c = FIB + `print(fib(${n}))`; return aPy(fT(`${fPre(c)}In ra mấy? (fib(0) = 0, fib(1) = 1)`, fibv(n), `Dãy: 0, 1, 1, 2, 3, 5, 8, 13, 21: fib(${n}) = ${fibv(n)}.`), c, [String(fibv(n))]) },
  flip: () => { const n = fR(3, 8); return fT(`Với fib(0) = 0, fib(1) = 1, fib(n) = fib(n - 1) + fib(n - 2), biết fib(?) = ${fibv(n)}. Dấu ? là mấy?`, n, `Dãy 0, 1, 1, 2, 3, 5, 8, 13, 21: ${fibv(n)} đứng ở vị trí ${n}.`) },
  new: () => { const n = fR(4, 7), c = `c = 0\ndef fib(n):\n    global c\n    if n == 2:\n        c += 1\n    if n < 2:\n        return n\n    return fib(n - 1) + fib(n - 2)\nfib(${n})\nprint(c)`; return aPy(fT(`${fPre(FIB)}Tính fib(${n}) bằng cách thuần này (không ghi nhớ). Hàm fib(2) bị gọi bao nhiêu lần?`, fibCalls(n, 2), `Đếm các lời gọi fib(2) trong cây gọi: ${fibCalls(n, 2)}.`), c, [String(fibCalls(n, 2))]) },
  verdict: KV("Hà nói: 'ghi nhớ kết quả (memo) làm kết quả của fib khác đi so với tính thuần'. Hà nói đúng hay sai?", "Hà nói: 'memo giữ nguyên kết quả, chỉ bỏ việc tính lại những bài con đã tính'. Hà nói đúng hay sai?", "Mỗi bài con chỉ tính một lần rồi tra lại", "Kết quả bị sai khác", "Memo chỉ làm đẹp code", "Sai: kết quả giữ nguyên, chỉ nhanh hơn."),
  read: () => { const n = fR(4, 6); const c = `c = 0\ndef fib(n):\n    global c\n    if n == 1:\n        c += 1\n    if n < 2:\n        return n\n    return fib(n - 1) + fib(n - 2)\nfib(${n})\nprint(c)`; return aPy(aNum(`${fPre(FIB)}Đọc kỹ đề: khi tính fib(${n}), hàm fib(1) (KHÔNG phải fib(2)) bị gọi bao nhiêu lần?`, fibCalls(n, 1), `Đếm riêng fib(1): ${fibCalls(n, 1)} lần. fib(2) bị gọi ${fibCalls(n, 2)} lần, một câu hỏi khác.`, [fibCalls(n, 2), fibCalls(n, 0)]), c, [String(fibCalls(n, 1))]) }
};
bank("dp1", "new", [() => { const n = fR(3, 6), tot = (m => { let c = 0; const f = k => { c++; if (k < 2) return; f(k - 1); f(k - 2) }; f(m); return c })(n), c = `c = 0\ndef fib(n):\n    global c\n    c += 1\n    if n < 2:\n        return n\n    return fib(n - 1) + fib(n - 2)\nfib(${n})\nprint(c)`; return aPy(fT(`${fPre(FIB)}Tính fib(${n}) bằng cách thuần này. Tổng cộng hàm fib được gọi bao nhiêu lần (kể cả lần đầu)?`, tot, `Đếm mọi lời gọi trong cây: ${tot}.`), c, [String(tot)]) }]);
bank("dp1", "verdict", [KV("Nam nói: 'tính fib(50) bằng cách thuần vẫn nhanh vì máy tính mạnh'. Nam nói đúng hay sai?", "Nam nói: 'mỗi bậc số lần gọi tăng gần gấp đôi nên fib(50) thuần rất chậm'. Nam nói đúng hay sai?", "Cùng một bài con bị tính đi tính lại rất nhiều lần", "Máy mạnh thì mọi thứ đều nhanh", "fib(50) chỉ gọi 50 lần", "Sai: số lần gọi tăng theo cấp số nhân.")]);
bank("dp1", "read", [() => { const n = fR(2, 5), c = `def fib(n):\n    if n < 2:\n        return 1\n    return fib(n - 1) + fib(n - 2)\nprint(fib(${n}))`, v = (m => { const f = k => k < 2 ? 1 : f(k - 1) + f(k - 2); return f(m) })(n); return aPy(aNum(`${fPre(c)}Nhìn giống fib đã học nhưng đọc kỹ ca cơ sở. In ra mấy?`, v, `Ca cơ sở đổi thành return 1 nên số lớn hơn fib thường. Kết quả ${v}, không phải ${fibv(n)}.`, [fibv(n), v + 1]), c, [String(v)]) }]);

/* ===== dp2: bảng quy hoạch động, leo cầu thang ===== */
const stairs = (n, steps) => { const w = [1]; for (let i = 1; i <= n; i++) { w[i] = 0; for (const s of steps) if (i - s >= 0) w[i] += w[i - s] } return w[n] };
PRB.dp2 = {
  same: () => { const n = fR(3, 7), code = `w = [1, 1, 2]\nfor i in range(3, ${n + 1}):\n    w.append(w[i - 1] + w[i - 2])\nprint(w[${n}])`; return aPy(fT(`Mỗi lần bước 1 hoặc 2 bậc. Lên bậc ${n} có bao nhiêu cách? (bậc 1: 1 cách, bậc 2: 2 cách)`, stairs(n, [1, 2]), `Mỗi bậc bằng tổng hai bậc ngay trước: 1, 2, 3, 5, 8, 13, 21 ...`), code, [String(stairs(n, [1, 2]))]) },
  flip: () => { const k = fR(1, 4), a = stairs(k + 2, [1, 2]), b = stairs(k + 1, [1, 2]); return fT(`Mỗi lần bước 1 hoặc 2 bậc. Lên bậc ${k + 2} có ${a} cách, lên bậc ${k + 1} có ${b} cách. Lên bậc ${k} có bao nhiêu cách?`, a - b, `cách(${k + 2}) = cách(${k + 1}) + cách(${k}), nên cách(${k}) = ${a} - ${b} = ${a - b}.`) },
  new: () => { const n = fR(4, 7), v = stairs(n, [1, 3]), c = `def dem(n):\n    if n < 0:\n        return 0\n    if n == 0:\n        return 1\n    return dem(n - 1) + dem(n - 3)\nprint(dem(${n}))`; return aPy(fT(`Lần này mỗi bước đi 1 hoặc 3 bậc (không còn 2). Lên bậc ${n} có bao nhiêu cách? Hãy tự nghĩ: bước cuối cùng đến từ những bậc nào?`, v, `cách(n) = cách(n - 1) + cách(n - 3), tính từ cách(0) = 1 lên dần: kết quả ${v}.`), c, [String(v)]) },
  verdict: KV("Hà nói: 'cách(n) = cách(n - 1) x cách(n - 2)'. Hà nói đúng hay sai?", "Hà nói: 'cách(n) = cách(n - 1) + cách(n - 2)'. Hà nói đúng hay sai?", "Bước cuối là một trong hai khả năng khác nhau, các cách cộng lại", "Hai khả năng nhân với nhau", "Chỉ có một khả năng", "Sai: hai nhóm cách khác nhau thì cộng, không nhân."),
  read: () => { const k = fR(1, 4), w = [1, 2, 3, 5, 8]; return aNum(`dp = [${w.join(", ")}] là bảng số cách leo cầu thang, dp[0] ứng với BẬC 1. Đọc kỹ: dp[${k}] là số cách lên bậc mấy?`, k + 1, `dp[0] là bậc 1 nên dp[${k}] là bậc ${k + 1}. Chỉ số lệch một so với số bậc.`, [k, k + 2]) }
};
bank("dp2", "new", [() => { const n = fR(3, 8), v = stairs(n, [1, 2]); return fT(`Xếp một dải dài ${n} ô bằng các viên gạch dài 1 ô và dài 2 ô (xếp liền nhau, không chồng). Có bao nhiêu cách xếp khác nhau?`, v, `Viên gạch cuối là dài 1 (còn ${n - 1} ô) hoặc dài 2 (còn ${n - 2} ô): cùng công thức với leo cầu thang, kết quả ${v}.`) }]);
bank("dp2", "verdict", [KV("Nam nói: 'mỗi khi cần dp[i] phải tính lại từ đầu mọi ô trước'. Nam nói đúng hay sai?", "Nam nói: 'dp[i] chỉ cần đọc lại hai ô trước đã được tính sẵn'. Nam nói đúng hay sai?", "Các ô trước đã nằm sẵn trong bảng", "Phải tính lại từ đầu", "Bảng không lưu gì", "Sai: bảng lưu kết quả để khỏi tính lại.")]);
bank("dp2", "read", [() => { const n = fR(3, 6), w = [1, 1]; for (let i = 2; i <= n; i++) w.push(w[i - 1] + w[i - 2]); const c = `dp = [1, 1]\nfor i in range(2, ${n + 1}):\n    dp.append(dp[i - 1] + dp[i - 2])\nprint(dp[${n}])`, lesson = stairs(n + 1, [1, 2]); return aPy(aNum(`${fPre(c)}Nhìn giống bảng leo cầu thang nhưng đọc kỹ giá trị khởi đầu. In ra mấy?`, w[n], `Khởi đầu [1, 1] cho ra 1, 1, 2, 3, 5, ...: dp[${n}] = ${w[n]}.`, [lesson, w[n] + 1]), c, [String(w[n])]) }]);

/* ===== e1: đọc thông báo lỗi ===== */
const ERRS = ["IndexError", "KeyError", "NameError", "TypeError"];
const eCase = () => { const t = aPick(["I", "K", "N"]); if (t == "I") { const m = fR(3, 5), a = Array.from({ length: m }, () => fR(1, 9) * 10), k = m + fR(0, 2), c = `nums = ${JSON.stringify(a)}\nprint(nums[${k}])`; return { c, e: "IndexError" } } if (t == "K") { const k = aPick(["c", "d", "z"]), c = `d = {"a": 1, "b": 2}\nprint(d["${k}"])`; return { c, e: "KeyError" } } const nm = aPick(["tong", "dem", "kq"]), c = `x = 5\nprint(${nm})`; return { c, e: "NameError" } };
PRB.e1 = {
  same: () => { const s = eCase(); return aPy(aStr(`${fPre(s.c)}Chạy đoạn này sẽ gặp lỗi gì?`, s.e, ERRS, `Tên lỗi cho biết loại sự cố: ${s.e}.`), s.c, [], s.e) },
  flip: () => { const n = fR(3, 8); return fT(`Một danh sách có ${n} phần tử. Chỉ số NHỎ NHẤT mà truy cập vào sẽ gây IndexError là mấy?`, n, `Chỉ số hợp lệ là 0 đến ${n - 1}, nên ${n} là chỉ số đầu tiên vượt quá.`) },
  new: () => { const k = aPick(["cam", "xoai", "mit"]), c = `gia = {"tao": 10, "le": 12}\nprint(gia["${k}"])`; return aPy(aStr(`${fPre(c)}Chạy đoạn này gặp lỗi gì?`, "KeyError", ERRS, `Tra khóa "${k}" chưa có trong dictionary: KeyError.`), c, [], "KeyError") },
  verdict: KV("Hà nói: 'NameError là lỗi chỉ số vượt quá độ dài danh sách'. Hà nói đúng hay sai?", "Hà nói: 'NameError nghĩa là Python chưa biết một cái tên, thường do dùng biến chưa tạo'. Hà nói đúng hay sai?", "Tên lỗi cho biết loại sự cố", "NameError là chỉ số sai", "NameError là chia cho 0", "Sai: chỉ số vượt quá là IndexError."),
  read: () => { const k = fR(4, 8), c = `print("a")\nprint("b")\nnums = [1, 2, 3]\nprint(nums[${k}])\nprint("c")`; return aPy(aNum(`${fPre(c)}Đọc kỹ: trước khi gặp lỗi, màn hình đã in ra bao nhiêu dòng?`, 2, `Hai dòng "a" và "b" chạy bình thường, tới nums[${k}] thì dừng, "c" không bao giờ in.`, [0, 3]), c, ["a", "b"], "IndexError") }
};
bank("e1", "new", [() => { const m = fR(3, 5), a = Array.from({ length: m }, () => fR(1, 9)), c = `a = ${JSON.stringify(a)}\nfor i in range(len(a)):\n    print(a[i + 1])`, py = `a = ${JSON.stringify(a)}\ntry:\n    for i in range(len(a)):\n        a[i + 1]\nexcept IndexError:\n    print(i)`; return aPy(fT(`${fPre(c)}Chương trình dừng với IndexError. Lúc đó biến i bằng mấy?`, m - 1, `i = ${m - 1} là lần cuối, a[${m}] không tồn tại.`), py, [String(m - 1)]) }]);
bank("e1", "verdict", [KV("Nam nói: 'đọc thông báo lỗi là mất thời gian vì nó chẳng cho biết gì'. Nam nói đúng hay sai?", "Nam nói: 'tên lỗi và số dòng cho biết loại sự cố và nơi xảy ra'. Nam nói đúng hay sai?", "Thông báo lỗi là bản đồ chỉ chỗ cần xem", "Thông báo lỗi vô nghĩa", "Chỉ cần đoán", "Sai: thông báo lỗi cho manh mối cụ thể.")]);
bank("e1", "read", [() => { const c = `nums = [1, 2, 3]\nif len(nums) > 5:\n    print(nums[7])\nprint("xong")`; return aPy(fC(`${fPre(c)}Đọc kỹ: chạy đoạn này chuyện gì xảy ra?`, ["Không lỗi, in xong, vì dòng nums[7] không được chạy", "IndexError", "NameError"], "Điều kiện len(nums) > 5 sai nên nhánh chứa nums[7] bị bỏ qua."), c, ["xong"]) }]);

/* ===== e2: lệch một ===== */
const e2c = a => `nums = ${JSON.stringify(a)}\ntotal = 0\nfor i in range(len(nums) - 1):\n    total += nums[i]\nprint(total)`;
PRB.e2 = {
  same: () => { const m = fR(3, 5), a = Array.from({ length: m }, () => fR(1, 9)), s = a.slice(0, -1).reduce((x, y) => x + y, 0), c = e2c(a); return aPy(fT(`${fPre(c)}In ra mấy? Dò từng vòng bằng tay.`, s, `Chỉ cộng ${m - 1} phần tử đầu: ${s}. Phần tử cuối ${a[m - 1]} bị bỏ sót.`), c, [String(s)]) },
  flip: () => { const x = fR(1, 9), s = fR(3, 15); return fT(`Một vòng lặp lỗi lệch một in ra tổng ${s}, trong khi tổng đúng là ${s + x}. Nó bỏ sót phần tử cuối. Phần tử cuối có giá trị mấy?`, x, `${s + x} - ${s} = ${x}.`) },
  new: () => { const m = fR(3, 5), a = Array.from({ length: m }, () => fR(1, 9)), s = a.slice(1).reduce((x, y) => x + y, 0), c = `nums = ${JSON.stringify(a)}\ntotal = 0\nfor i in range(1, len(nums)):\n    total += nums[i]\nprint(total)`; return aPy(fT(`${fPre(c)}In ra mấy?`, s, `range(1, len) bắt đầu từ chỉ số 1, bỏ qua phần tử đầu ${a[0]}: tổng ${s}.`), c, [String(s)]) },
  verdict: KV("Hà nói: 'range(len(nums) - 1) duyệt hết mọi phần tử của nums'. Hà nói đúng hay sai?", "Hà nói: 'range(len(nums)) cho ra 0 đến len - 1, vừa đủ mọi phần tử'. Hà nói đúng hay sai?", "range(n) dừng ở n - 1", "range(n) dừng ở n", "range(n) bắt đầu từ 1", "Sai: trừ thêm 1 là bỏ sót phần tử cuối."),
  read: () => { const x = fR(2, 9), c = e2c([x]); return aPy(fC(`${fPre(c)}Danh sách chỉ có MỘT phần tử. Đọc kỹ: in ra gì?`, ["0", String(x), "Báo lỗi"], `range(0) không chạy vòng nào, total giữ 0. Không có lỗi, chỉ có kết quả sai.`), c, ["0"]) }
};
bank("e2", "new", [() => { const m = fR(4, 5), a = Array.from({ length: m }, () => fR(1, 5)); a[m - 1] = 9; const c = `a = ${JSON.stringify(a)}\nbest = a[0]\ni = 1\nwhile i < len(a) - 1:\n    if a[i] > best:\n        best = a[i]\n    i += 1\nprint(best)`, b = Math.max(...a.slice(0, -1)); return aPy(fT(`${fPre(c)}In ra mấy?`, b, `Vòng while dừng trước phần tử cuối (9), nên 9 không bao giờ được so sánh: ${b}.`), c, [String(b)]) }]);
bank("e2", "verdict", [KV("Nam nói: 'lỗi lệch một luôn khiến Python báo IndexError'. Nam nói đúng hay sai?", "Nam nói: 'lỗi lệch một có thể không báo lỗi gì, chỉ cho kết quả sai'. Nam nói đúng hay sai?", "Bỏ sót phần tử vẫn chạy được", "Luôn báo lỗi", "Python tự sửa", "Sai: ví dụ trên chạy bình thường nhưng sai kết quả.")]);
bank("e2", "read", [() => { const m = fR(3, 5), a = Array.from({ length: m }, () => fR(1, 9)), s = a.reduce((x, y) => x + y, 0), c = `nums = ${JSON.stringify(a)}\ntotal = 0\nfor i in range(len(nums)):\n    total += nums[i]\nprint(total)`; return aPy(aNum(`${fPre(c)}Đoạn này có đúng không? In ra mấy?`, s, `Code này ĐÚNG (không có -1): tổng đầy đủ ${s}.`, [s - a[m - 1], s + 1]), c, [String(s)]) }]);

/* ===== e3: giá trị khởi tạo sai ===== */
PRB.e3 = {
  same: () => { const m = fR(3, 5), a = Array.from({ length: m }, () => fR(1, 9)), k = fR(1, 5), s = a.reduce((x, y) => x + y, 0), c = `nums = ${JSON.stringify(a)}\ntotal = ${k}\nfor x in nums:\n    total += x\nprint(total)`; return aPy(fT(`${fPre(c)}In ra mấy?`, s + k, `total bắt đầu ${k}, cộng thêm ${s}: ${s + k}. Tổng đúng là ${s}.`), c, [String(s + k)]) },
  flip: () => { const a = [fR(1, 9), fR(1, 9), fR(1, 9)], s = a[0] + a[1] + a[2], k = fR(1, 5); return fT(`nums = ${JSON.stringify(a)}. Một đoạn code cộng dồn bắt đầu từ total = ? rồi in ra ${s + k}. Giá trị khởi tạo đó là mấy?`, k, `Tổng thật là ${s}, in ra ${s + k}, nên khởi tạo là ${s + k} - ${s} = ${k}.`) },
  new: () => { const a = Array.from({ length: fR(3, 4) }, () => -fR(1, 9)), c = `nums = ${JSON.stringify(a)}\nbest = 0\nfor x in nums:\n    if x > best:\n        best = x\nprint(best)`; return aPy(fT(`${fPre(c)}Đoạn tìm số lớn nhất này in ra mấy?`, 0, `Mọi số đều âm nên không số nào lớn hơn 0: in 0, dù 0 không có trong danh sách.`), c, ["0"]) },
  verdict: KV("Hà nói: 'best = 0 an toàn cho mọi danh sách khi tìm số lớn nhất'. Hà nói đúng hay sai?", "Hà nói: 'lấy phần tử đầu tiên làm mốc luôn đúng với danh sách không rỗng'. Hà nói đúng hay sai?", "Mốc là phần tử thật của danh sách", "0 luôn nhỏ hơn mọi số", "Mốc nào cũng được", "Sai: danh sách toàn số âm sẽ cho kết quả sai."),
  read: () => { const a = [-fR(1, 9), fR(1, 9), -fR(1, 9)], c = `nums = ${JSON.stringify(a)}\nbest = 0\nfor x in nums:\n    if x > best:\n        best = x\nprint(best)`; return aPy(aInt(`${fPre(c)}Nhìn giống đoạn bị lỗi best = 0. Đọc kỹ danh sách: in ra mấy?`, a[1], `Có một số dương ${a[1]} lớn hơn 0, nên lần này vẫn ra đúng. Lỗi chỉ lộ khi mọi số đều âm.`, [0, -a[0]]), c, [String(a[1])]) }
};
bank("e3", "new", [() => { const a = Array.from({ length: fR(3, 4) }, () => fR(2, 5)), c = `nums = ${JSON.stringify(a)}\ntich = 0\nfor x in nums:\n    tich = tich * x\nprint(tich)`; return aPy(aNum(`${fPre(c)}Đoạn này định tính tích các số. In ra mấy?`, 0, `tich bắt đầu 0, nhân gì cũng ra 0. Phần tử trung hòa của phép nhân là 1.`, [a.reduce((x, y) => x * y, 1), 1]), c, ["0"]) }]);
bank("e3", "verdict", [KV("Nam nói: 'giá trị khởi tạo đúng cho phép nhân dồn là 0'. Nam nói đúng hay sai?", "Nam nói: 'giá trị khởi tạo đúng cho phép nhân dồn là 1, vì nhân 1 không làm đổi gì'. Nam nói đúng hay sai?", "Số nhân vào mà không đổi kết quả là 1", "0 nhân gì cũng ra chính nó", "Khởi tạo nào cũng được", "Sai: 0 nhân gì cũng ra 0.")]);
bank("e3", "read", [() => { const a = [-fR(1, 9), -fR(1, 9), -fR(1, 9)], m = Math.max(...a), c = `nums = ${JSON.stringify(a)}\nbest = nums[0]\nfor x in nums:\n    if x > best:\n        best = x\nprint(best)`; return aPy(aInt(`${fPre(c)}Lần này mốc là nums[0]. Danh sách toàn số âm: in ra mấy?`, m, `Mốc là phần tử thật nên kết quả đúng: ${m}. Đây là cách khởi tạo an toàn.`, [0, a[0] == m ? a[1] : a[0]]), c, [String(m)]) }]);

/* ===== e4: lỗi logic, không báo lỗi ===== */
PRB.e4 = {
  same: () => { const a = Array.from({ length: fR(3, 5) }, () => fR(1, 9)), c = `def dem_chan(nums):\n    c = 0\n    for x in nums:\n        if x % 2 == 1:\n            c += 1\n    return c\nprint(dem_chan(${JSON.stringify(a)}))`, v = a.filter(x => x % 2 == 1).length; return aPy(fT(`${fPre(c)}Hàm tên dem_chan (đếm số chẵn). Nó in ra mấy?`, v, `Điều kiện x % 2 == 1 đếm số LẺ: ${v} số lẻ trong danh sách.`), c, [String(v)]) },
  flip: () => { const n = fR(5, 9), m = fR(1, n - 1); return fT(`Hàm dem_chan bị lỗi: nó đếm số LẺ. Với một danh sách ${n} số nguyên, hàm in ra ${m}. Danh sách đó thực sự có bao nhiêu số chẵn?`, n - m, `${n} số, ${m} lẻ, nên ${n - m} chẵn.`) },
  new: () => { const a = Array.from({ length: fR(4, 6) }, () => fR(1, 9)), c = `def dem_lon(nums):\n    # dem so lon hon 5\n    c = 0\n    for x in nums:\n        if x >= 5:\n            c += 1\n    return c\nprint(dem_lon(${JSON.stringify(a)}))`, v = a.filter(x => x >= 5).length; return aPy(fT(`${fPre(c)}Hàm định đếm số LỚN HƠN 5. Nó in ra mấy với danh sách trên?`, v, `x >= 5 tính cả số 5 nên có thể đếm thừa. Kết quả thật của code: ${v}. Số lớn hơn 5 đúng là ${a.filter(x => x > 5).length}.`), c, [String(v)]) },
  verdict: KV("Hà nói: 'lỗi logic thì Python báo lỗi ngay khi chạy'. Hà nói đúng hay sai?", "Hà nói: 'lỗi logic chạy bình thường nhưng kết quả sai, chỉ test mới lộ ra'. Hà nói đúng hay sai?", "Python chỉ kiểm tra cú pháp và exception, không kiểm tra ý định của bạn", "Python hiểu ý định của bạn", "Lỗi logic luôn là SyntaxError", "Sai: lỗi logic không báo lỗi gì."),
  read: () => { const a = Array.from({ length: fR(4, 6) }, () => fR(1, 9)), lo = a.filter(x => x % 2 == 1).length, ch = a.length - lo, which = Math.random() < 0.5, c = `def dem_chan(nums):\n    c = 0\n    for x in nums:\n        if x % 2 == 1:\n            c += 1\n    return c\nprint(dem_chan(${JSON.stringify(a)}))`; return aPy(aNum(`${fPre(c)}Đọc kỹ đề, rồi trả lời: hàm trên ${which ? "THỰC SỰ IN RA" : "ĐÚNG RA PHẢI IN"} số mấy?`, which ? lo : ch, which ? `Code đếm số lẻ: in ${lo}.` : `Đúng ra phải đếm số chẵn: ${ch}.`, [which ? ch : lo, a.length]), c, [String(lo)]) }
};
bank("e4", "new", [() => { const a = aPick([[3, 4], [5, 2], [7, 8]]), c = `def co_chan(nums):\n    for x in nums:\n        if x % 2 == 0:\n            return True\n        else:\n            return False\n    return False\nprint(co_chan(${JSON.stringify(a)}))`, v = a[0] % 2 == 0; return aPy(fC(`${fPre(c)}Hàm này định kiểm tra xem danh sách có số chẵn nào không. Nó in ra gì?`, [v ? "True" : "False", v ? "False" : "True", "Báo lỗi"], `return nằm trong vòng lặp nên hàm kết thúc ngay ở phần tử đầu tiên (${a[0]}). Kết quả ${v}. Đúng ra danh sách ${JSON.stringify(a)} ${a.some(x => x % 2 == 0) ? "có" : "không có"} số chẵn.`), c, [v ? "True" : "False"]) }]);
bank("e4", "verdict", [KV("Nam nói: 'khi code chạy sai mà không báo lỗi, cứ đoán rồi sửa bừa là nhanh nhất'. Nam nói đúng hay sai?", "Nam nói: 'nên dò từng bước hoặc in giá trị từng vòng rồi so với kết quả mong đợi'. Nam nói đúng hay sai?", "Phải thấy máy đang làm gì ở từng bước", "Đoán nhanh hơn", "Xóa hết viết lại", "Sai: sửa bừa dễ gây thêm lỗi.")]);
bank("e4", "read", [() => { const a = Array.from({ length: fR(3, 5) }, () => fR(1, 9)), v = a.filter(x => x % 2 == 1).length, c = `def dem_le(nums):\n    c = 0\n    for x in nums:\n        if x % 2 == 1:\n            c += 1\n    return c\nprint(dem_le(${JSON.stringify(a)}))`; return aPy(aNum(`${fPre(c)}Hàm này tên dem_le và đếm số lẻ. Nó có đúng không? In ra mấy?`, v, `Tên hàm và việc làm khớp nhau: hàm ĐÚNG, in ${v}.`, [a.length - v, a.length]), c, [String(v)]) }]);

Object.assign(PREQ, { r1: ["p4", "p2"], r2: ["r1"], r3: ["r2"], n1: ["a3", "p4"], n2: ["n1", "p3"], n3: ["n2"], t1: ["n1"], t2: ["t1", "r2"], g1: ["d1", "a3"], g2: ["g1", "que", "d2"], g3: ["g2", "r2"], dp1: ["r2", "d1"], dp2: ["dp1", "a3", "p3"], e1: ["a3"], e2: ["sm"], e3: ["e2", "sm"], e4: ["e3", "cn"] });
